pypa/pipenv

- setup.py
`dirname` is still in [os.path](https://docs.python.org/3/library/os.path.html#os.path.dirname) in Python 3.
> fix dirname import

- pipenv/cli.py
Presently when there is no Pipfile inside a directory, running
`pip --where` gives
`Pipfile found at None. Considering this to be the project home.`.
This seems ambiguous and I've changed it to
```
$ pipenv --where
No Pipfile present at project home. Consider running `pipenv install`
first to automatically generate a Pipfile for you.
$
```
> Better output for where command when no Pipfile

- pipenv/cli.py
See at http://pexpect.sourceforge.net/pexpect.html the documentation
of interact. I include here for easy reference
| Note that if you change the window size of the parent the SIGWINCH
| signal will not be passed through to the child.
> Fixes terminal size not being set properly

- pipenv/cli.py
This ensures that it will work when running across different Python versions.
Fixes #59
> Use uncompiled version of pep508checker

- pipenv/cli.py
So, pulling the thread a bit more on kennethreitz/requests#3830, it appears Travis tests will *always* pass, regardless of failures, when run via `pipenv run`. It appears the problem is that pipenv isn't checking the exit code on the subprocess, so it always returns 0 from a successful execution of `cli.py`. This patch will allow pipenv to properly return whether or not a task succeeded to the shell.
There may be a better way to do this, but this was all I could find in the `pexpect` documentation. I used Requests' Travis build to test this and it behaves as expected with the patch. I can look into mocking up a few tests, but I wasn't sure how they would fit in with the current testing setup.
Sorry to be bombarding you with PRs today :)
> Return subprocess exit code

- pipenv/cli.py
Quick fix for #88, passing `str`/`unicode` instead of `bytes` to the parser because Python 3 can't process `bytes`.
I chose Requests' `text` property instead of `decode('utf-8')` in the event we get an unexpected page encoding, but that may be overkill. There isn't a significant increase in overhead using this since `chardet` is already being loaded with Requests, and we're parsing the whole page.
> pass unicode to parser instead of bytes

- pipenv/cli.py
This addresses an issue of trying to install bad package names which is tangential to, but possibly not completely covering, #95. I'm not sure if you'd like this to be resilient or hit a hard stop if it encounters a package it can't find.
Current repro:
```bash
>>> pipenv install notreal
File "/Users/a/Work/OpenSource/sauna-test/.venv/bin/pipenv", line 11, in <module>
load_entry_point('pipenv==3.1.9', 'console_scripts', 'pipenv')()
File "/Users/a/Work/OpenSource/sauna-test/.venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
File "/Users/a/Work/OpenSource/sauna-test/.venv/lib/python3.6/site-packages/click/core.py", line 697, in main
File …
```
> handle bad package names more gracefully

- pipenv/cli.py
This PR fixes #81 by using a list of arguments for calls to `pexpect.spawn` instead of a formateed string.
Cheers
> Use list of arguments in calls to `pexpect.spawn`

- pipenv/cli.py
This is a clarifies the error message when `$SHELL` isn't found. Certain linux environments (Alpine as shown in #104) don't have the variable set automatically, so we can let the user know they need to set it in that case.
> update error message for missing SHELL variable

- pipenv/cli.py
Use:
```sh
pipenv uninstall pytest --dev
```
to uninstall `pytest` from the `[dev-packages]` section as described in #103
> Support uninstalling of dev packages. Closes #103

- pipenv/cli.py
- pipenv/project.py
This should fix the current issues with the OrderdDict changes in the build. There's a certain amount of complexity in using OrderedDict in older versions of Python (specifically 2.6) that's already been handled in Requests. Since that is a hard dependency I leveraged it's OrderedDict implementation to spare us the headache. Hopefully that's OK.
> fixing OrderedDict

- HISTORY.txt
- pipenv/cli.py
`ensure_project` requires that both the virtualenv and pipfile are checked. The `check_pipfile` function is time consuming, especially as your Pipfile gets bigger, which can lead to multiple second delays. While this is acceptable for installation, it makes using `pipenv run` and `pipenv shell` painful as noted in #120.
Since `pipenv run` and `pipenv shell` never actually use the pipfile, we can safely skip that step and only verify the virtualenv is running. This results in an ~7x speed increase in my local testing with a pipfile of 20 entries.
Before:
```
$ time pipenv run python --version
Python 3.6.0
real	0m4.061s
user	0m1.222s
sys	0m0.136s
```
After:
```
$ time pipenv run python --version
Python 3.6.0
real	0m0.583s
user	0m0.370s
sys	0m0.087s
```
> consolidating ensure checks to virtualenv when possible

- Pipfile
- setup.py
- tests/requirements_requests.txt
I successfully installed `pipenv` with `pip` and tried to run for the first time only to encounter this error:
```
File "/Library/Frameworks/Python.framework/Versions/3.4/bin/pipenv", line 11, in <module>
load_entry_point('pipenv==3.2.4', 'console_scripts', 'pipenv')()
File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2642, in load_entry_point
return ep.load()
File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2296, in load …
```
> Qualfied version of requests required to >2.3.0

- HISTORY.txt
- pipenv/cli.py
This is an attempt to solve #129. pipenv will try to normalize all keys against the name provided in the package repository provided in [source]. This functionality broke dependencies from alternative sources, such as git. Instead of performing a hard fail on not finding a package, we will now treat normalization as a best effort. If we can't find a better option, let's trust the user to provide what they want.
> perform proper_case as best effort approach

- pipenv/cli.py
We write the Pipfile at the beginning of every run regardless of if it changed or not. Let's only record changes.
> only write file when changed

- README.rst
Pipfile is linked to it's GitHub repository. I added links for *pip* and *virtualenv*, too.
> Link pip and virtualenv projects in README

- pipenv/cli.py
- pipenv/utils.py
This addresses #148 where we had a possible overwriting condition that caused an unexpected version number to appear in some Pipfile configurations. We will now verify version numbers against hard pinned version in the Pipfile.
> verify package version before adding it to Pipfile.lock

- pipenv/cli.py
With the introduction of `--python` commands in the form `pipenv install --three --python=3.6.0` became possible. With the current ordering, `python3` will be chosen rather than the more specific `python3.6.0` command.
While users **should** only use one of these parameters, we want to give precedence to the more specific parameter. This way a `python3` binding that doesn't match 3.6.0 isn't used, creating a possibly unintended environment.
> use specified python version over --three/--two

- .gitignore
- Makefile
- docs/advanced.rst
- docs/index.rst
Adding the beginnings of an "advanced" documentation section. This provides extended commands for `pipenv install`/`pipenv uninstall` and example setups for using pipenv with Travis and tox.
> Advanced docs

- pipenv/cli.py
- test_pipenv.py
Hi! Hope you don't mind that I wrote some quick code for this. It was breaking on the dash in version 3.2.3-2 of functools32, which is preventing me from sharing some pipenv code with colleagues.
With this PR, instead of truncating the ends of versions containing dashes, it will keep them intact. Also I added some tests for the parse_download_fname function.
> Improve dashed version parsing

- pipenv/cli.py
This is a small performance-oriented followup to #175 which should ~halve the amount of regex being run!
Once the beginning of the version string has been found, the flag is no longer modified, and thus there's no reason to keep running the regex.
> Improve parse_download_fname performance

- HISTORY.txt
- docs/advanced.rst
- pipenv/cli.py
- pipenv/environments.py
I would like to be able to clean up this noise on CircleCI:
> Add PIPENV_NOSPIN option for cleaner build logs

- pipenv/cli.py
Temporarily disable spinner until a patch is merged to fix blindspin for 2.6.
> disable spinner for 2.6

- Pipfile
- pipenv/cli.py
- pipenv/project.py
- tests/test_pipenv.py
I've done the following changes:
Making `cli.proper_case` use a new method that runs through all sources in project.sources, and return the Request's return for the first one that hit OK, or neither did ok, then raise an exception.
Also doing something similar to `cli.pip_install` so that it will try to pip install for all the sources and return the first cmd that worked or the last that didn't work.
And changed `project.source` to `project.sources` and making it return a list as default instead of just the first source present.
And added some tests
> Add extra-index-url support

- docs/advanced.rst
> Add missing backtick in advanced usage docs

- pipenv/cli.py
- tests/test_pipenv.py
As stated in #231, `pip_download` (function used by the pipenv lock command) ins't using the project.sources to download the pypackages.
I changed it so that `pip_download` would work like `pip_install` and try downloading using each of the defined `project.sources` as the `index-url` in the `pip` md.
Also added some tests fo check for this behavior.
fix #231
> Make pip_download respect project.sources

- pipenv/cli.py
This makes `pipenv lock --requirements > requirements.txt` behave
properly.
> lock: output to stderr

- pipenv/cli.py
This addresses #239, and will place a restriction on shell creation with a maximum depth of 1 in the CLI. There doesn't seem to be a compelling reason for why a user would want to activate the virtualenv inside of itself, and this behaviour is causing issues for some users. pipenv will now simply print a message saying the shell is already activated and take no action.
> Only spawn shell once

- Pipfile
- Pipfile.lock
- pipenv/cli.py
- pipenv/project.py
- pipenv/utils.py
- tests/test_pipenv.py
- tests/test_project.py
- tests/test_utils.py
~This is **DO NOT MERGE** until at least later today. Still need to find some time to clean up but want to allow some time for review from anyone who's interested.~
This is an attempt to address #204, #229 and #240 which all have the same underlying issue. When dealing with Pipfile and Pipfile.lock entries we've had a lot of issues with casing and name formatting in comparisons. We'd fixed this previously for package names specified by us, or pipenv users, but missed the case with mis-cased names in other packages' `install_requires` lists.
In order to prevent this from occurring in the future, I've transitioned to using a normalized naming scheme derived from pep426 where all names will be lower-cased and use dashes in place of underscores. This should allow uniform comparison and then …
> Fix VCS dependencies

- pipenv/cli.py
When I run pip update, a lot of requirements change position in lock file. 
It hard to understood, which packages updates and in git comes lot of unnecessary changes.
> Add sort_keys param to sort lockfile

- pipenv/cli.py
- pipenv/utils.py
This will add the `--ignore-hashes` option to `pipenv install` which will allow the user to ignore package hash checking.
The implementation is a little funkier than I wanted, but if you include hashes anywhere in a requirements.txt file, it will require them for everything. This now requires us to purge all hashes read in from the Pipfile.lock before trying to install.
> add --ignore-hashes support

- pipenv/cli.py
The warning about using `--python` on Windows is shown even when `--python` is used:
> Fix redundant '--python' warning on Windows

- pipenv/cli.py
Fixes #283 
@nateprewitt thanks for the guidance on this issue. I've got a small PR here to add an explicit error message (first two commits are just cleanups of a couple things my linter caught).
"No Pipfile found" sounds a little terse to me, so if you have any suggestions for phrasing, I'd be happy to hear them.
> Handle rm when missing Pipfile

- pipenv/cli.py
- tests/test_pipenv.py
Alright, so after sitting on this for a month, I think I'm ready to pull the trigger on this. This PR addresses #270 by stripping "[implicit post release](https://www.python.org/dev/peps/pep-0440/#implicit-post-releases)" data out of the version number. This information, while important, seems to be handled under the hood by `pip`. Passing a version number with the implicit post release directly to `pip` doesn't work, so the reasonable option here seems to be removing it and allowing `pip` to give us the most recent post release.
> strip implicit post releases from version numbers in Pipfile.lock

- pipenv/cli.py
Certain combinations of Python and Windows environments (particularly on Appveyor) are returning inconsistent casing on filenames. The offending platforms are lowercasing all the content sent to standard out but downloading the filenames with "proper" casing, which causes issues in our lookup dictionary. To solve this, I'm implementing `names_map` as a `CaseInsensitiveDict` from Requests to avoid key errors.
This addresses https://github.com/kennethreitz/pipenv/issues/213#issuecomment-290963351 but is unreleated to #213 itself. This will also resolve the same issue encountered in Appveyor in kennethreitz/requests#3988.
> fix filename lookup for Windows

- pipenv/cli.py
see #315.
Pipe and redirection are working well in my Linux and Windows computer.
> use os.execl to "run" subcommand on Unix ( close #315 )

- pipenv/cli.py
This is a follow up to https://github.com/kennethreitz/pipenv/issues/208#issuecomment-296668612, which aptly points out we've had a broken uninstall command for `dev-packages` for some time.
The semantics that were defined for `--dev` is that it uninstalls every package listed in `[dev-packages]` without removing them from the Pipfile. In order to remove a package the user *should* have been able to use `pipenv uninstall package_name` but that hasn't been working.
Since we don't have a way to specify where the package exists in the Pipfile, `pipenv uninstall package_name` should probably remove `package_name` from both `[packages]` and `[dev-packages]` for consistency. Having a different/conflicting dependency for `packages` vs `dev-packages` doesn't really make sense, so in theory it …
> remove package from all locations in Pipfile

- pipenv/cli.py
When a user tries to uninstall a package from `packages`, the `dev-packages` key throws a `KeyError` in the `_pipfile` OrderedDict if they have never installed a dev package. This could be the case for new users of Pipenv who are just trying out PoCs rather than full-fledged projects. This PR fixes this.
Similarly, if a user tries to `pipenv uninstall <package>` without ever installing that package, the `packages` key throws a `KeyError`. While this is unintended usage, the user would still see a stack trace and this manifests as poor workmanship, hence fixing that too.
> Fix for key error when uninstalling [dev-]packages

- pipenv/utils.py
- tests/test_utils.py
Previously doing `pipenv install "django-rest-auth[with_social]==0.8.2` would
lose the extra information and if you edited the Pipfile by hand to
```
[[source]]
[packages.django-rest-auth]
version = "==0.8.2"
extras = [ "with_social",]
```
`pipenv update` would break with a malformed pip command.
> handle package[extra]==version properly

- pipenv/__init__.py
Packages under `pipenv/vendor` should be used than that installed by pip.
This will resolve package conflict issues like https://github.com/kennethreitz/pipenv/issues/355.
`pipenv/vendor`  will be inserted into `sys.path` after the script directory.
cf. https://docs.python.org/3/library/sys.html#sys.path, http://stackoverflow.com/a/10097543
```console
$ pip3 install click==0.4
$ pipenv
File "/usr/local/bin/pipenv", line 11, in <module>
load_entry_point('pipenv==4.0.1', 'console_scripts', 'pipenv')()
File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 560, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2648, in …
```
> Use sys.path.insert(1, v_path) instead of sys.path.append(v_path)

- pipenv/cli.py
- pipenv/utils.py
This pr makes pipenv launching faster by lazy import modules which wastes much time for initialize.
This is the part of [pprofile](https://github.com/vpelletier/pprofile) result by running `$ pprofile -m pipenv`. `import parse_requirements` wastes over half of all initialize time, `import requirements` wastes about 18%, ( and `import requests` wastes 14% ).
```
File: /tmp/pipenv/pipenv/cli.py
File duration: 0.0026648s (0.03%)
Line #|      Hits|         Time| Time per hit|      %|Source code
------+----------+-------------+-------------+-------+-----------
1|         0|            0|            0|  0.00%|# -*- coding: utf-8 -*-
2|         2|  1.50204e-05|  7.51019e-06|  0.00%|import contextlib
3|         1|  4.76837e-06|  4.76837e-06|  0.00%|import codecs
4|         1|  2.36034e-05| …
```
> Import slow modules lazily

- pipenv/cli.py
- tests/test_project.py
This will drastically reduce the amount of duplicated code for our installs now that we're performing all of them one at a time. The previous approach had required two separate conditionals due to hashes. Since we can apply require hashes on a package-by-package basis now, this division is no longer needed.
It's possible we can remove this all the way up into the Pipfile, but I haven't confirmed that yet. This patch will allow us to fix #377 and we work towards further removal in a future patch.
> Simply Dependency Installation

- pipenv/utils.py
The index argument was not being parsed because of the missing hyphen.
> hyphen missing in pip index argument

- pipenv/cli.py
`pipenv shell` on Windows throws a FileNotFoundException due to `which('activate_this.py')` returning a path containing a forward slash:
```
File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "c:\python36\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Python36\Scripts\pipenv.exe\__main__.py", line 9, in <module>
File "c:\python36\lib\site-packages\pipenv\vendor\click\core.py", line 722, in __call__
File "c:\python36\lib\site-packages\pipenv\vendor\click\core.py", line 697, in main
File "c:\python36\lib\site-packages\pipenv\vendor\click\core.py", line 1066, in invoke
File …
```
> Fixed handling of .py files on Windows

- pipenv/cli.py
Fixes #484 
If changing url of editable git repo for package, pip doesn't know what to do and asks for input which causes pipenv to crash. This change assumes that we user wants to always prefer package installed as defined in Pipfile, therefore, wiping the existing install and recloning to meet defined requirements.
Testing:
1. Create fresh venv
2. Add following contents of Pipfile
```
[[source]]
[packages]
fudge = { git = 'https://github.com/fudge-py/fudge.git', ref = 'master', editable = true }
```
3. `pipenv install` should be successful
4. update Pipfile fudge requirement url to `https://github.com/jsatt/fudge.git`
* before change, this fails with traceback similar to #484 
* after change, this succeeds
> Force reclone of editable git if url changes

- pipenv/cli.py
paths starting with the os separator are absolute paths and shouldn't be resolved with the `which` helper and should have the virtualenv activated automatically for them.
> Automatically set system flag if running command with abs path

- pipenv/utils.py
I logged the issue here: https://github.com/pypa/pip/issues/4717
Basically, the only thing standing in our way of using a third party private server (gemfury in this case) is that the pip code only catching request errors if you use their session when calling it.
What are your thoughts on this?
> Leverage pip's requests to allow for error catching

- pipenv/utils.py
I find a bug on windows.
The program can not get the python version when writing the pipfile.
> fix a bug on windows - can not get the python version

- appveyor.yml
- pipenv/utils.py
- test_windows/test_pipenv.py
This is a fix for the windows tests.  Manual testing confirmed it was working, but the tests were not updated to reflect some changes in the cli api as well as changes in the pipfile spec.  
The tests are still failing for one reason though:  tablib is not letting `shutil` do its work in one of the tests.  Seems like git is hanging on a hash keeping the file open, which then can't get removed by `shutil`
```>                   os.unlink(fullname)
E PermissionError: [WinError 5] Access is denied: 
'test_requirements_to_pip\\.venv\\src\\tablib\\.git\\objects\\pack\\pack-f62460c8a29b488d06169e6eb93733b7a8d3aea7.idx'
c:\python34-x64\lib\shutil.py:375: PermissionError
> Windows tests

- pipenv/cli.py
Updating pipenv might fail occasionally, and the default output is not quite clear.
So I use crayons to beautify the error message and make it more friendly.
> Output friendly and concise message when updating pipenv failed.

- docs/advanced.rst
Changed the raw-file link for get-pipenv.py so that calling curl would lead to
the actual file instead of a 302 Redirect to the file.
> Update crude installation instructions to properly find get-pipenv.py

- pipenv/cli.py
- pipenv/project.py
Fix this cmd `pipenv graph` executed in system path.
```
$ pipenv graph
File "/usr/local/bin/pipenv", line 11, in <module>
sys.exit(cli())
File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, …
```
> Fix NoneType.

- pipenv/utils.py
On Windows, Miniconda's python prints "Python 3.6.2 :: Continuum Analytics, Inc." when running `python --version`
> Support Miniconda's `python --version` format

- pipenv/cli.py
- pipenv/project.py
- pipenv/utils.py
* This now resolves relative paths correctly upon locking (not 100% sure if the hashing behavior is what we want, since the hash of the relative path will never match the hash of the absolute path -- maybe we should always hash teh absolute path even if we store the relative path?)
* For some ungodly reason this now also puts VCS urls and refs in the lockfile however.  I have no clue why.
> Relative file paths fix

- pipenv/vendor/pexpect/popen_spawn.py
I've opened an identical PR for pexpect: https://github.com/pexpect/pexpect/pull/446
> Fix popen_spawn when specifying a path on Windows which contains "\" separators

- pipenv/vendor/pexpect/popen_spawn.py
* Instead of testing for platform, which is not always accurate, it's better to test posix compliance by just checking whether we are posix compliant
> Test for posix compliance by checking posix compliance

- pipenv/cli.py
bold was being used in puts instead of in crayon, breaking the code.
reproduce doing: `pipenv uninstall -d requests`
> fix: bold used in puts instead of crayon

- pipenv/cli.py
Trying to do:
`pipenv uninstall -d nose`
raises a `KeyError` exception.
This fix the issue.
> fix: uninstall dev expecting tuple, not dict

- pipenv/cli.py
- tests/test_pipenv.py
Doing `pipenv uninstall -d <package>` does not remove the file from the
Pipfile. There was a flag preventing from doing so in `cli.uninstall`
Includes test
Closes #575
Note:
`test_cli_usage` is not passing for me because running `pipenv install regex` does not return `code == 0`
> fix: uninstall dev now removes package from Pipfile

- pipenv/environments.py
On my system, pipenv fails to detect the presence of pyenv, so it doesn't offer to download and install missing Python versions.
I think `PYENV_ROOT` will only be set if the user explicitly sets it. It seems better to use `PYENV_SHELL` here. That one is set by `pyenv init`.
Also, I think it's a bit cleaner to use a `bool`  for the `PYENV_INSTALLED` variable.
> Improve pyenv detection

- docs/advanced.rst
A list item containing indented the second (and following) lines become an item of definition list.
For example, following reST code
```reST
- ``--all`` — This parameter will purge all files from the virtual environment,
but leave the Pipfile untouched.
```
converted to
```HTML
<li>
<dl class="first docutils">
<dt><code class="docutils literal"><span class="pre">--all</span></code> — This parameter will purge all files from the virtual environment,</dt>
<dd>but leave the Pipfile untouched.</dd>
</dl>
</li>
```
In the example, the second line should be positioned at the same level of the first line.
In addition, sphinx splits that list item into two msgstr: "``--all`` — This parameter will purge all files from the virtual environment," and "but leave the Pipfile untouched."
This makes …
> Fix reST syntax of lists

- pipenv/project.py
Fixes #546
`touch_pipfile` is already called from `ensure_project` if needed.
> Remove extra touch of the Pipfile during run

- pipenv/cli.py
Hey! I noticed that `pipenv -h` works, but for subcommands it usually results in `Error: no such option: -h`. For `pipenv install -h` specifically, it actually throws an `RequirementParseError: Invalid requirement, parse error at "'-h'"`. 
This PR adds `-h` and `--help` to all commands, following [the click docs](http://click.pocoo.org/5/documentation/#help-parameter-customization).
> Add '-h' and '--help' for all commands

- pipenv/cli.py
Thanks for recommending [`PIPENV_DEFAULT_PYTHON_VERSION`](https://twitter.com/kennethreitz/status/912068103588245507). I was taking a look at the source, to see how it worked and this function looked ripe for simplifying. 
(Not sure if micro contributions like this are always helpful, so feel free to feedback on that :smile: )
Also I see it ignores anything more detailed that x.y.
> simplify code in find_a_system_python

- pipenv/cli.py
Little typo snuck in https://github.com/kennethreitz/pipenv/commit/f08fb1f2713a97540bb5036d312acc5ecd1ddb58#diff-e1e68886e05fef92bb74ed1699e5179eR1534.
Thanks for all the work on this project.
> Fix typo in sequential flag help

- docs/advanced.rst
- docs/basics.rst
This PR resolve problems casing following error messages.
```
WARNING: /Users/tomohiko/MyRepos/Python/pipenv/docs/advanced.rst:66: (WARNING/2) Title underline too short.
☤ Deploying System Dependencies
------------------------------
WARNING: /Users/tomohiko/MyRepos/Python/pipenv/docs/advanced.rst:66: (WARNING/2) Title underline too short.
☤ Deploying System Dependencies
------------------------------
/Users/tomohiko/MyRepos/Python/pipenv/docs/basics.rst:125: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/Users/tomohiko/MyRepos/Python/pipenv/docs/basics.rst:253: WARNING: malformed hyperlink target.
/Users/tomohiko/MyRepos/Python/pipenv/docs/basics.rst:286: WARNING: malformed hyperlink target.
/Users/tomohiko/MyRepos/Python/pipenv/docs/basics.rst:298: WARNING: …
```
> Fix reST syntax errors

- docs/advanced.rst
Also mentions using `PIP_IGNORE_INSTALLED` to still
install everything that's pip-installable into the virtual environment,
even if a suitable version is already installed globally.
Closes #748
> Issue #748: cover the --site-packages option

- pipenv/cli.py
`tm_day` was used in checking easteregg dates.
this is unssupported on python2.7,
use 'tm_mday` insted of `tm_day`
```
File "/home/aodag/src/github.com/aodag/pipenv/venv/bin/pipenv", line 11, in <module>
load_entry_point('pipenv', 'console_scripts', 'pipenv')()
File "/home/aodag/src/github.com/aodag/pipenv/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/home/aodag/src/github.com/aodag/pipenv/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
return ep.load()
File "/home/aodag/src/github.com/aodag/pipenv/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2405, in load
return …
```
> fix using tm_day unsupported on py2

- pipenv/patched/pip/compat/__init__.py
- pipenv/vendor/delegator.py
I use the `pipenv install` command on windows,, but there was a UnicodeDecodeError:
``` plain
PS E:\repos\GitHub\myapp> pipenv install
Creating a virtualenv for this project…
File "D:\Program Files\Python36\Scripts\pipenv-script.py", line 11, in <module>
load_entry_point('pipenv==8.2.6', 'console_scripts', 'pipenv')()
File "d:\program files\python36\lib\site-packages\pipenv\vendor\click\core.py", line 722, in __call__
File "d:\program files\python36\lib\site-packages\pipenv\vendor\click\core.py", line 697, in main
File "d:\program files\python36\lib\site-packages\pipenv\vendor\click\core.py", line 1066, in invoke
File "d:\program …
```
> Fix unicode decode error on windows

- pipenv/patched/pip/_vendor/pkg_resources/__init__.py
This is basically a port of pip's commit eaccb88674beff75bb98a1d1e2d53a26a9c63890, which updates the vendored pkg_resources, and fixes a crash which, apparently, seems to happen when trying to import setuptools/pkg_resources in an environment where a namespace package is installed, but where there is more than one directory in the path of the namespace package (this seems to be the case on all the systems to which I have access).
This crash is reproducible by running any pipenv command, including `pipenv --version` in an empty directory.
See the upstream bug [here](https://github.com/pypa/setuptools/issues/885) for further details.
Fixes #552
> Update pip's pkg_resources from Setuptools 34.2.0.

- pipenv/cli.py
After [this commit](https://github.com/kennethreitz/pipenv/commit/04ce86abe081246a27cd94d3e20db2a6d4000452) the exception KeyError is no longer raised in case the env variable `SHELL` is missing.
This patch fixes the issue without making any changes in the current flow. 
One might want to make this check earlier when `PIPENV_SHELL` is set at [environments.py#L90](https://github.com/kennethreitz/pipenv/blob/master/pipenv/environments.py#L90) and then remove all validations of `PIPENV_SHELL` afterwards.
> Fix when PIPENV_SHELL is empty

- MANIFEST.in
- pipenv/cli.py
- Add missing `mapping` file from vendored `pipreqs` to dist
- Resolve non-stdlib package names using `mapping` file before checking PyPI
- Do not `lower` needed package names after resolving them with `pipreqs`
> Fix check --unused

- pipenv/patched/piptools/resolver.py
Fixes #839
This well ensure the dependencies are well-fetched on the next iteration too.
I think this patched section could be removed, but I can't give a 100% guarantee right away, so I'll submit this fix for now and will leave the "full" resolving of markers later.
> Reset the InstallRequirement.prepared attribute when yeilding dependencies

- pipenv/cli.py
This uses the `max()` builtin to determine the latest pipenv version
instead of sorting the available versions and taking the last version.
This is clearer, idiomatic, and avoids the need for intermediate lists.
> cli: Use max() to determine latest version

- docs/install.rst
- pipenv/pipenv.1
`make man` to cover recent docs changes (including #843 )
I assume removal of the "Automatic Python Installation" section from man that this causes is intentional? (https://github.com/kennethreitz/pipenv/compare/master...therefromhere:rebuild-man?expand=1#diff-b5e9ceb23f5465ad53594720c58e859aL684 )
> Typo fix + rebuild man

- pipenv/cli.py
- pipenv/utils.py
Fix #851.
Enabled adding a package specified with `~=` compatible release specifier.
Disabled "did u mean" suggestion for packages specified with `!=`, `>`, `<`, `~=`
> fix installing with compatible release specifier

- pipenv/cli.py
- tests/test_pipenv.py
Refs #887
The regressions test fails without the second commit. `python_dateutil` is added to the Pipfile.lock even though it's not listed in the Pipfile.
> Don't lock VCS dependencies not listed in the Pipfile

- pipenv/utils.py
- tests/test_pipenv.py
Fix for determining if a package name is a locally installed package.  I ran into this because a project I work on depends on the `ansible` Python package _and_ has a top-level `ansible/` directory which is _not_ a Python package.  
The current logic detects the `ansible/` filesystem directory as a Python package file installation and sets the package name to the hash of the directory path, which is nonsense.  Then, `pip` tries to uninstall something like `deadbeef` and fails, not uninstalling anything after that non-existent "package".
I kept this change simple and stupid as I believe that the file (un)installation support is really just about _files_, and I didn't want to drag `importlib` into this.
re: 
- https://github.com/kennethreitz/pipenv/pull/818
- …
> Fix pip file deps conversion

- docs/install.rst
Hi, I just packaged pipenv in Nixpkgs:
https://github.com/NixOS/nixpkgs/commit/e55b99e840e713f840f4a6989211913707838708
At the moment it's only available in the unstable channel, but (even if you're not on the unstable channel) you can easily try it out (after installing Nix: `curl https://nixos.org/nix/install | sh` if you don't have it already) with:
env NIX_PATH='nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/e55b99e840e713f840f4a6989211913707838708.tar.gz' nix-env -f '<nixpkgs>' --install --attr pipenv
or
env NIX_PATH='nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz' nix-env -f '<nixpkgs>' --install --attr pipenv
(the first tarball link is pinned to the specific commit at which pipenv appeared, the 2nd link instead will track the most recent …
> Document Nix installation option

- Dockerfile
Copies `Pipfile` and `Pipefile.lock`, installs deps on building a docker
image using the official pipenv image.
This is a approach i saw on the official python onbuild images. Maybe this makes things a little more convenient...
> Uses ONBUILD in Dockerfile to install deps while building

- pipenv/cli.py
- pipenv/utils.py
- tests/test_pipenv.py
* Allow PIPENV_IGNORE_VIRTUALENVS to work with pipenv shell
* Fixes #894
> Shells with PIPENV_IGNORE_VIRTUALENVS on win

- pipenv/cli.py
When specifying a python (`--three, --two or --python`) version, `pipenv` deletes the existing virtual env **before** checking if the specified version is installed.
With this change, pipenv can prevent mistyped versions, or even undesirable actions; suppose someone cannot download a new python version due to a limited network etc.
> Ensure python version is installed before deleting existing virtual env

- MANIFEST.in
In #871 it was found that problem is with cacert.pem missing from vendored requests. Although cacert.pem exists in repository it is ignored during build. By digging through commits I found that previously it was included through MANIFEST.in, but was changed in 6ac67d9 commit. Looking at commit message and change it doesn't seem like it was intended. Likely it was broken even before that, because at the moment of that change path pipenv/vendor/requests/cacert.pem didn't exist (I guess there was some restructuring going on before that).
There is a note about cacert.pem in pip/_vendor/README.rst on how you can optionally remove it, which seems strange if cacert.pem should be ignored by build like it is right now.
Still I might be wrong, but it fixes #871 for me.
> Add cacert.pem from requests to releases. Fixes #871

- pipenv/cli.py
help still prints out if you execute pipenv run with no args
Signed-off-by: Erin O'Connell <erinocon5@gmail.com>
> disabled help message for run

- pipenv/cli.py
- tests/test_pipenv.py
> Lock requirements enhancement

- pipenv/project.py
- tests/test_project.py
Add a more explicit error message if a section of the Pipfile is duplicated
> Fix #973 Fails if two conflicting "requires" sections are present.

- pipenv/project.py
- tests/test_project.py
Reverts kennethreitz/pipenv#976
> Revert "Fix #973 Fails if two conflicting "requires" sections are present."

- pipenv/cli.py
The truncated help text for the "Commands:" section (on `pipenv`) threw me off some while first looking at and learning Pipenv.
I made a quick PR to see how it would be with displaying the full help text. 
Eliminating the auto-truncation by the `click` library was achieved by switching from the `help` kwarg to `short_help` in the `click.command` decorator.
> Switched to `short_help` kwarg from `help` for command help text.

- pipenv/cli.py
Fix handling of the proper long index option (--index-url) for pip install.
As far as I can tell, `pip install` uses `-i` and `--index-url` (see [documentation](https://pip.readthedocs.io/en/stable/reference/pip_install/#cmdoption-index-url)), the `pip search` accepts `--index` long option. Those options are added by [pip-tools](https://github.com/jazzband/pip-tools) when using pip-compile.
I'm wondering if the packages should not be associated with that index, following https://docs.pipenv.org/advanced.html#specifying-package-indexes
Change mentioned in #856 
Example `requirements.txt` coming out of `pip-compile`:
```
--index-url https://pypi.example.com/xxx/+simple/
Django==1.9.5
myprivatepkg==1.1.5
```
> fix pip index handling

- pipenv/environments.py
When running `pipenv install`, it doesn't see that I have already installed the Python version through pyenv. I get the following warning:
```
Warning: PYENV_ROOT is not set. New python paths will probably not be exported
properly after installation.
```
If I run `PYENV_ROOT=~/.pyenv pipenv install` then it successfully sees the installed version.
I don't export a `PYENV_ROOT`, as pyenv defaults to using `~/.pyenv` (seen [here](https://github.com/pyenv/pyenv/blob/2f396596d768bf7aa300f7e89e89ae4cc0f748aa/libexec/pyenv#L54)).
This PR tells Pipenv to use this default if there's no `PYENV_ROOT` set, so that it doesn't break when used with the default installation of pyenv.
> Use the default PYENV_ROOT if it is not set

- pipenv/utils.py
This modifies the pip-tools exceptions class to prompt the user the check their version specifier/number if none be resolved.
> Added nice warning message for version specifiers

- README.rst
The fish shell is great, but bash is still a popular shell in use by many people. I thought it would be useful to include instructions to setup auto-completion in bash in the readme.
> Add bash shell completion instructions

- pipenv/cli.py
Without this patch:
`pipenv run myscript -- --foo` is treated as
`pipenv run myscript --foo`
and
`pipenv run myscript --foo --python --debug` is treated as
`pipenv run --python=--debug myscript --foo`
..etc
> Ensure 'run <command>' arguments are not stolen by 'run' arguments

- pipenv/cli.py
- pipenv/project.py
- pipenv/utils.py
- pipenv/vendor/pathlib2.py
- tests/test_pipenv.py
- tests/test_utils.py
* Issues - #949, #939, #936 and to a lesser extent #817 #540 #914 #960 #870 and more
* Fixed: Local file path installation (resolves in pipfile as relative
path)
* Pass file:// URI to Requirements library for resolving
TODO:
* Ignore non-explicit directory paths lacking os.sep or ./
* Fix extras_require (per #870)
* Add tests
> Relative file and path installation

- pipenv/cli.py
- tests/test_pipenv.py
- Add better exception handling and error messaging for parse errors
- Add test to verify this is now being handled correctly
- Fixes #1056
> Stop writing unparseable requirements to Pipfiles

- pipenv/utils.py
This is required to have pip/pip-tools get the right wheels according to
the project virtualenv python version.
Should completely fix #857, and the likes.
/cc @kennethreitz @erinxocon @nateprewitt @techalchemy
> In HackedPythonVersion, patch sys.version_info

- pipenv/utils.py
This is needed to get pipenv to work on Python 2 hosts (current version on PyPI is broken). Adds the base class of `FileNotFoundError` and adds the default argument of `None` to the `utime` call.
> Fix #1085 for Python 2

- pipenv/cli.py
See #1054 for details.
Basically, using `pipenv lock -r > requirements.txt` in a project that didn't already have a virtualenv would output `Using /path/to/python to create virtualenv...` in stdout. This would cause the `requirements.txt` file to contain the said line.
Example without fix:
```
$ cat requirements.txt
Using /usr/local/bin/python3.6m to create virtualenv…
pandocfilters==1.4.2
snowballstemmer==1.2.1
ipython-genutils==0.2.0
pygments==2.2.0
pytest-asyncio==0.8.0
prompt-toolkit==1.0.15
```
Example with this diff:
```
$ cat requirements.txt
pandocfilters==1.4.2
snowballstemmer==1.2.1
ipython-genutils==0.2.0
pygments==2.2.0
pytest-asyncio==0.8.0
prompt-toolkit==1.0.15
```
(Both examples have been shortened for brevity)
> Fix #1054, 'Using <python> to create virtualenv' now outputs to stderr

- pipenv/utils.py
- tests/test_pipenv.py
- Split out markers and local paths
- Fixes #870 and #1083 and #858 and #848 
- Also splits markers properly using pip's approach
- The requirements parser we use really needs a lot of help
> Properly split and parse requirements lines

- pipenv/patched/README.md
- pipenv/patched/piptools/locations.py
This will avoid having `pipenv` and the "real" `pip-tools` stepping on each other.
I encountered some issues while working on both projects due to that overlap, so lets fix this.
> Use the pipenv cache path in the patched pip-tools

- docs/_templates/sidebarintro.html
The sidebar in the documentation includes a button to follow Kenneth on GitHub, which was linked to over HTTP and as such triggered an active mixed content warning. Since the button is available over HTTPS, it should be linked to using HTTPS.
> Fix active mixed content warning in docs

- pipenv/utils.py
- tests/test_pipenv.py
- Fixes #1126
- Does a simple check before stripping the VCS prefix on
a `requirement.uri` in `pipenv.utils.convert_deps_from_pip`
> Only strip VCS prefix for URIs with vcs+ patterns

- pipenv/patched/pip/req/req_set.py
- tests/test_pipenv.py
Trying to address #875, #993, #1060
What this PR still needs:
Details can be found on this comment: https://github.com/kennethreitz/pipenv/issues/875#issuecomment-337717817
> Dependency resolution - Do not pin candidates on first selection

- pipenv/cli.py
- pipenv/utils.py
- tests/test_utils.py
- Fixes #1111 
- Uses existing infrastructure to add editable dependencies to the list
of sequentially installed packages
- Only alters functions used for this purpose
- Essentially there is a race condition because multiple editors are
trying to write to lib/site-packages/easy-install.pth for local editable
packages, so they overwrite one another
> Do sequential installs on editable dependencies

- README.rst
Replace dead link to "python packaging" documentation in the first line of the documentation.
> Update README.rst for a dead URL

- pipenv/utils.py
- tests/test_pipenv.py
- For some reason pipenv treats pipfile entries with leading specifiers as paths on windows
- Might want to add a fix for 9.0.1
[![Build status](https://ci.appveyor.com/api/projects/status/a383f9obssqlucox/branch/bugfix/windows-specifier-check?svg=true)](https://ci.appveyor.com/project/techalchemy/pipenv/branch/bugfix/windows-specifier-check)
> WIP: Stop Treating Specifiers as Paths on Windows

- pipenv/cli.py
- pipenv/project.py
#624 was partially reverted in ecbb386 without a solution to the closed issue. Ideally, we would have `project.project_directory` return the current directory if a `Pipfile` doesn't exist. I don't know what the implications of that will be though, and we're likely to introduce follow on issues mucking with it right now.
This should get us out the door for 9.0.1 without losing what #624 was trying to accomplish. I'd like a second pair of eyes to green light this before we merge.
> use current directory if project directory doesn't exist

- pipenv/utils.py
- tests/test_pipenv.py
- Backup resolver was broken when hash resolution was split out into two
functions
- This PR returns the resolver to the caller function
- This is for edge cases where the PyPI json API and the pip resolver
don't return the same authoritative result for a package lookup (a name
can be resolved in one source but not the other)
- Added test to prevent future regression
- Fixes #1195 
/cc @nateprewitt for 9.0.1
> Fix backup resolver

- pipenv/cli.py
When updating all with the `--clear` flag, it isn't passed to the `do_lock` call, so the cache isn't actually cleared.
This PR fix this behavior.
> Pass clear flag to lock when updating

- pipenv/cli.py
- pipenv/utils.py
- tests/test_pipenv.py
- Test now checks for dev dependency "pytest==3.1.1" rather than the
characters of the string
- Test verifies that dev dependencies are excluded by default
- Corrected intent of returned variables from merge_deps call in cli.py
> Improve test & code clarity around requirements generation

- pipenv/cli.py
Wrap the `src` path in quotes for safer handling of paths that include special characters (discovered when using a path that contained parens).
> Fix: quote src for safer handling

- pipenv/project.py
- pipenv/utils.py
- tests/test_utils.py
This fixes #1218.
Windows generally use upper cased drive names, but allow (without normalizing) lower cased names in cmd.exe, which results in inconsistencies when hashing the full path (to get the name of the project's virtualenv). Python does not provide a good solution[*], so we need to roll our own.
[*]: Python does have os.path.normcase(), but it always converts the whole paths to lowercase. This would break virtually *all* existing virtualenvs for Windows users.
UNC host names (which Python also treats as drives), on the other hand, can actually be either cased. I am not sure if they are case-sensitive, or should be coerced to what case, so this patch keeps with the existing behaviour, and does not try to coerce them.
> Force Windows local drive names to uppercase

- docs/index.rst
Outside of the TOC blocks it was referring to install.html instead of /install/ and resulted in broken links.
> Fixed broken links to fancy install methods

- pipenv/utils.py
Fixing a bug when using a combination of user / password in index url and `verify_ssl = false` in Pipfile
Example Pipfile to reproduce : 
```
[[source]]
name = "pypi"
[[source]]
name = "private"
url = "https://user:password@myrepo/simple"
verify_ssl = false
[dev-packages]
[packages]
mypackage = "*"
[requires]
python_version = "3.5"
```
Using `pipenv lock --verbose` with this give us the following output
```
Using pip: -i https://pypi.python.org/simple --extra-index-url https://user:password@myrepo/simple --trusted-host user
```
> replace netloc by hostname when adding trusted-host arg to pip

- pipenv/cli.py
When i uninstall the package in verbose mode, pipenv throws the following error:
```bash
❯ pipenv uninstall --verbose elasticsearch-dsl
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project.
Un-installing elasticsearch-dsl…
$ {0}
File "/Users/dongweiming/avalon/venv/bin/pipenv", line 11, in <module>
load_entry_point('pipenv', 'console_scripts', 'pipenv')()
File "/Users/dongweiming/pipenv/pipenv/vendor/click/core.py", line 722, in __call__
File "/Users/dongweiming/pipenv/pipenv/vendor/click/core.py", line 697, in main
File "/Users/dongweiming/pipenv/pipenv/vendor/click/core.py", line 1066, …
```
> Fix uninstall package error in verbose mode

- docs/advanced.rst
For those wanting to use/migrate to pipenv, the question of how to use Tox comes up.
Worked on a plugin for Tox that will just use pipenv instead of virtualenv and pip. 
This is an update to the docs to redirect people there. Since this is not related or supported by PyPa, it's referenced as 3rd party.
> Add a reference to a 3rd party plugin for tox

- pipenv/cli.py
If the output of ``pip freeze`` contains comments (e. g. a line like ``## !! Could not determine repository location``), then the ``pipenv update`` command fails when it tries to parse the requirements:
````
(project-cIS5-zzV) bash-3.2$ pipenv update -d
Updating all dependencies from Pipfile…
File "/.local/bin/pipenv", line 11, in <module>
sys.exit(cli())
File "/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
File "/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
File "/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
return …
```
> pipenv update fails if freeze output contains comments

- pipenv/utils.py
- tests/test_pipenv.py
This fixes #1240.
The shellquote call was added for every platform in https://github.com/pypa/pipenv/commit/908b41df75f6306a427a198d506b3b5f9ebef676, but this won't work on, at least, Linux. I've taken an educated guess at this being required on Windows as the subprocess module has [documentation explaining how Windows argument sequences are treated differently](https://docs.python.org/2/library/subprocess.html#converting-argument-sequence).
I don't have access to a Windows environment, so I can't confirm whether or not my supposition is correct.
> Don't shellquote backup Python executable

- pipenv/utils.py
- tests/test_pipenv.py
- Fixes #1225
- Add checks for Wheel files and archive files specifically
- Adopts egg-fragment parsing for local file paths to allow naming of
filesystem paths as well
- Adds these checks both to the `get_requirement()` function and the
`is_installable_file()` function
> More thorough checks before resolving files

- pipenv/cli.py
- pipenv/utils.py
- tests/test_legacy.py
- tests/test_pipenv.py
At the moment, pipenv will create a temporary file per non-leaf package during dependency resolution, and one per resolved package during installation.
This PR adds cleanup to those two cases, and a test to ensure that no temporary artifacts remain after installation.
> Clean up temporary files created during installation

- pipenv/utils.py
- tests/test_pipenv.py
- New bug introduced by #1221 throws an error when running `pipenv install` on windows in a directory with no pipfile
- This also updates the relevant tests to normalize paths for assertions to pass on appveyor
- I just set up my own appveyor with a webhook so test failures caught this
`Project.pipfile_location` is calling `utils.normalize_drive(loc)` even when `loc = None`, which throws the following error:
```python
File "C:\projects\pipenv-jqd6x\pipenv\cli.py", line 1766, in install
ensure_project(three=three, python=python, system=system, warn=True, deploy=deploy)
File "C:\projects\pipenv-jqd6x\pipenv\cli.py", line 607, in ensure_project
if not project.pipfile_exists:
File "C:\projects\pipenv-jqd6x\pipenv\project.py", line 99, in pipfile_exists
return bool(self.pipfile_location)
File …
```
> Fix ensure_project bug on windows when missing pipfile

- pipenv/utils.py
- tests/test_utils.py
- Fixes #1121
- Adds a bunch of tests for `pipenv.utils.get_requirement()`
> Properly parse urls as Link objects

- pipenv/cli.py
In some systems `Requirements.txt` != `requirements.txt` and this line could possibly bring confusion to users.
Since we are only searching for actual `requirements.txt` in `find_requirements()`: https://github.com/pypa/pipenv/blob/cbcc89bee73e5af2e34252deb686ad7578e14c61/pipenv/utils.py#L1121
> Updates cli.py with proper requirements filename

- pipenv/cli.py
Current code tries to run .format on the return code of click.echo which is always None.
> Fix AttributeError on pipenv uninstall --verbose

- pipenv/project.py
- pipenv/utils.py
- tests/test_pipenv.py
- tests/test_utils.py
*Note*: This fix ensures duplicate virtualenvs are not created/overwritten on windows due to drive letter capitalization.
Windows will allow upper and lowercase drive letters and will return whatever the user specified when swapping drives, so if the user previously used capitalized lettering to create a virtualenv with pipenv, but now uses lowercased drive lettering, pipenv will create a new environment.  This resolves that issue.
- Added string check for `normalize_path` function
- Updated tests to use `normalize_path` on both sides of assertions
Force Windows local drive names to uppercase
Windows generally use upper cased drive names, but allow (without normalizing) lower cased names in cmd.exe, which results in inconsistencies when hashing the full path (to get the name of the …
> Windows Drive Case Normalization

- pipenv/cli.py
- pipenv/patched/crayons.py
- pipenv/utils.py
This PR intends to consolidate the post-9.0.1 minor PRs which were merged for easy review.  Included in this PR these items:
- #1298 - Missing comma in `__all__` tuple in patched crayons
- #1287 - replace netloc by hostname when adding trusted-host arg to pip
- #1268 - Update fails if freeze has comments
- #1242 - dont use requirements.txt when filename provided
- ~~#1282 - Fix uninstall error in verbose mode~~ in master via #1361
> Post 9.0.1 minor merges

- docs/basics.rst
This is useful for people using Pipenv and looking for more information related to specifying VCS dependencies.
> Add link to Pipfile specification

- Dockerfile
This makes it clearer that you don't have to do `pipenv run python3 main.py` for instance.
> Add CMD to example Dockerfile usage

- pipenv/core.py
Fix the `core.do_create_virtualenv` cmd generation when both `PIPENV_VENV_IN_PROJECT` and `site_packages` are enabled.
> Fix `do_create_virtualenv` cmd generation.

- pipenv/core.py
`.` is actually a `source` alias. But it works better, since `source` is not supported in raw `sh`.
As it was discussed in https://github.com/pypa/pipenv/issues/1371 some systems do not have `bash` installed.
Prove link: https://askubuntu.com/questions/25488/what-is-the-difference-between-source-and
> Updates `activate_virtualenv`, closes #1371

- pipenv/core.py
Re-work former PR https://github.com/pypa/pipenv/pull/1204 to get the fix back into the new `master` branch using the `shellquote` helper, as mentioned in https://github.com/pypa/pipenv/pull/1361#issuecomment-360797751.
> Fix: shellquote src path

- pipenv/utils.py
- tests/test_pipenv.py
- tests/test_utils.py
- Fixes #1329 
Reintroduces the following:
- #1241 (don't shellquote backup executable)
- #1235 (Properly parse URLs as link objects when generating requirements)
- #1236 (More thorough checks before resolving files)
> Requirements generation and resolver related post-9.0.1 PRs

- HISTORY.txt
- pipenv/cli.py
- pipenv/core.py
Closes #1434. 
Changes:
1. `-v` now always allowed as shorthand for `--verbose`
2. added callback that sets pip.logger's log level to INFO if `--verbose` specified.
Open questions:
1. Does using callback with `--verbose` look like a reasonable way to do this? I like that it is simple and combines log setting/verbosity into one place (but I don't know if it's "click-ish")
2. Level of log output look okay? ([success example](https://gist.github.com/jtratner/606469d9f896fce1f6c8f9aa439b18ab) +  see example from "bad" install at end).  Perhaps only pip.utils should get this log level applied with verbose? (other stuff is so noisy it's a bit of a bummer)
3. Should I attempt to colorize output with log handler? 
Failing build dumps pip log info - yay!
```
Pipfile.lock not found, creating… …
```
> Show pip info level logging with verbose

- pipenv/pipenv.1
- tests/test_pipenv.py
Found via `codespell -q 3 --skip="./patched"`
> MIsc. comment and doc typos

- pipenv/core.py
Fixes https://github.com/pypa/pipenv/issues/1455
I went with the approach of bypassing the build a dependency tree when a virtualenv does not exist for optimization purposes. The other approach would have been to build a dependency tree and conditionally switch to valid empty JSON after evaluating the empty output.
> fix graph command for missing virtualenv

- README.rst
- docs/index.rst
- pipenv/core.py
Explicitly point out in first page of docs that you can use `pipenv run pip ...` to invoke pip utility commands.
I previously made #1461, which was sensibly rejected on the grounds that it wasn't actually needed. Somebody pointed out in #1462 that I'm not the first person to make this mistake. The proposed change is perhaps not the strongest possible guarantee that nobody will make the mistake again, but also could help. Maybe. It's at any rate extremely unlikely to hurt.
> document pip commands from pipenv

- pipenv/core.py
Fish 3 removes the `.` command in favour of `source`, so we need to adapt.
See https://github.com/pypa/pipenv/pull/1388#issuecomment-367353694
> Update activate_virtualenv again for Fish 3.0+

- pipenv/core.py
Attempting to clean a project without a lockfile results in:
```
> pipenv clean
File "/usr/local/bin/pipenv", line 11, in <module>
load_entry_point('pipenv', 'console_scripts', 'pipenv')()
File "/Users/dschaller/Documents/pipenv/pipenv/vendor/click/core.py", line 722, in __call__
File "/Users/dschaller/Documents/pipenv/pipenv/vendor/click/core.py", line 697, in main
File "/Users/dschaller/Documents/pipenv/pipenv/vendor/click/core.py", line 1066, in invoke
File "/Users/dschaller/Documents/pipenv/pipenv/vendor/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File …
```
> show warning if lockfile doesn't exist on clean

- pipenv/core.py
- pipenv/utils.py
- pipenv/vendor/backports/weakref/__init__.py
- pipenv/vendor/backports/weakref/weakref.py
- tests/test_pipenv.py
This is a small piece of what might need to be a bigger cleanup of some of our backend processes.  This aims to provide the capacity to cleanly handle temporary filesystem resources, and also aims to use more carefully those resources which we do generate.
Broad fixes to testing infrastructure
- Add custom rmtree function to handle windows rms
- Only warn on failure to remove a tree
- This should mitigate a large portion of our windows test failures
- After sufficiently substantial time investment I am currently of the opinion that there is no real elegant way to handle this (I have tried programmatically finding all processes with open file handles, terminating them with a 500ms retry and a 15s timeout)
- Close and handle tempfiles in resolvers
- Only create tempfiles for non-editable …
> Temporary File Cleanup

- pipenv/core.py
Currently, running `pipenv lock --keep-outdated` with a `Pipfile` with `Requests = "*"` blows up because the name is normalised in the lockfile.
Also fixes a typo.
> Convert dependency name to PEP 423 name when looking for it in lockfile

- HISTORY.txt
- pipenv/environments.py
- tests/test_pipenv.py
Frequently I run into the situation where pipenv's virtual environment was created with `PIPENV_VENV_IN_PROJECT=1` (via `Makefile` or other setup script), but when I go to run a one-off command some time later, pipenv creates a new virtual environment missing my dependencies:
```
$ PIPENV_VENV_IN_PROJECT=1 pipenv install pytest
Creating a virtualenv for this project…
⠋New python executable in /private/tmp/test/.venv/bin/python
Installing setuptools, pip, wheel...done.
Virtualenv location: /private/tmp/test/.venv
Installing pytest…
Collecting pytest
Using cached pytest-3.4.1-py2.py3-none-any.whl
Collecting pluggy<0.7,>=0.5 (from pytest)
Collecting six>=1.10.0 (from pytest)
Using cached six-1.11.0-py2.py3-none-any.whl
Collecting py>=1.5.0 (from pytest)
Using cached …
```
> Assume PIPENV_VENV_IN_PROJECT when a local virtual environment exists

- pipenv/core.py
In `csh`, the `.` operator executes a directory, which is the wrong behaviour here. At best, when `pipenv` is installed system-wide (preferably via the operating system package manager), the result is a permission denied error from the shell.
As `csh` uses the `source` command, reflect that here.
> Correct csh syntax in activate_virtualenv

- docs/basics.rst
I'm new to python so I didn't know 'exit' was the thing to type to deactivate the pipenv shell, so I thought I would add that to the basic usage doc.
> Updated docs - basic usage example pipenv workflow

- HISTORY.txt
- pipenv/utils.py
Even for custom package indexes!
I tested this against Counsyl's internal devpi instance and it worked perfectly :) 
That said, I worry this would cause more issues than it would fix (because it will *always* generate hashes even if the index does not present them), but it'd be really *nice* to do it :) .  Perhaps we could put this behind an environment variable and let folks opt-in to it and kick the tires.
Would fix issue in #1503.
Pipfile like this:
```
›› cat Pipfile
[[source]]
url = "https://internal-devpi/my/index/+simple"
name = "counsyl-pypi"
[packages]
internal-package = "*"
```
installs with hashes
```
Installing 'internal-package --hash=sha256:somehash'
$ "/Users/jtratner/.virtualenvs/example-LTUvl4NZ/bin/pip" install   --verbose  --no-deps  -r …
```
> Always try to generate a hash for packages in Pipfile.lock

- pipenv/core.py
When the dependency list got sorted in 6261122d (current line 828) you'd start getting `TypeError` when the code on line 823 executed because it changed the dependency tuple to a dependency list.
> Fix dependency list type mismatch

- pipenv/patched/prettytoml/elements/table.py
- pipenv/patched/prettytoml/elements/traversal/__init__.py
Two bugs involved here.
First of all, `__delitem__` uses `_find_following_newline` to find where the line to delete ends, which in turns looks for the next closest newline element. But if the previous line ends with a comment element (which implies a newline), it will also be deleted. This would be a problem if the comment is inline.
```
foo=1  # comment
bar=2
```
In this minimal example, the elements in play are
```python
AtomicElement('foo')
PunctuationElement('=')
AtomicElement(1)
WhitespaceElement('  ')
CommentElement('# comment')
AtomicElement('bar')
PunctuationElement('=')
AtomicElement(2)
```
When deleting `foo`, it starts from `AtomicElement('foo')` and looks for the next newline, but does not consider `CommentElement`, ending up deleting all elements. This fix replaces …
> Fix __delitem__ in prettytoml’s table element

- pipenv/core.py
also fixes a typo :)
I was surprised to see the return code give '1' if anything was uninstalled. I'm fairly sure that, unless there is an error in actually performing the act of cleaning the env, pipenv should exit with '0'.
> fix returncode for clean

- pipenv/core.py
`list.copy()` is equivalent to `list[:]`, but the former is only available in Python 3.
> Fix --selective-upgrade compatibility with Python 2

- docs/advanced.rst
bash and zsh require different syntax for enabling shell completion than
fish. That difference was accounted for in README, but not in docs (and,
consequently, on website).
> Add instruction how to enable bash/zsh completion to website

- pipenv/core.py
- pipenv/utils.py
In investigating #1552 I thought I'd try and put in a proper fix - this way the verbose output is printed whether there is an error or not, and I also traced back the `verbose` flag being dropped up the call stack.
> Fix verbose display

- pipenv/core.py
- pipenv/utils.py
> Fix git+ssh url parsing for requirements

- pipenv/resolver.py
- pipenv/utils.py
This at least dumps all of stdout and stderr from pip installs when verbose (which is great for debugging why some setup.py is bad and hopefully helping folks help themselves :) )
I think a better long-term option would be to try and find the start of the "complete output" section and dump that, but this is significantly easier / less error-prone.
The underlying issue is that if the resolver generates a really huge traceback, then printing the second half of the lines doesn't help.
Will help things like #1567.
Before this PR:
```
›› pipenv install --verbose
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Using pip: -i https://...company-pypi...
ROUND 1
Current constraints:
Finding the best candidates:
Finding secondary dependencies: …
```
> Really show all of stderr when verbose

- pipenv/core.py
Fixes issue #1596. `get_requirement` function was receiving an unexpected keyword argument.
> Remove unexpected keyword argument 'verbose'

- pipenv/cli.py
More details in issue #1247, but basically:
- `pipenv.core` takes about 400ms to import
- why do that before checking if `--completion` was passed?
This takes `pipenv --completion` from taking 1.1 seconds down to only 0.6 seconds on my machine (I think it can still go faster, hopefully I'll have time to explore that more in a couple of weeks, but this seemed like an easy win).
> Move handling of --completion earlier to make it way faster

- pipenv/cli.py
Currently Pipenv reinvokes itself with the _PIPENV_COMPLETE environment variable set in order to make click_completion print out the completion function; this is slow (I measured around 480ms) and it would be nice if `pipenv --completion` was as fast as possible.
To that end, this PR switches to using the `click_completion.get_code` function to ask click_completion for the completion function directly.
- we now have to pass `prog_name`, as we're no longer going through Click's completion code (Click has a little thing to [guess the program name](https://github.com/pallets/click/blob/55682f6f5348f5220a557f89c3a796321a52aebf/click/core.py#L694) based on sys.argv)
- this changes the output *slightly*, but it's only removing a newline from the end, which shouldn't matter (there is still a …
> Avoid running another process to print completion script

- docs/advanced.rst
And since VS Code's integration is live, if there's any desire to update the instructions to point to VS Code instead of Sublime whose support is still in-development, let me know and I can send a PR for that.
> Bump VS Code support to no longer be listed as in-progress

- pipenv/core.py
- pipenv/patched/pew/_win_utils.py
- pipenv/patched/pew/pew.py
- Windows only (pew implementation bug)
- Traverse process tree until we find a known shell
like cmd or powershell currently
- Fixes #1601
> Don't assume grandparent process is the shell

- docs/advanced.rst
Now that VS Code has pipenv support out of the box, might at well use an example that doesn't require any extra setup 😉
> Use VS Code as the example editor for EDITOR usage

- pipenv/core.py
I’m not sure what should be done when there’s no Python no warn about. This just skips the warning when there’s none.
Also regarding #1620 I also added detection to `py` in addition to `python`. This should be useful for Windows users (who generally use `py` whenever Un\*x users use `python`).
> Avoid type error when there’s no Python in PATH

- pipenv/core.py
Hopefully a viable alternative to #1620. In addition to looking for executables in PATH, also asks py.exe (if there is one) for its opinion when choosing an executable. Windows users would be able to use `--two`, `--three`, and `--python=<VERSION>`; this will be passed on to py.exe and ask if it can find any matching executable.
Non-Windows users will not be affected because there wouldn't be a `py.exe` to start with.
> Ask py.exe for its opinion when choosing a Python

- pipenv/project.py
- Fixes #1648 (again)
- Uses `sys.executable -m pipenv.pew` invocation instead of script invocation
> Fix virtualenv location reporting

- pipenv/core.py
- If no packages are installed, `results` contains a single empty string. This causes problems in the subsequent call to `convert_deps_from_pip`. Therefore filter out empty strings from `results` to avoid this.
- Fixes #1699
> Fix `do_outdated()` when `pip freeze` is blank

- pipenv/patched/notpip/index.py
- pipenv/utils.py
- Fixes #1539
- Currently writes the wrong index name to the lockfile
- Currently fails one round before succeeding
> Use --extra-index-url for resolution

- pipenv/patched/pew/pew.py
Fix #1682. The problem is that pew resolves `workon_home` on *import time*, but we need to patch the lookup logic. This is fine when we run it with pexpect, but not when invoked programmatically. The environment variable `WORKON_HOME` is changed too late for pew to pick up.
The quick fix is to simply delay importing pew, but it is too unreliable and easy to break again in the future. In the end I decided to just change all `workon_home` occurrences to function calls, so the value is resolved lazily, and can be patched whenever we want to.
> Make pew resolve workon home lazily

- pipenv/patched/pew/_win_utils.py
- pipenv/patched/pew/pew.py
So for some reason Microsoft thinks it’s a good idea to call a thing PowerShell but uses a different executable name. Let’s add `pwsh` wherever there is a `powershell`.
I only fix the `pipenv shell` usage. Completion likely won’t work (because I didn’t do anything about it) but ¯\\\_(ツ)\_/¯
> Support Powershell Core (pwsh.exe) on Windows

- pipenv/utils.py
- Fixes error writing index names to lockfiles
- Uses only specified index if one is specified in pipfile
Test pipfile:
```toml
[[source]]
name = "pypi"
[[source]]
url = "https://testpypi.python.org/pypi"
name = "testpypi"
[packages]
pipenv-test-private-package = {version = "*", index = "testpypi"}
```
> Fix index naming in lockfiles

- docs/advanced.rst
Jannis Gebauer of pyup.io let us know that he's definitely fine
with commercial *use* of the `pipenv check` feature, so it's
only commercial redistributors of `pipenv` that may need to
take a closer look at the licensing situation, and perhaps
talk to `pyup.io` directly.
Follow-up on #1651
> Revise `pipenv check` caveat for pyup.io feedback

- tests/test_pipenv.py
Not sure if this is a good idea. The tests keep overriding my `.env` during development, so here’s a fixture to backup/restore it after being overwritten during tests.
> Restore .env after testing

- docs/advanced.rst
- docs/index.rst
I've prepared a small section on how Pipfile/pipenv differs from the available mechanisms in setup.py (`install_requires` etc). This is something I've struggled with repeatedly in the past and in essence this is what has crystallized to me from what I've read and experienced over the last few years of handling python projects. I'm not totally confident this is actually the Right Way™ to do things. If people disagree I'd be happy about some feedback.
> Add section on distinction between setup.py and Pipfile

- tests/test_pipenv.py
Turns out #1666 and #1729 actually have the same root cause, and fixing one resolves the other. Changes made in #1729 are reverted because they are not needed anymore.
Also added some extra tests that helped me locate this problem.
> Fix venv creation during tests

- docs/advanced.rst
We removed the embedded copy of Safety-DB, so there's
no longer any copyright concern about the CC-BY-NC-SA
license, but it does mean `pipenv check` may end up throttled
eventually as all requests to the backend API use a common
key.
> Update `pipenv check` docs for Safety-DB removal

- pipenv/core.py
- tests/test_pipenv.py
Obv could also *not* create the empty virtualenv when running pipenv
clean, but in general can imagine this also occurring if you created an
empty virtualenv and then tried to do clean within it.
(installed packages was [''])
Fixes #1750.
Wanted to make most minimal change possible, but I could see also adding an `if virtualenv_does_not_exist: return` too
> Fix error on pipenv clean with empty virtualenv

- pipenv/help.py
* The `<details>` tag did not always close itself
* GitHub seems to require an additional line break after HTML to respect Markdown formatting again
Both were encountered when I was creating an issue
> pipenv.help output command formatting fixes

- pipenv/utils.py
Before this commit Pipfile had a more
than neeeded newlines between sections.
Currently generated Pipfile is
```
[[source]]
name = "pypi"
[packages]
[dev-packages]
[requires]
python_version = "3.6"
```
while after this commit it would become
```
[[source]]
name = "pypi"
[packages]
[dev-packages]
[requires]
python_version = "3.6"
```
> better cleanup_toml

- pipenv/__init__.py
- pipenv/resolver.py
Add the parent site-packages directory to sys.path *after* built-in ones, and only when it does not already exist.
This should vastly improve the resolver's robustness against hostile Python environments, such as #1753. It might help with issues like #693 as well, but I'm not sure (and not interested in figuring out either).
> Improve resolver path-patching

- docs/advanced.rst
I believe `passenv=HOME` is no (or no longer?) necessary, as pipenv will
use the virtualenv it is running in. I am assuming that this was to allow `pew` to find a place to put the virtualenv. Or are there other reasons I am unaware of?
In addition this PR adds a recommendation to add `--ignore-pipfile` to `pipenv install`, to protect
the locked dependency set from accidental changes.
> Remove recommendation to add `passenv=HOME` in tox.ini

- Pipfile
I think white only is available for Python 3+ (with no versions for python 2). This was causing test runner to fail for me locally.
> Make white only for python 3 dev-packages

- pipenv/utils.py
- tests/test_utils.py
When the I use a custom source in the Pipfile that is protected by a user & password. 
The [logic in prepare_pip_source_args](https://github.com/pypa/pipenv/blob/2282e7045f08c0794973d296b11ea174e7fda48a/pipenv/utils.py#L268) tries to manually parse ParseResult.netloc (returned from urlparse) this results in the username being passed as the `--trusted-host` when `verify_ssl` is set to false in the Pipfile.
For example, if one of the sources in the Pipfile is `https://user:password@custom.example.com/simple`  
it will result calling `resolver.py` with the wrong params (passed via the PIPENV_PACKAGES environment variable) and called from venv_resolve_deps
the value of the ` --trusted-host` will be the username instead of the host name.
https://github.com/pypa/pipenv/issues/1773
> fix prepare_pip_source_args not properly handle user & pw in repo URLs

- docs/diagnose.rst
- docs/index.rst
This is far from comprehensive, but can be expanded when needed. GitHub is terrible to search, and this can save some time when people ask questions that are already answered in the issue tracker.
> Add a page to answer common questions

- docs/advanced.rst
- pipenv/vendor/pipfile/api.py
- tests/test_vendor.py
Relying on `os.path.expandvars()` to inject environment variables in strings. Works on Windows, back-supports Python 2.7.
See https://github.com/pypa/pipenv/issues/1688
I'm not 100% sure that this is the correct place to do this injection.
Some thoughts:
- The Pipfile hash should be determined after values have attempted to be inserted.
- Pipfile shouldn't be intelligent by trying to differentiate env vars from regular characters—if an env var can't be inserted, the string should remain intact.
- As it stands, Pipenv's vendor folder contains some version of this repository. I don't fully understand the reasons behind this, maybe we could pin it as a requirement instead? We could then separate tests.
Mirrored Pipfile PR: https://github.com/pypa/pipfile/pull/105
> Allow values in Pipfile to consume Environment Variables

- pipenv/core.py
- pipenv/project.py
On a (390+ line) Pipfile, it takes ~5s to parse the entire thing :O.  Pipenv has to parse the pipfile repeatedly and all over the place, so caching the contents speeds things up dramatically when trying to do `pipenv lock` (at least in this case).
This PR makes a little cache based upon file location + md5sum of contents for the pipfile (and the hashing is pretty fast here), which takes ~0.09ms on a cache hit. Given that the cache key is based on the file contents, should be completely fine to do (only possible issue is if parsed_pipfile gets mutated).  I tried returning a copy of the object, but `contoml` throws super weird exceptions if you do that, so I added a helper to clear the pipfile cache in places where it *might* be mutated (even tho I think it's likely overly defensive).
> Cache parsed pipfile

- pipenv/vendor/pipfile/api.py
Current master tests are failing because of small bug in environment variable expansion.
I.e., this fails:
```
$ pipenv install 'requests[socks]'
File "/Users/jtratner/pipenv/pipenv/vendor/pipfile/api.py", line 103, in parse
parsed_toml = self.inject_environment_variables(toml.loads(content))
File "/Users/jtratner/pipenv/pipenv/vendor/pipfile/api.py", line 79, in inject_environment_variables
d[k] = self.inject_environment_variables(v)
File "/Users/jtratner/pipenv/pipenv/vendor/pipfile/api.py", line 79, in inject_environment_variables
d[k] = self.inject_environment_variables(v)
File "/Users/jtratner/pipenv/pipenv/vendor/pipfile/api.py", line 81, in inject_environment_variables
d[k] = [self.inject_environment_variables(e) for e in v]
File …
```
> Fix environment variable expansion with extras

- pipenv/patched/piptools/resolver.py
- Fix Overlapping naming checking for inner markers
- Perform a first-pass right-side split of markers and remove other
exact matching markers from the dependency string
- Fixes #1617, #1791, #1805, #1622
> Simplify marker checks in patched resolver

- README.rst
I've removed the --update option from the documentation, as it was recently removed from pipenv.
> remove --update option from the documentation

- pipenv/utils.py
I think the check for we-should-check-warehouse API needs to be updated to also consider pypi.org.
> Still check warehouse API for new pypi.org

- pipenv/core.py
- pipenv/project.py
- Check for editable pipfile entries when running `pipenv install`
- Check only when lockfile or virtualenv doesnt exist but pipfile does
- If so, first install the editable dependencies, then do resolution
- Required to accommodate `ireq.get_dist()` which we use for setup.py
parsing
- Fixes #1782
> Resolve editable packages on the local filesystem

- pipenv/core.py
- pipenv/project.py
- pipenv/utils.py
- tests/test_pipenv.py
Introduced in #1812. The values aren’t always dict, but can be strings… Also fix the `editable_dev_packages` call that is probably also wrong.
> Fix detection of editable packages

- .travis.yml
- tests/test_pipenv.py
This confirms #1757 is fixed. There is one potential discussion here, however.
Currently if your dependencies specify conflicting environment markers, Pipenv will only choose one of them, as demonstrated in the `test_specific_package_environment_markers` test case. I would instead argue Pipenv should try to aggregate the conditions, i.e. with two markers `sys_plarform=='win32'` and `os_name=='splashwear'`, the lockfile should contain something like
```
"markers": "sys_plarform=='win32' or os_name=='splashwear'"
```
> Add tests for environment marker precedence logic

- pipenv/core.py
- pipenv/utils.py
The intent has been for hashes to be in a stable order to minimize diff
noise. Commit 1fa3e2a567da779b0c081ac28893aca3353c0674 caused a
regression here by converting to a set and back.
Fixes #1529
Fixes #1664
> Pipfile.lock hashes back to determinitic order

- docs/advanced.rst
- pipenv/core.py
- pipenv/project.py
- tests/test_pipenv.py
Fixes #1833.  @frostming - kinda was already there by the time I saw your note - heh.
First commit just fixes both locations where environment variables were injected before hash calculation.
Second commit DRYs up the pipfile hash checking a bit and adds a test case.  I know the API is a little goofy (returning a tuple only when truthy), but it felt like an easier to read way to do the API.
Perhaps longer term it'd be better to move this into pipfile directly.
In particularly, I think this would be a good idea:
```
>>> p = pipfile.load(inject_env=True)
>>> p.hash
AssertionError: cannot calculate hash on pipfile with already-substituted env vars
```
> Fix env calculation with hashes

- HISTORY.txt
- pipenv/environments.py
- pipenv/project.py
- tests/test_pipenv.py
Also remove `PIPENV_SHELL_COMPAT` which appears to be no longer used.
(confirmed test case fails without this change and passes with it).
Before:
```
$ PIPENV_VENV_IN_PROJECT=1 pipenv install
$ pipenv --venv
/Users/jtratner/example7/.venv
$ mkdir subdir
$ cd subdir
$ pipenv --venv # :(
No virtualenv has been created for this project yet!
```
After:
```
$ pipenv --venv
/Users/jtratner/example7/.venv
$ mkdir subdir
$ cd subdir
$ pipenv --venv
/Users/jtratner/example7/.venv
```
The full test suite doesn't pass locally for me right now so I can't tell if I've broken anything else.
> Detect .venv at project root when in subdirectory

- pipenv/project.py
- tests/test_pipenv.py
- Currently it assumes posix complience and uses `posix=True`
- This breaks when parsing on windows
> Fix `shlex.split()` call to check for posix first

- run-tests.sh
This prevents the pipe syntax in the $TAP_OUTPUT branch from masking the underlying pytest failure.
Reference: http://redsymbol.net/articles/unofficial-bash-strict-mode/
> Set -o pipefail so errors propagate through piping

- Dockerfile
- with the calls in separate lines, there can be caching issues
- changed `apt` to `apt-get` to stop instability warnings
Fixes #1859
> Combine RUN apt-get calls in Dockerfile

- pipenv/core.py
- pipenv/help.py
- pipenv/project.py
- pipenv/utils.py
- tests/test_pipenv.py
1. Fix up a test case that was never passing (but should have) <-- clearly wasn't running in CI (and I missed it as a last minute change right before merging)
2. Remove unused / duplicate imports
3. whitespace fixups
Now when you run flake8, mostly good:
```
$ flake8 tests/*.py pipenv/*.py
tests/test_utils.py:371:14: E131 continuation line unaligned for hanging indent
tests/test_utils.py:382:12: E131 continuation line unaligned for hanging indent
tests/test_utils.py:384:13: E122 continuation line missing indentation or outdented
pipenv/__init__.py:22:1: F401 '.resolver' imported but unused
pipenv/cli.py:15:1: F403 'from .environments import *' used; unable to detect undefined names
pipenv/cli.py:137:12: F405 'PIPENV_SHELL' may be undefined, or defined from star imports: .environments …
```
> Lint + test fixes

- pipenv/utils.py
- tests/test_utils.py
@techalchemy - as we discussed previously - this removes some code that can never be executed.
1. is_vcs requires (req.path or req.uri) to be truthy.
2. (req.path or req.uri) would be true in first if statement
Thus if you have:
```
if (req.uri or req.path or ...) and not req.vcs
elif req.vcs or is_vcs(req.path)
```
if `is_vcs(req.path)` is Truthy, then the first if clause must be
truthy, so it's unnecessary.
Also add a quick test to confirm that originating purpose for that check
is now handled otherwise.
> Remove extraneous is_vcs check

- pipenv/utils.py
- tests/test_utils.py
At this point I think it is better to just parse the whole thing with regex instead. I read some past commits on this part of code and found d00d33be. @eli-b can you help me test if Miniconda’s version output works with this regex pattern?
> Fix Python version parser for 2.7.0

- HISTORY.txt
- pipenv/core.py
- pipenv/patched/piptools/resolver.py
- pipenv/project.py
- pipenv/utils.py
- Fixes #1937, #1683
- Modifies the resolved wheel info on the way into the lockfile to
retain the relative path
> Resolve dependencies of local wheels

- pipenv/patched/piptools/repositories/pypi.py
Re-use pip's safe file cache to store hash values for packages.
Set up is:
1. only hash if the remote provides a checksum/hash in URL (e.g. `https://pypi.python.org/mypkg/whatever-path.whl#md5=....`)
2. Store hash in a path including the checksum/hash in the URL (again, only if valid)
3. always return a hash
I will remove print statements before merging.
Gotta think about how to test this too...
> Hash cache

- pipenv/core.py
Currently, if a new dependency has been added to the `Pipfile` and `pipenv lock --keep-outdated` is run a `KeyError: '<dependency-nam>'` error is raised. Conditioning on whether the dependency is already in the lockfile fixes this.
> Check whether dependency exists in old lockfile during keep-updated lock

- pipenv/cli.py
- pipenv/core.py
- pipenv/project.py
- pipenv/utils.py
- tests/integration/test_install_uri.py
This is an attempt to address sluggish startup time by making costly imports, like pip9 and pipdeptree, lazy.
Timings from my laptop:
BEFORE (at commit 8a67a21d61a2383253fe0dd5e7a8d79d51d30d2d):
```
$ time pipenv >/dev/null --help
real	0m0.844s
user	0m0.751s
sys	0m0.085s
```
AFTER (at commit a2b194ea0a7fa7355dc7987b947af5291e63ebd1):
```
$ time pipenv >/dev/null --help
real	0m0.357s
user	0m0.332s
sys	0m0.026s
```
unit-tests are failing same 5 tests on my laptop on both master and in this branch, so while i haven't broken anything else, I can't say anything about those 5 failures.
> Make costly imports lazy to optimize startup time

- pipenv/utils.py
- tests/unit/test_utils.py
Thanks for this great tool. It makes using python much more fun.
I ran into the following issue when attempting to use it with pypy3.
```
$ pipenv --python /usr/local/bin/pypy3
Creating a virtualenv for this project…
File "/usr/local/Cellar/pipenv/11.10.0/libexec/bin/pipenv", line 11, in <module>
load_entry_point('pipenv==11.10.0', 'console_scripts', 'pipenv')()
File "/usr/local/Cellar/pipenv/11.10.0/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
File "/usr/local/Cellar/pipenv/11.10.0/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
File "/usr/local/Cellar/pipenv/11.10.0/libexec/lib/python3.6/site-packages/pipenv/vendor/click …
```
> Parse pypy3 version string containing multiple lines

- pipenv/cli.py
This makes it easier for someone to realize when they have provided an invalid Python path without missing that message due to the sizable virtualenv traceback which follows it. I first encountered this when someone copy-and-pasted the example from the Conda documentation which has `--python=/path/to/anaconda/python`.
See #1862
> Require “--python” values to exist

- pipenv/core.py
- tests/integration/test_install_uri.py
- This was removed in a refactor for no discernable reason
- The logic is still present in dev-packages
- Fixes #1130
> Re-add check for vcs pkgs presence in pipfile

- docs/basics.rst
When importing from requirements.txt, it may be useful to
keep the versions of packages you have for the moment,
while unpinning them for the future.  This is already supported
via `--keep-outdated`; this commit adds a mention to the docs.
Fixes #908.
> Mention --keep-outdated in docs for importing

- pipenv/core.py
I'd like to be able to use the pyenv auto-installs from within a non-interactive session to allow Dependabot to honour the Python version specified in a Pipfile.
If `PIPENV_YES` is set, it seems like a relatively strong indicator that `SESSION_IS_INTERACTIVE` logic should be ignored, so I don't think there's any need for an additional environment variable. Happy to add an explicit one if you would prefer, though.
> Allow pyenv installs in non-interactive sessions in PIPENV_YES is set

- docs/index.rst
While debugging issue #2072, @techalchemy and @uranusjr both suggested that Homebrew isn't a well-supported option for installing pipenv.
If so, then I suggest updating the docs so that it's not the first-endorsed installation method. I've just swapped it with `pip` so that's the first suggestion newcomers like myself read. Cheers!
> Suggest pip as the first recommended installation method instead of Homebrew

- pipenv/utils.py
- tests/unit/test_utils.py
- Include extras when rebuilding urls from pipfiles
- Fixes #1997 and #2128
> Parse and include extras from vcs and non-vcs urls

- pipenv/utils.py
- tests/unit/test_utils.py
- Fixes #2121
- Add tests for regressions
> Only use `-e` for install when `editable=True`

- HISTORY.txt
Quick, before the author of `requests` notices! 🙀
> Fix typo in HISTORY.txt: reqeuests -> requests

- pipenv/core.py
I think this is actually a regression?
> Call virtualenv by module

- pipenv/project.py
If we don't have a project, we don't have an associated environment.
Fix #2202.
> Fix venv discovery

- pipenv/patched/notpip/_internal/pep425tags.py
- pipenv/vendor/requirementslib/__init__.py
- pipenv/vendor/requirementslib/requirements.py
- pipenv/vendor/requirementslib/utils.py
- tasks/vendoring/patches/patched/_post-pip-update-pep425tags.patch
> Update requirementslib to fix windows paths

- pipenv/core.py
- tests/integration/test_cli.py
> Nelfin fix 2229

- pipenv/core.py
- pipenv/utils.py
- tests/unit/test_utils_windows_executable.py
On Windows, the environment variable `PATHEXT` holds a list (`;`-separated) of extensions that Windows use to look up an executable file when the user enters a (extension-less) command into the prompt. This rewrite makes `find_windows_executable` mimic this behaviour.
Fix #2282.
> Respect PATHEXT when looking for Win executable

- pipenv/core.py
- pipenv/vendor/pipdeptree.py
- pipenv/vendor/vendor.txt
- tasks/vendoring/patches/vendor/pipdeptree-local-pip.patch
Fix `pipenv graph` so that it uses local system pip instead of trying to use patched pip (since this runs in the virtualenv this won't ever work)
- Fixes #2258
- Add patch to prevent import rewrites from catching this again
- Add useful debugging line to print errors to stderr
> Fix pipenv graph

- pipenv/core.py
- Also don't search for requirements.txt if taking in a package name
- Fixes #2222
> Don't search for requirements.txt if using pipfile

- pipenv/core.py
- pipenv/utils.py
Flamegraphs tell me that json resolution failures are incredibly slow and bad for performance
- Disable Json resolver
- Tweak vcs resolution
> Resolver Tweaks

- docs/advanced.rst
- pipenv/cli.py
- pipenv/core.py
- pipenv/environments.py
- pipenv/resolver.py
- pipenv/utils.py
- tests/integration/test_install_basic.py
- tests/integration/test_lock.py
- tests/integration/test_sync.py
- tests/integration/test_uninstall.py
In response to #2075, allow users to override the default PyPI indices (pypi.org, pypi.python.org) with a mirror specified via CLI parameter or environment variable.
> Allow users to override default PyPI index URLs with PyPI mirror URLs

- pipenv/core.py
- pipenv/utils.py
- This has been driving me mad.
> Refactor and cleanup some locking code

- pipenv/core.py
We should try to promote `pipenv run` more. `pipenv shell` is almost never a good idea outside the development phase, but as things currently stand people are using it when they shouldn’t.
Also some refactoring to remove dead code and misleading function name.
> Hint “pipenv run” after creating the virtualenv

- pipenv/cli.py
- pipenv/core.py
- tests/integration/test_pipenv.py
- `pipenv update` currently doesn't actually run `pipenv lock`
- Semantics around this changed but it doesn't look like the code did
- `pipenv update` should operate similarly for all operations by running
`lock` followed by `sync`
- Fixes #2179
> Switch all update workflows to `pipenv lock/sync`

- news/2386.bugfix
- news/2386.vendor
- pipenv/vendor/dotenv/main.py
- tasks/vendoring/patches/vendor/dotenv-windows-unicode.patch
Patch based on theskumar/python-dotenv#101 by @greyli.
> Ensure environs are strings on Python 2 + Windows

- news/2385.feature
- pipenv/core.py
Do a `where` on the command; if it is found, prevent the intermediate `COMSPEC` and use `CreateProcess` directly. Only use `shell=True` if the command is not an executable.
This prevents some unexpected behaviour caused by the intermediate shell process.
> Use shell=False when "run" if possible on Windows

- news/2408.feature
- pipenv/cli.py
- pipenv/core.py
- tests/integration/test_cli.py
and append it to the call to safety
> Allow check to ignore packages 

- setup.py
The new version of click_completion requires its Jinja2 templates to be installed along with the package in order to work. If not, any invocation of `pipenv --completion` results in a `jinja2.exceptions.TemplateNotFound` for the template in question.
I’ve just trivially added the pattern to `setup.py`, and tested that it works.
> Install Jinja2 templates for click_completion

- news/2426.vendor
- tasks/vendoring/patches/patched/_post-pip-update-pep425tags.patch
- tasks/vendoring/patches/patched/prettytoml-python37.patch
This makes PEP 479 enabled Pythons (such as 3.7) work again.
Otherwise you get:
RuntimeError: generator raised StopIteration
Fixes https://github.com/pypa/pipenv/issues/2426
------
Untested. The vendoring script fails with unrelated problem.
> prettytoml: Catch StopIteration in AbstractTable._enumerate_items

- pipenv/patched/piptools/repositories/pypi.py
Tiny one, but previous comment was confusing.
> Fix typo in comment ('Pip < 9 and below' -> 'Pip 9 and below')

- news/2433.bugfix
- news/2433.vendor
- pipenv/vendor/requirementslib/__init__.py
- pipenv/vendor/requirementslib/models/requirements.py
- pipenv/vendor/vendor.txt
- tests/integration/test_install_uri.py
> Update requirementslib to fix #2421

- pipenv/utils.py
- tests/integration/test_lock.py
Fix the `HackPythonVersion` function so that it injects env only if the value is valid.
> Add test case for #1901

- setup.py
This argument prevents accident install `pipenv` on not supported python versions.
The syntax for this string you can find in [PEP440](https://www.python.org/dev/peps/pep-0440/).
Note: this feature works with pip 9.0+.
> Add `python_requires` in setup.py

- pipenv/help.py
I don't know why but on MacOS  when you execute this command `python -m pipenv.help` and redirect output stream to some another file, script fails with exception. 
```bash
$ python -m pipenv.help > test.txt 
File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/Users/maxkrivich/Projects/pipenv/pipenv/help.py", line 89, in <module>
main()
File "/Users/maxkrivich/Projects/pipenv/pipenv/help.py", line 48, in main
print(u'Pipenv–specific environment variables:')
UnicodeEncodeError: …
```
> Fix `UnicodeEncodeError` in help.py

- pipenv/core.py
If the `pip` output already has been printed due to it containing the string "Ignoring", then avoid printing it again if `--verbose` is enabled.
Ironically, in my simple test of this (`pipenv install --verbose` in a ) the "Ignoring" string is only included in the `pip` output if `--verbose` is supplied.
I've tried to make a screenshot of it here to show the problem, but I had to make it quite small in order to fit it all on screen. You can however see that the yellow and blue output is duplicated:
> Avoid double `pip` output if `--verbose` is used an output includes "Ignoring"

- pipenv/shells.py
> Fix subprocess usage for Python 2

- docs/dev/contributing.rst
Pretty straight forward change. This seemed like a typo to me. I'm assuming this file is used to generate https://docs.pipenv.org/dev/contributing/ as well.
> Change "Github Pull Pipenv" to "Github Pull Requests" in contributing.rst

- docs/basics.rst
In `docs/basics.rst` I changed `new package your provided.` to `new package you provided.`
> Fix small docs typo

- docs/_static/custom.css
- docs/advanced.rst
- docs/conf.py
- docs/diagnose.rst
- pipenv/environments.py
- pipenv/shells.py
Default values are added to docstrings so they appear in the docs. This should help maintainers to keep them up-to-date.
Fix #2547.
How the section looks after the change:
> Automatically generate environment variable docs

- docs/advanced.rst
It's a partial duplicate of the "Custom Virtual Environment Location" section.
> Delete "Changing Where Pipenv Stores Virtualenvs"

- news/2563.bugfix
- pipenv/cmdparse.py
- tests/unit/test_cmdparse.py
Windows built-in commands don't always work well with quotes.
```cmd
rem The path can be interpreted correctly, but not "/w".
dir "/w" "C:\"
rem Outputs "foo" "bar", with quotes!
echo "foo" "bar"
```
The solution (I think) is to be less aggressive. Only quote things if they need to be quoted (i.e. contains whitespaces).
> Only quote arguments during cmdify if needed

- pipenv/cli.py
Reverts pypa/pipenv#2542 
This breaks `pipenv install as all flag should be capture by it. Reverting until we address that.  My bad guys
> Revert "Add docstrings to show short_help when running --help"

- .env
- CONTRIBUTING.md
- pytest.ini
- run-tests.bat
- run-tests.sh
- tests/integration/conftest.py
- tests/integration/test_install_basic.py
- tests/pytest-pypi/pytest_pypi/app.py
- tests/pytest-pypi/pytest_pypi/templates/package.html
Addresses some difficulties encountered when trying to get up to speed contributing to the project.
- Fixes pytest.ini to ignore things like `build` dirs when looking for tests
- Fixes resolving vendored test packages when running tests outside the repo root
- Add some docs on development setup and testing
There are a few more structural decisions that this doesn't address:
- repo `pipenv` shadowing global package when bootstrapping (pypa/pipenv#2557)
- The docker-compose image doesn't have python 3.7, so `make test` doesn't work
- The test Dockerfile is outside this repo, so ^ can't be fixed as easily
> Simplify testing for new contributors

- pipenv/cli.py
This reverts #2571 which mistakingly reverted #2542 which addressed #2381 by adding `short_help` text to the output of `--help`.
Let me know if this works @erinxocon!
> Revert "Revert "Add docstrings to show short_help when running --help""

- pipenv/project.py
- tests/integration/test_lock.py
Applies the fix suggested in https://github.com/pypa/pipenv/issues/2504#issuecomment-402853014
Resolves #2504
I couldn't find a quick/easy way to test this locally before pushing (just saw the Makefile), so using buildkite to test a bit blind. 😅
> Serialize prettytoml ArrayElements as lists

- README.md
This makes the badges in the README inline which pushes some of the more informative content up the page.
Super small, nit change, but a bunch of other projects do the same :P
* https://github.com/pypa/pip
* https://github.com/requests/requests
> Make README badges inline

- pipenv/core.py
This shows the better error to the user if virtual env is broken
also suggests commands that can solve the issue
Closes https://github.com/pypa/pipenv/issues/1918
> Show better error if virtual env is broken

- setup.py
find_packages' exclude keyword is a bit unintuitive in that it only excludes the top-level directory specified, but happily includes all the children unless you wildcard those too.
Update this to actually match the original intent.
> Exclude more things from installation which aren't meant to be installed

- news/2610.bugfix
- pipenv/core.py
> Fix `exists-action` argument passing

- pipenv/core.py
- pipenv/project.py
- pipenv/utils.py
- Use `get_installed_distributions` from pip
- This cascades to `pkg_resources.working_set` which relies on
`sys.path` to uncover packages
- Consequently I implemented `temp_path()` as a contextmanager in the
style of `temp_environ()`
- This requires us to know the environment's `sys.path`, so
`load_path(python)` will do a `json.dumps` of `sys.path` to stdout
which then gets loaded and returned
- Allows us to avoid trying to hack around `pip freeze` output to parse
out names from comments etc
- Provides other potential uses
> Leverage pip to access installed packages

- pipenv/shells.py
Fix #2623. The detection logic is also improved a little to handle Cmder and MSYS at the same time.
> Support Msys Bash

- docs/advanced.rst
As of the release version 2018.2 PyCharm has a full pipenv support. [Source](https://www.jetbrains.com/pycharm/whatsnew/ "New features")
> PyCharm now fully supports pipenv

- news/2607.bugfix
- pipenv/core.py
- pipenv/project.py
- tests/integration/test_lock.py
Now will return None when facing JSONDecodeError when loading the lockfile.
do_init will remove the old lockfile and replace it.
Fix #2607
> Add JSONDecodeError handling for get_lockfile_hash

- news/2676.bugfix
- pipenv/utils.py
This works around a faulty virtual environment on my machine that makes Python throw `OSError: too many level of symlinks`. If a virtual environment is faulty, we can just ignore it.
> Ignore OSError in is_virtual_environment check

- news/2656.bugfix
- pipenv/utils.py
- tests/unit/test_utils.py
`pipenv` breaks when the first specified source in the Pipfile contains a username and password.
> Fix parsing of verify_ssl=false in urls with authentication in Pipfile

- tests/integration/conftest.py
- tests/integration/test_install_uri.py
I was trying to figure out why I was not able to install some `git+git` and some `git+ssh` dependencies with pipenv. Turns out I was falling prey to the slight syntax differences of those two alternatives compared to `git+https`. 
I adapted the `git+https` test for `git+git` and `git+ssh` and thought I'd contribute them. Not sure if it is worth keeping the `gitdb2` check in the two new tests though.
> Adding some git+git and git+ssh tests as examples

- tests/integration/test_install_twists.py
Issue #2613 was fixed via #2643, but the fix did not include a regression test.
This pull request proposes an integration test that failed prior to #2643 but succeeds now.
By taking a look at #2643 it wasn't clear to me how to write a unit test instead of this integration test. Because this integration test relies on web connectivity to a github repository, I created a dummy repo to be used just by this test. I suspect it is preferable to fork that repo under the `pypa` org so as not to have it under my personal account though.
There doesn't seem to be a relevant fragment for just adding a regression test
> Add test for setup.py::dependency-link field

- news/2732.bugfix
- pipenv/resolver.py
- pipenv/utils.py
`pipenv lock --verbose` does not set `PIPENV_VERBOSITY` correct for the resolver subprocess, and does not correctly show verbose output.
This patch adds the verbosity value into environment variables to make sure the resolver knows itself is in verbose (or debug) mode.
Some other changes are added to make the verbose flag understood by `pipenv-resolver`, and works well with environment variables (using `max()` calls).
> Correctly pass verbosity to resolver

- README.md
- news/2685.doc
There was a request for [additional documentation on installing from git](https://github.com/pypa/pipenv/issues/2685)
I updated the README.md with an example to install requests, this could also be added to the official docs as well, but I figured this was a good start. I didn't add any additional information to the `news/` directory because I wasn't sure what the naming method was 
* [ x ] Associated issue
* [ x ] A news fragment in the `news/` directory to describe this fix with the extension `.bugfix`, `.feature`, `.behavior`, `.doc`. `.vendor`. or `.trivial` (this will appear in the release changelog). Use semantic line breaks and name the file after the issue number or the PR #.
> Added an example to README.md for installing from git

- pipenv/utils.py
`pipenv` might fail to resolve dependencies when the cache is not cleared. The error message is uninformative.
This PR will print a more useful error message when dependencies fail to resolve, instructing the user to first try clearing the dependency cache with `$ pipenv lock --clear`.
This PR has been submitted based on the discussions in #2596.
> Improves message when dependencies could not be resolved.

- pipenv/progress.py
Black moved a couple comments to some funky places.
This moves the comments back to the lines to which they refer.
> Move misformatted comments

- news/2718.behavior
- pipenv/core.py
Provide better error-handling for #2718 (so the command never throws OSError).
Some Windows users are used to launch files without specifying a command, e.g.
> my-script.py
This works in the shell because Windows will automatically choose an command based on file association, and with newer Python versions, the Py Launcher (py.exe) automatically chooses the correct Python based on shebang-parsing.
A similar syntax, unfortunately, does not currently work in Pipenv
> pipenv run my-script.py
Since my-script.py will be treated as a real application by the subprocess module.
This patch catch Windows error 193 during subprocess initialization, and fall back to use COMSPEC (shell=True) when it happens, to provide better support for this use case.
> Improve "run" behavior on Windows

- news/2754.trivial
- pipenv/core.py
- tests/unit/test_core.py
Addresses #2754.
This displays a warning if the `PIPENV_DOTENV_LOCATION` environment variable is set but the file specified does not exist.
> Warning for non-existent PIPENV_DOTENV_LOCATION file

- README.md
The badge UI for VSTS builds is now there (though a little hard to find - see the screen below), so I added badges for your readme if you'd like them.
I put both Linux and Windows builds there, though if you'd rather only have the Windows one that's fine (feel free to just edit this PR yourself). I also used a not-quite-released feature to customize the text on the badge, so when that rolls out (days-to-weeks, as I understand) the "build" text will be replaced with "Windows" or "Linux".
> Add VSTS CI badges

- docs/dev/contributing.rst
- news/2793.doc
The link to the "be cordial" essay on https://pipenv.readthedocs.io/en/latest/dev/contributing/#be-cordial is out-of-date. I updated it.
Note: the similar link in `CODE_OF_CONDUCT.md` already points at the current essay location, so that one is fine.
> Fixed link to the "be cordial" essay in the contribution doc.

- docs/basics.rst
- news/2792.doc
The example url for doing `pipenv install -e some-repo-url#egg=something` was missing the `egg=` in the fragment identifier. I fixed that.
I'll add a news/ file as soon as I've got a PR number :-)
> Added missing 'egg=' in the example url

- CODE_OF_CONDUCT.md
The code of conduct document linked to the wrong code of conduct.
This fixes the code of conduct document to link to the PyPA code of conduct.
> Update code of conduct location

- pipenv/vendor/click/_unicodefun.py
There should be a space after hyperlink which is point to `click` document.
Currently, when an exception about supported locale occurs:
```
RuntimeError: ...STRIPPED... Consult http://click.pocoo.org/python3/for mitigation steps.
```
Add a single space after the link to http:click.pocoo.org/python3/ .
> Add blank space after link

- news/2808.trivial
- tests/integration/test_install_twists.py
- tests/integration/test_uninstall.py
There are 2 unclosed files in tests, nothing big.
Use context managers.
> Fix 2 ResourceWarning: unclosed file, in tests

- HISTORY.txt
- setup.py
- tests/pytest-pypi/setup.py
As spelled on https://pypi.org/.
> Correct capitalization of PyPI

- news/2877.bugfix
- pipenv/utils.py
This PR fixes #2786 as `pipenv` tries to iterate through `WORKON_HOME` (`virtualenvs` folder) without ensuring it exists first.
Creating the `WORKON_HOME` directory from inside `pipenv/utils.py:get_workon_home`.
> Create virtualenvs directory if it does not exist

- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Custom.md
- .github/ISSUE_TEMPLATE/Feature_request.md
https://github.com/pypa/pipenv/issues/2893
> How does this pull request fix your problem? Did you consider any alternatives? Why is this the *best* solution, in your opinion?
I just removed this link.
> Remove a 404 link in issue templates

- README.md
Azure Pipelines now uses https://dev.azure.com/pypa/pipenv instead of https://pypa.visualstudio.com/pipenv (even though redirects will work for some time).  This updates the build badges to use that new domain.
> Use new Azure Pipelines domain in build badges

- news/2912.bugfix
- pipenv/environments.py
Try to fix https://github.com/pypa/pipenv/issues/2912
Load patched pip by setting environment variable ```PIP_SHIMS_BASE_MODULE```
> Fixed vcs is not supported in pip9

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
When I try to open/view issues or pull requests, I found it a littile bit difficult to distinguish issue/pr headers from their content, since level ```#####``` is too similar with the contents.  Maybe it is better to level up the headers.
Well it is a little bit opinionated, but I still would like to share my thoughts. 😄 
Update github templates' header level to ```###```.
> Level up the template headers

- news/1393.bugfix
- pipenv/core.py
- pipenv/utils.py
- pipenv/vendor/requirementslib/__init__.py
- pipenv/vendor/requirementslib/models/requirements.py
- pipenv/vendor/requirementslib/models/utils.py
> Update requirementslib - fix editable requirements

- news/2971.bugfix
- pipenv/project.py
- tests/integration/test_install_basic.py
Fixes https://github.com/pypa/pipenv/issues/2960, which was caused by a change in the API for `toml`.
> Fix parsing of outline tables

- news/2849.bugfix
- pipenv/core.py
- pipenv/project.py
- tasks/vendoring/patches/vendor/pipdeptree-updated-pip18.patch
- tests/integration/test_cli.py
> Properly scope pipenv clean to local env

- pipenv/core.py
Latest release of pipenv gave me this error; seemed like an easy fix
Looks like a call to `add_index_to_pipfile` uses a keyword called `trusted_host`, but the keyword is `verify_ssl`
Changed `trusted_host` to `verify_ssl`. Doesn't look like it's referenced anywhere else. And it fixed pipenv for me.
Don't believe there is an issue for it though.
> Keyword arg error in Getting `add_index_to_pipfile`

- news/2979.bugfix
- pipenv/core.py
- pipenv/project.py
- pipenv/utils.py
Fix trusted-host passthru
- Fix marker cleaning
- Fixes #2979
> Fix trusted-host passthru

- news/2998.bugfix
- news/3007.vendor
- pipenv/cli/command.py
- pipenv/core.py
- pipenv/utils.py
- pipenv/vendor/pythonfinder/__init__.py
- pipenv/vendor/pythonfinder/models/python.py
- pipenv/vendor/vendor.txt
- pipenv/vendor/vistir/__init__.py
- pipenv/vendor/vistir/misc.py
Escape command line requirements as necessary
- Fixes #2998
> Fix normalization during install

- pipenv/core.py
https://github.com/pypa/pipenv/issues/2990#issuecomment-428935640
- Fixes #2990
Adding trailing space to ``--prompt`` argument when creating the virtualenv.
> Add trailing white space to --prompt argument when creating virtualenv

- news/3026.bugfix
- pipenv/utils.py
- tests/integration/test_lock.py
Fixed https://github.com/pypa/pipenv/issues/3026
This is a annoying critical bug. Fixed by do not append ```extra``` when translating markers since they are unnecessary. Also test is added to avoid regression in further development.
> Fixed unnecessary extras are added in lockfiles

- news/3069.trivial
- pipenv/environments.py
The issue is describe in #3068 : Impossible to hide the "Courtesy Notice" about active virtualenv.
The origin of the issue is that a value of `-1` for `PIPENV_VERBOSITY` is ignored but the current logic.
`isdigit()` is not adapted to test a negative value:
```
In [1]: '-1'.isdigit()
Out[1]: False
```
Use `int()` to cast and catch `ValueError`.
> Fix PIPENV_VERBOSITY parsing logic

- docs/advanced.rst
Fix sentence structure by removing stray "you".
> Remove 'you' from sentence in docs page

- README.md
- docs/index.rst
Add the button:
[![Try in browser](https://cdn.rawgit.com/rootnroll/library/assets/try.svg)](https://rootnroll.com/d/pipenv/)
to README and docs to launch a Pipenv playground and try it out right in the browser.
https://rootnroll.com is a standalone service for running cli playgrounds.
Source files used to create the Pipenv playground: https://github.com/rootnroll/library/tree/master/pipenv
Automated build of docker image: https://hub.docker.com/r/rootnroll/demo-pipenv/
> Add try-in-browser button to launch Pipenv playground (README and docs)

- news/3131.bugfix.rst
- pipenv/_compat.py
Fix unicode encoding to replace non-ascii chars
- Drops any unmapped non-ascii characters on non-utf8 systems
- Fixes #3131
> Fix unicode encoding to replace non-ascii chars

- news/1977.feature.rst
- news/2411.feature.rst
- news/2828.feature.rst
- news/2885.bugfix.rst
- news/3047.bugfix.rst
- news/3055.bugfix.rst
- news/3099.bugfix.rst
- news/3113.bugfix.rst
- pipenv/__init__.py
- pipenv/_compat.py
- pipenv/cli/command.py
- pipenv/core.py
- pipenv/exceptions.py
- pipenv/project.py
- pipenv/utils.py
- pipenv/vendor/requirementslib/models/requirements.py
- tests/integration/test_sync.py
- Fix inadvertent occasional global installation of files
- Fix inadvertent occcasional global removal of files
- Fix empty output from `pipenv update --outdated`
- Fixes #2828
- Fixes #3113
- Fixes #3047
- Fixes #3055
> Fix virtualenv path derivations

- news/3134.bugfix.rst
- pipenv/project.py
Found an edge case in `project.get_location_for_virtualenv()`. If `PIPENV_VENV_IN_PROJECT` is true, `.venv` is always used as a directory, not read as a file.
To reproduce:
```
$ mkdir my-project
$ cd my-project
$ export PIPENV_VENV_IN_PROJECT=1
$ touch Pipenv
$ echo './.i-want-my-venv-here' > .venv
$ pipenv lock   # This will fail because Pipenv wants to use .venv as the virtual environment.
```
I reorganised the discovery function. Comments are added so branching is more straightforward (hopefully). The new logic works like this:
1. Is there a project root yet? If not…
* Use `$PWD/.venv` if `PIPENV_VENV_IN_PROJECT` is set
* Use the `$WORKON_HOME/[name]-[hash]` scheme by default
2. Does `.venv` exist in project root? If not, use the same logic as 1. (replacing `$PWD` with project root) …
> Rewrite venv discovery logic

- news/2848.bugfix.rst
- pipenv/cli/command.py
- pipenv/cli/options.py
- pipenv/core.py
Respect --skip-lock option for uninstall
- Fixes #2848
> Respect --skip-lock option for uninstall

- pipenv/vendor/delegator.py
Continue to fix https://github.com/pypa/pipenv/issues/3102. Sometime ```TIMEOUT``` errors will be raised as well as ```EOF```.
> Continue to fix cannot concatenate str and type issue during locking

- news/3179.trivial
- pipenv/core.py
Closes #3179
The package names can be unicode or str in python2. Using ```repr``` will translate them to ```u''``` or ```''``` format.
I think removing ```repr``` is safe since the names are passed into ```format```. Actually some codes already did this such as https://github.com/pypa/pipenv/blob/master/pipenv/core.py#L2164-L2168
> Better output of pipenv clean and uninstall

- pipenv/core.py
Closes https://github.com/pypa/pipenv/issues/3181
Since index source per-line is not working, let's just disable it.
> Do not add index source per-line in requirements files

- news/3158.bugfix.rst
- pipenv/cmdparse.py
- tests/unit/test_cmdparse.py
Close #3169. I adopted the solution, but only apply it to the first argument (the command). @frostming can you verify if this fixes your problem?
> Quote command if it contains parentheses

- pipenv/cli/options.py
Currently ```--skip-lock``` option is used for several commands, such as ```install```, ```uninstall```. The ```Ignore locking mechanisms when **installing**``` is not appropriately anymore.
> Update skip lock option help info since it is used in several operations

- pipenv/core.py
The ```pipenv lock -r``` should only output all default packages. The ```pipenv lock -r -d``` should only output all dev packages. But currently master branch will ouput both default and dev packages for ```pipenv lock -r -d```. This behaviour is different with any released versions.
For example, following Pipfile currently would output all packages by ```pipenv lock -r -d```.
```
[[source]]
url = "https://pypi.org/simple"
name = "pypi"
[dev-packages]
requests = "*"
[packages]
flask = "*"
[requires]
python_version = "3.6"
```
```
D:\test>pipenv lock -r -d
-i https://pypi.org/simple
certifi==2018.10.15
chardet==3.0.4
click==7.0
flask==1.0.2
idna==2.7
itsdangerous==1.1.0
jinja2==2.10
markupsafe==1.1.0
requests==2.20.0
urllib3==1.24.1
werkzeug==0.14.1
```
Actually it should …
> Only output dev packages for pipenv lock -r -d

- news/2737.bugfix.rst
- pipenv/patched/prettytoml/tokens/py2toml.py
- pipenv/patched/prettytoml/tokens/toml2py.py
- tasks/vendoring/patches/patched/prettytoml-unicode.patch
- tests/unit/test_vendor.py
Fix #2737 Prettytoml doens't support non-ASCII characters well.
Since the upstream doesn't seem to be maintained anymore, I create a patch for prettytoml. The fix works well on my machine(3.7, Windows/WSL)
> Fix non-ASCII support for prettytoml

- news/3183.bugfix.rst
- news/3185.bugfix.rst
- pipenv/cli/options.py
- pipenv/core.py
- pipenv/project.py
- pipenv/utils.py
- Pass `pre` correctly when using `pipenv install --pre`
- Ensures we always make inline tables when writing to pipfile
- Fixes #3183
- Fixes #3185
> Fix double completion message on locking

- pipenv/utils.py
Signed-off-by: frostming <mianghong@gmail.com>
The fix of #3147 is reverted in later commits(#3158).
Make sure the hash of artifacts are included in lockfile
Fixes #3212
> Bring back the fix of #3147

- CHANGELOG.rst
Fix 'Release 2018.11.14' markup.
From:
To:
> fix 'Release 2018.11.14' markup

- news/3257.bugfix.rst
- pipenv/utils.py
See https://github.com/pypa/pipenv/issues/3257.
When running multiple pipenv processes simultaneously, they may both attempt to use 'mkdir_p' at the same time, which can cause one of the pipenv processes to crash when it tries to create a directory that already exists. This is a classic TOCTOU bug that has bitten many a piece of software.
I personally hit this in my continuous integration setup where I invoke `pipenv` multiple times, potentially in parallel, and see crashes such as this:
```
[ tes/examples/python/smoke-test ] sample: /home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/examples/python/smoke-test
[ etes/examples/python/guestbook ] sample: /home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/examples/python/guestbook
[ tes/examples/python/smoke-test ] pulumi: …
```
> Fix a TOCTOU issue in mkdir_p

- pipenv/vendor/pythonfinder/__init__.py
- pipenv/vendor/pythonfinder/environment.py
- pipenv/vendor/pythonfinder/models/python.py
- pipenv/vendor/pythonfinder/utils.py
Update pythonfinder for resilient parsing
> Update pythonfinder for resilient parsing

- news/3287.bugfix.rst
- pipenv/core.py
After a new Python version was installed by `pyenv` it was never found, because the old Pythons were cached.
Bust the cache after installing a new Python.
> Clear pythonfinder cache after Python install

- news/3261.bugfix.rst
- pipenv/_compat.py
- pipenv/core.py
- tests/integration/test_pipenv.py
- tests/pytest-pypi/pytest_pypi/app.py
Unset PYTHONHOME during non-global installs
- Fixes #3261
>  Unset PYTHONHOME during non-global installs & cleanup unused code

- pipenv/exceptions.py
There is a bug, `self` missing self when calling base class constructor.
```
File "/usr/local/lib/python2.7/site-packages/pipenv/exceptions.py", line 168, in __init__
PipenvUsageError.__init__(message=fix_utf8(message), extra=extra, **kwargs)
TypeError: unbound method __init__() must be called with PipenvUsageError instance as first argument (got nothing instead)
```
Pass in `self` as the first argument.
> Pass self when calling base class constructor.

- news/3318.bugfix.rst
- pipenv/core.py
- tests/integration/test_install_basic.py
Abort pipenv when installing a non-exist package, before adding the package name to Pipfile.
Closes #3318
> Abort pipenv when pip install fails

- news/3313.bugfix.rst
- pipenv/_compat.py
Currently, pipenv does this:
1. In `__init__.py`, `sys.stdout` and `sys.stderr` are replaced by `io.TextIOWrapper`s with `encoding` set to `'utf8'` (no dash): https://github.com/pypa/pipenv/blob/d9ebad335dc4cfff9cb223f7cc3141066044b65b/pipenv/__init__.py#L31-L36
2. In `_compat.py`, the encoding is forced to UTF-8 by checking if `sys.stdout/err.encoding.lower()` is equal to `'utf-8'` (with a dash): https://github.com/pypa/pipenv/blob/d9ebad335dc4cfff9cb223f7cc3141066044b65b/pipenv/_compat.py#L331
Fixes #3313.
- Canonicalizes the encoding name using `codecs.lookup()`. This will always return `'utf-8'` for UTF-8 encodings, no matter what alias is used (`'utf8'`, `'UTF-8'`, `'u8'`, etc.)
- Catch `ImportError` when importing `ctypes`, so that this code path doesn't crash with PyPy (which …
> Handle alternate names for UTF-8 encoding

- news/3307.bugfix.rst
- pipenv/cmdparse.py
- tests/unit/test_cmdparse.py
Carets introduce a difficult situation since they are essentially “lossy” when parsed. Consider this in cmd.exe:
> echo "foo^bar"
"foo^bar"
> echo foo^^bar
foo^bar
The two commands produce different results, but are both parsed by the shell as `foo^bar`, and there's essentially no sensible way to tell what was actually passed in. This implementation assumes the quoted variation (the first) since it is easier to implement, and arguably the more common case.
Fix #3307.
> Quote arguments with carets for cmd.exe

- README.md
The Azure Pipelines build badges are pointing at the old pipelines.
This PR points the build badges to the new/current pipelines.
Thanks for considering this PR!
> Point build badges at the current pipelines

- tests/integration/test_install_basic.py
Since we are moving from travis to azure, let's re-enable the test disabled in travis.
> Enable test disabled in travis

- news/3362.trivial.rst
- pipenv/utils.py
- tests/integration/test_install_basic.py
- tests/integration/test_project.py
In the previous codebase, https://github.com/pypa/pipenv/blob/master/pipenv/utils.py#L94 is always ignored and the table gets rewritten, losing any spaces between inline table keys. The reason behind this is we can't get the real data structure from the `value` here.
Get the real data type from `container._body`
> Preserve inline spaces in toml

- news/3348.feature.rst
- pipenv/core.py
There is no simple way to see the what is the command line that's used for `pipenv run`
Output the command line to the log as `info`, so it's output when run in verbose mode.
Seeking early feedback.
> Enable output of script line for 'run' in verbose mode

- setup.py
Just simple fix typo on `setup.py`. in setup function it specifies 'upload' but in UploadCommand's doc-string it say `support setup.py publish`. I just fixed that.
https://github.com/pypa/pipenv/blob/51b46c9f586de3965e55f3bc182f83470b07c101/setup.py#L71
https://github.com/pypa/pipenv/blob/51b46c9f586de3965e55f3bc182f83470b07c101/setup.py#L152
> simple bug fix in setup.py

- news/3384.bugfix.rst
- pipenv/core.py
pipenv install PACKAGE_NAME --selective-upgrade crashes with unhashable type: 'list
```
File "/usr/local/bin/pipenv", line 11, in <module>
sys.exit(cli())
File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 717, in main
File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core. …
```
> Fix unhashable type error in --selective-upgrade

- setup.py
Support for Python 2.6 was removed in (or before) 47604c644bf18bbbb39800833fcf0dd96526f1eb. Therefore, no need to include these dependencies.
> Remove Python 2.6 dependencies from setup.py

- news/3427.bugfix.rst
- pipenv/project.py
- tests/integration/test_lock.py
Fixes #3427 
Derive missing fields from existing ones for Pipfile's source.
> Populate source when getting lockfile

- pipenv/core.py
Trivial fix to formatting of the warning message you get when running `pipenv graph` before a virtualenv exists.
> core: nonexistent virtualenv warning msg: add missing space

- news/3449.bugfix.rst
- pipenv/project.py
- pipenv/utils.py
- tests/integration/conftest.py
- tests/integration/test_lock.py
When Pipfile source name is changed and do `pipenv lock` the index names in lock file are not updated correctly
Only consider sources in Pipfile when locking, since the sources in lock file are not updated yet.
Fixes #3449
> Update the index names in lock file

- news/3595.feature.rst
- pipenv/core.py
- pipenv/environments.py
- pipenv/progress.py
Windows can't be pleased by the emojis.
Keep the behavior that emojis are hidden by default for windows users, but can be enabled by setting `PIPENV_HIDE_EMOJIS=0`
> Let windows user configure to show emojis

- .azure-pipelines/jobs/run-tests-windows.yml
- .azure-pipelines/jobs/run-tests.yml
- .azure-pipelines/steps/create-virtualenv-linux.yml
- .azure-pipelines/steps/create-virtualenv.yml
- .azure-pipelines/steps/install-dependencies.yml
- .gitignore
- news/2783.bugfix.rst
- pipenv/__init__.py
- pipenv/cmdparse.py
- pipenv/core.py
- pipenv/exceptions.py
- pipenv/utils.py
- pipenv/vendor/vistir/misc.py
- pipenv/vendor/vistir/path.py
- pipenv/vendor/vistir/spin.py
- pytest.ini
- setup.cfg
- tests/integration/conftest.py
- tests/integration/test_install_basic.py
- tests/integration/test_install_markers.py
- tests/unit/test_utils.py
Fix python path discovery if not called `python`
- Begin a refactor of `delegator.run` invocation to ensure we capture
and handle failures with our own exception wrappers
- Additoinally capture output and error logging and command information
when running in verbose mode (should avoid significant repitition in
the codebase)
- Refactor `which` and `system_which` to fallback to pythonfinder's
implementation
- Abstract `is_python_command` to identify whether we are looking for
python, this enables us to rely on `pythonfinder.Finder.find_all_python_versions()`
to ensure we aren't skipping python versions
- Should be resilient to environments where there is no `which` utility
- Fixes #2783 
- Fixes #3363
- Fixes #3513 
- Fixes #3533
> Fix python path discovery if not called python

- news/2553.behavior.rst
- pipenv/core.py
- pipenv/exceptions.py
#2553 
Conservative checks of known exceptions when subprocess returns output.
> conservative check for known exceptions in subprocess stderr.

- docs/_templates/sidebarintro.html
- docs/_templates/sidebarlogo.html
👋 team,
TL;DR: Add same search experience as https://docs.python-guide.org/
I'm working at Algolia on the a project called [DocSearch](https://community.algolia.com/docsearch/) which goal is to enhance documentation websites with exhaustive, fast and relevant search. You might have seen DocSearch live already on websites like [Bootstrap](https://getbootstrap.com/), [Brew](https://brew.sh/) or [jQuery](https://jquery.com/).
We use pipenv and we love it, we want to give back to this great project.
I have created [a preview of this PR](https://docsearch-pipenv.netlify.com/) and what DocSearch on the pipenv website could will look like here. Feel free to try it and let us know what you think. Please not the learn-as-you-type experience and the typo tolerance:
[![demo of DocSearch + …
> [doc website] Add a nice search experience

- CONTRIBUTING.md
Two broken documentation links in CONTRIBUTING.md
Replaced broken urls with correct ones
> Fix broken documentation links in CONTRIBUTING.md

- news/3724.trivial.rst
- tests/integration/conftest.py
See https://docs.pytest.org/en/latest/mark.html#update-marker-code
`get_marker()` was removed form pytest 4. In Fedora, we've already updated to pytest 4.
https://docs.pytest.org/en/latest/deprecations.html#node-get-marker
https://docs.pytest.org/en/latest/mark.html#update-marker-code
I've changed all `get_marker()` to `get_closest_marker()`. All are checked for None, so we only ask "is there some", not "give me all".
> Pytest 4: Update to get_closest_marker

- news/3768.bugfix.rst
- pipenv/resolver.py
- pipenv/utils.py
- pipenv/vendor/requirementslib/models/requirements.py
- pipenv/vendor/requirementslib/models/setup_info.py
- setup.py
When pinning outdated dependencies, `--keep-outdated` can throw a `KeyError` on VCS dependencies because they don't have a version number to pin or compare.
> Fix keyerror in keep_outdated when using VCS dependencies

- docs/advanced.rst
- news/2317.doc.rst
Documentation should mention variable expansion works only in [[source]] entries #2317
As suggested I added the use of the operator only in the [[source]] section.
I also simplified the text on the alternatives of usage of variable expansion.
- Fixes #2317
> #2317 documentation variable expansion

- .azure-pipelines/steps/run-tests-linux.yml
- .azure-pipelines/steps/run-tests-windows.yml
- .azure-pipelines/steps/run-tests.yml
- Pipfile.lock
- news/3577.feature.rst
- news/3647.bugfix.rst
- news/3656.bugfix.rst
- pipenv/core.py
- pipenv/environments.py
- pipenv/patched/piptools/utils.py
- pipenv/resolver.py
- pipenv/utils.py
- pipenv/vendor/vistir/compat.py
- pipenv/vendor/vistir/misc.py
- tasks/vendoring/patches/patched/piptools.patch
- tests/integration/test_lock.py
Add new feature toggle for VCS dependency resolution
- Fixes #3577
> Add new feature toggle for VCS dependency resolution

- Pipfile.lock
- news/3763.feature.rst
- pipenv/core.py
- We used to override `PIP_NO_DEPS` by default when handling VCS or file
dependencies
- This PR exempts VCS and file dependencies from that rule since we are
able to resolve them in a pre-lock resolution step
- Fixes #3763
> Don't override PIP_NO_DEPS by default

- news/3652.feature.rst
- pipenv/environments.py
Fixes #3652 where PIPENV_INSTALL_TIMEOUT could not be changed. This was preventing users from setting longer timeouts when `pipenv lock` was taking over 15 minutes.
Follows similar format to other environment variables in environments.py to get the environment variable, while keeping the same default.
> Allow overriding `PIPENV_INSTALL_TIMEOUT` environment variable

- news/3819.bugfix.rst
- pipenv/core.py
Fixes #3819  
Iterate over all possible python executables, instead of using `which("python", allow_global=True)`. This is to keep consistent with what `which_pip` does when `system=True`.
Pipenv is usually installed as an isolated application. By this method, `sys.executable`, which is the path of the isolated python interpreter, won't be preferred in the first place.
> Find the python interpreter for pipenv check --system.

- news/3644.trivial.rst
- tests/integration/test_cli.py
- tests/integration/test_install_basic.py
- tests/integration/test_pipenv.py
- tests/integration/test_project.py
- tests/integration/test_uninstall.py
This replaces requests with tablib in tests where using requests
in a de-vendored environment causes the tests to fail unnecessarily.
Continuation of https://github.com/pypa/pipenv/issues/3644
How does …
> Avoid using requests unnecessarily in tests

- news/3718.bugfix.rst
- pipenv/cli/command.py
- pipenv/cli/options.py
- pipenv/core.py
- pipenv/vendor/requirementslib/models/setup_info.py
Ensure we always respect --site-packages
- Sometimes we fail to respect `--site-packages` when it is passed with
`--install`
- This resolves that and ensures we always pass it to `ensure_project`
- Fixes #3718
> Ensure we always respect --site-packages

- news/3844.behavior.rst
- pipenv/cli/command.py
This PR re-enables `--help` option for `pipenv run` command.
There are a few issues related to this problem:
- https://github.com/pypa/pipenv/issues/1405
- https://github.com/pypa/pipenv/issues/2127
- https://github.com/pypa/pipenv/issues/2843
As you see, it is a reoccurring confusion that `pipenv run` command does not support `--help`. It was disabled in #940 and there was no particular motivation referenced. I believe it deserves to be enabled back.
It is brought up by different members the core team that this is working "as intended" because pipenv forwards everything through to the subcommand, but it is not entirely true, e.g. `pipenv run` for example accepts all virtualenv creation parameters:
```
$ pipenv run --python=3 which python
Creating a virtualenv for this project...
Pipfile: …
```
> run: re-enable --help option

- pipenv/core.py
Closes #3544 
The error message is printed twice when the installation fails. It can be reproduced by `pipenv install requests==3.0`.
The patch fixes the change on the master branch, so no news is required.
> Eliminate duplicate error outputs.

- docs/index.rst
Re-hosted the GIF in `docs/index.rst` into a [public gist](https://gist.githubusercontent.com/jlusk/855d611bbcfa2b159839db73d07f6ce9).
Closes #3499 and #3666.
> change URL for GIF

- news/3807.bugfix.rst
- pipenv/vendor/pythonfinder/utils.py
- pipenv/vendor/requirementslib/models/setup_info.py
- pipenv/vendor/requirementslib/models/utils.py
- tasks/release.py
* Update pythonfinder, fix #3807 
* Update requirementslib.
* Update release script.
> Update vendor packages

- news/towncrier_template.rst
Add the missing whitespace between news text and issue number.
> Fix towncrier template

- azure-pipelines.yml
- news/3879.bugfix.rst
- pipenv/cli/command.py
- pipenv/core.py
- tests/integration/test_cli.py
- tests/integration/test_install_basic.py
Fix #3879 
Pass `--pre` and `--clear` to outdated
Add tests for the pre option.
> Pass lock options to outdated

- docs/basics.rst
- news/3885.trivial.rst
In the [_Specifying Versions_](https://github.com/pypa/pipenv/blob/master/docs/basics.rst#-specifying-versions-of-a-package) section of the [_Basics_](https://github.com/pypa/pipenv/blob/master/docs/basics.rst) documentation, there is a misleading code comment saying that _requests~=1.2_ is equivalent to _requests~=1.2.0_, which it isn’t. __~=1.2_ is equivalent to _>=1.2,<2.0_, but _~=1.2.0_ is equivalent to _>=1.2.0,<1.3.0_. Fixed by removing the comment.
Reported in a [comment](https://github.com/pypa/pipenv/commit/87551b9d45e6f208fabb36ecdd81ce6d49ca98cf#r34571192) to https://github.com/pypa/pipenv/commit/87551b9d45e6f208fabb36ecdd81ce6d49ca98cf. Accepted by @frostming.
Fixes #3884.
> Remove a misleading code comment from docs

- docs/cli.rst
- docs/index.rst
- news/3346.doc.rst
Currently pipenv's doc includes a fully CLI reference in the index. The CLI reference is very long and make page loading slowly.
This PR moves the CLI into separate part in docs and add link for it in the index. Check https://pipenv-fork.readthedocs.io/en/latest/index.html and https://pipenv-fork.readthedocs.io/en/latest/cli.html#pipenv for preview!
> Move CLI into separate part in docs

- README.md
- news/3911.doc.rst
This PR will fix #3911.
https://s3.amazonaws.com/media.kennethreitz.com/pipenv.gif seems to 404 (as described in issue #3911)
This PR changes the GIF's link to what is currently used in Pipenv's documentation (https://docs.pipenv.org/en/latest/)
> Fix link to GIF in README.md, add descriptive alt text

- docs/_templates/sidebarintro.html
- docs/_templates/sidebarlogo.html
As issued at https://github.com/pypa/pipenv/issues/3913, git-legit address is returning users to a poker site.
Update git-legit to correct new address.
> Sidebar: Update git-legit to new url address

- README.md
A few of the documentation links were incorrect when I was trying to install pipenv.  I believe they routed to an old website.
I updated the documentation links to point to the correct location.
> Update documentation links to take you to the correct website

- docs/basics.rst
Links to the PEP 440 articles in `docs/basics.rst` are broken.
Links are resolved as followed:
* `https://pipenv.readthedocs.io/en/latest/basics/<https://www.python.org/dev/peps/pep-0440/>`
* `https://www.python.org/dev/peps/pep-0440/#version-specifiers>`
Removed `<` and `>` characters from the links
> Fixed link references for PEP 440 in docs/basics.rst

- .github/ISSUE_TEMPLATE/Bug_report.md
Related to https://github.com/pypa/pipenv/issues/3958 - note that this is a minor fix, I'm sure there are other areas where domain names need to be updated including search results.
Going to the old URL https://docs.pipenv.org/en/latest/diagnose/ was giving an SSL error.
This can be fixed in two ways
1. Update URL to http://docs.pipenv.org/en/latest/diagnose/
1. Update URL to https://pipenv.kennethreitz.org/en/latest/diagnose/
I chose the second approach to match the project homepage URL.
Always consider opening an issue first to describe your problem, so we can discuss what is the best way to amend it.  Note that if you do not describe the goal of this …
> Update diagnose URL

- README.md
> pipenv is available on all Fedoras

- news/4045.bugfix.rst
- pipenv/environments.py
Pipenv ignores the `PIPENV_SPINNER` environment variable.
For some reason the spinner style was hardcoded to "bouncingBar" if the operating system is Windows and "dots" otherwise. This behaviour is preserved.
If the user sets the `PIPENV_SPINNER` environment variable then its value takes precedence.
> honor PIPENV_SPINNER environment variable

- pipenv/environment.py
This is not an issue, actually, but just a non-pythonic way to do something.
Since we should be using list comprehensions or generator expressions instead of a `filter` with lambda functions.
References:
- https://www.oreilly.com/library/view/python-cookbook/0596001673/ch01s11.html
- https://www.artima.com/weblogs/viewpost.jsp?thread=98196
I just changed the piece of code using `filter` to a generator expression. Really simple change.
> Use list comprehension instead of filter with lambda function

- .dockerignore
Just ignore all directories to speed up docker build.
Docker build is slow, because it loads everything in its context.
Add a .dockerignore file.
> Create .dockerignore to speedup docker build

- news/4018.feature.rst
- pipenv/core.py
- pipenv/environments.py
- pipenv/installers.py
#3875 adds support for asdf, much like the pyenv integration. And succeeds #3888 where I accidentally used a rebase and made some bad history.
The asdf and pyenv interfaces are much the same. So I just subclassed the pyenv runner. There may be room to more generally handle these kind of integrations, but I didn't want to make too dramatic of a change to the code base and give the smallest diff.
Open to any better solutions.
> ASDF Support

- docs/advanced.rst
- news/4100.doc.rst
More documentation for ``.env`` files
https://github.com/pypa/pipenv/issues/3610
Added in more documentation and also added documentation to upstream project https://github.com/theskumar/python-dotenv/pull/221
> Dotenv docs

- pipenv/patched/notpip/_internal/pep425tags.py
- tasks/vendoring/patches/patched/_post-pip-update-pep425tags.patch
This fixes runtime error on Linux ARM when calling:
```bash
pipenv install [package]
```
- version (current master, installed as work around for other problem in public version):
```bash
pi@rpi4:~/dev/pipenv $ pipenv --version
pipenv, version 2020.04.01.a1
```
This line check on ARM platform:
```py
if platform == "linux_armv7l" and not is_linux_armhf()
```
https://github.com/peterblazejewicz/pipenv/blob/f20c9dc688948db2b4dfd0a6a68398c4bf0c6254/pipenv/patched/notpip/_internal/pep425tags.py#L174
triggers a check using `os`, which was not imported, resulting
in runtime error.
Thanks!
Full stack trace:
```bash
pi@rpi4:~/dev/python-playground $ pipenv install
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Building requirements... …
```
> fix(pep425tags): missing `os` package import added

- README.md
- docs/advanced.rst
- news/4210.trivial.rst
- Remove bits about CC-BY-SA licensing
- Remove bits about using an embedded API key
- Add a little flair to the readme to acknowledge pyup
> Update documentation to reflect accurate pyup use

- docs/requirements.txt
Documentation (located under the `./docs` directory) build fails with "exception: No module named 'sphinxcontrib.spelling'" error.
sphinxcontrib-spelling was added by https://github.com/pypa/pipenv/commit/2f460a9128ee5c880dcbc52fd2b8de3fe393720a 3days ago.
Reproducing processes:
```
pip install -r docs/requirement.txt
cd docs
make html
```
Insert an entry of sphinxcontrib-spelling
> Lacking sphinxcontrib-spelling module

- news/3396.bugfix.rst
- news/4217.bugfix.rst
- pipenv/patched/piptools/utils.py
- pipenv/utils.py
- tasks/vendoring/patches/patched/piptools.patch
- tests/integration/test_lock.py
- Recursively resolve PEP 508 URLs in subdependencies
- Fix `piptools` cache storage of VCS dependencies as results
- Avoid saving VCS dependency versions to `Pipfile.lock`
- Fixes #3396
- Fixes #4217
Signed-off-by: Dan Ryan <dan.ryan@canonical.com>
> Fix recursive PEP 508 VCS resolution

- news/4229.bugfix.rst
- pipenv/core.py
Fix #4229 
Fixed a hidden bug that `reverse_deps` get overridden in each run of the loop.
Also normalize the package name in `reverse_deps`.
> Fix the broken update --outdated handler

- news/3057.feature.rst
- pipenv/core.py
- pipenv/environment.py
- tasks/vendoring/patches/vendor/vistir-imports.patch
- Skip satisfied dependencies in the environment during install
by checking whether the constraint of a specifier is satisfied
- If there is no specifier and a dependency is installed, assume it
is satisfied
- For editable dependencies, if the dependency in the environment is
an egg link and points at the same path as the given dep, assume
it is satisfied
- TODO: Add test
- Fixes #3057 
- Fixes #3506
> Skip satisfied dependencies during installation

- news/3506.feature.rst
- news/4220.bugfix.rst
- pipenv/core.py
- pipenv/patched/crayons.py
- pipenv/project.py
- pipenv/vendor/vendor.txt
- pipenv/vendor/vistir/misc.py
- tasks/vendoring/patches/patched/crayons.patch
- Respect `--system` when it is supplied during install
- Fixes #4220
> Load the pip version from the correct prefix

- news/4267.vendor.rst
- pipenv/vendor/passa/models/projects.py
- pipenv/vendor/pythonfinder/models/mixins.py
- pipenv/vendor/pythonfinder/models/path.py
- pipenv/vendor/pythonfinder/models/python.py
- pipenv/vendor/pythonfinder/models/windows.py
- pipenv/vendor/pythonfinder/utils.py
- pipenv/vendor/requirementslib/models/dependencies.py
- pipenv/vendor/requirementslib/models/lockfile.py
- pipenv/vendor/requirementslib/models/markers.py
- pipenv/vendor/requirementslib/models/metadata.py
- pipenv/vendor/requirementslib/models/pipfile.py
- pipenv/vendor/requirementslib/models/project.py
- pipenv/vendor/requirementslib/models/requirements.py
- pipenv/vendor/requirementslib/models/resolvers.py
- pipenv/vendor/requirementslib/models/setup_info.py
- pipenv/vendor/requirementslib/models/url.py
- pipenv/vendor/requirementslib/models/vcs.py
- tasks/vendoring/patches/vendor/update-attrs-import-path.patch
The `attrs` module is vendored in pipenv, but when the package is installed on the system, the system version is imported first, and fails if the version is different.
We found this issue in Fedora, where we have python-attrs-19.1.0, which causes a failure because version 19.3.0 is expected (and vendored):
>   @attr.s(slots=True, eq=True, hash=True)
class SetupInfo(object):
E   TypeError: attrs() got an unexpected keyword argument 'eq'
pipenv/vendor/requirementslib/models/setup_info.py:1341: TypeError
I've implemented a patch in Fedora that instead of `import attr` uses `from pipenv.vendor import attr`. I think it be useful upstream too, so I opened this PR.
News fragment is probably not necessary, but I can provide one if prompted.
> Make sure to import the vendored attrs

- RELEASING.md
Moving @techalchemy's notes from https://demo.codimd.org/wY3hW3f2SuGXBfd0ZsHsag to merge them into the release process doc.
Signed-off-by: Sumana Harihareswara <sh@changeset.nyc>
Towards #4130.
> Update release process to reflect Dan's notes

- news/4279.trivial.rst
- tests/integration/test_install_uri.py
Remove expectation of `version` key in `test_ssh_vcs_install` to
stop it from failing.
Mirrors similar change to `test_git_vcs_install` in
243b4fd0df552b7430fbaa5dadbaa4d7b322127f.
Fixes #4279.
Mirror 243b4fd0df552b7430fbaa5dadbaa4d7b322127f.
> #4279: Stop test_ssh_vcs_install from failing

- news/4278.bugfix.rst
- pipenv/utils.py
- tests/integration/test_lock.py
Fixes bug introduced by 552d1274eacbd04c61f46f639bd967d294f25e6a,
which activated the (unused) changes made much earlier in
a08a2da52488fa31b1e74b22211f383566fef16b.
Fixes #4278.
`pipenv.utils.get_locked_dep` uses the version specified in the Pipfile if it starts with `==` without checking whether that version is a wildcard match.
Do not use the version in the Pipfile if it is a wildcard match.
> #4278: Don't pin wildcard versions in lockfile

- news/4273.bugfix.rst
- pipenv/core.py
- pipenv/project.py
#3386 causes some regression issue #4273 
This PR reverts some of the changes of #3386, don't check against root directory but fix the `self.name` reference in `create_pipfile()`.
Sorry for the trouble.
> Don't check against root directory

- news/4292.bugfix.rst
- news/4292.vendor.rst
- pipenv/vendor/requirementslib/__init__.py
- pipenv/vendor/requirementslib/models/setup_info.py
- pipenv/vendor/vendor.txt
- Upstream update to parse package names from unresolveable function
calls in `setup.py`
- Fixes #4292
Signed-off-by: Dan Ryan <dan.ryan@canonical.com>
> Parse package names from functions in setup.py

- Makefile
- news/4271.bugfix.rst
- news/4273.bugfix.rst
- news/4274.bugfix.rst
- news/4276.bugfix.rst
- news/4279.trivial.rst
- news/4295.bugfix.rst
- news/4296.bugfix.rst
- news/4298.bugfix.rst
- news/4302.vendor.rst
- pipenv/cli/command.py
- pipenv/cli/options.py
- pipenv/core.py
- pipenv/environment.py
- pipenv/installers.py
- pipenv/project.py
- pipenv/utils.py
Clean up linter errors and add missing news items
- Clean up linter errors
- Fix py2 compatibility issues in `installers`
- Fix whitespace issues, unused imports
- Add a bunch of type hints
- Add missing news entries
- Update news fragments
- Add makefile script parts
> Linting cleanup, compatibility fixes, missing news entries

- news/4305.bugfix.rst
- news/4305.trivial.rst
- pipenv/environments.py
- pipenv/installers.py
Fixes bug #4305 introduced in c23e57b4824e0553ea2e91a2a6c59bff811aac39 which no longer identifies if the tty session is interactive. Which prevents pipenv from using pyenv to install a version of python that doesn't exist in pyenv
When this commit migrated to use [vistir._isatty](https://github.com/sarugaku/vistir/blob/7944195b9ab32375e3706d97e2eb36a0aeca772d/src/vistir/misc.py#L1092) it bypassed `os.isatty` which supports `fileno` while `vistir._isatty` does not. Also since `vistir._isatty` swallows all exceptions we no longer need to catch `UnsupportedOperation` 
Instead of passing in the `sys.stdout.fileno()` to `vistir._isatty` pass in the stream
> Fixes bug 4305, which no prompts to installs a pyenv python version that doesn't exist

- news/4316.bugfix.rst
- pipenv/environments.py
Hey there 👋 
This is my attempted fix for #4316 . The details should be in there. Let's keep all conversations around the issue there and put any feedback on the code here 😄
I removed a variable that seemed to over eagerly flag anything as a virtual environment in my local setup. It worked on my machine but I'm not sure about others 🙈
> Stop using PYVENV_LAUNCHER env variable when detecting venvs

- news/4315.bugfix.rst
- pipenv/core.py
- pipenv/environment.py
- pipenv/project.py
> Correctly populate the system python path

- news/4321.bugfix.rst
- pipenv/core.py
- tests/integration/test_uninstall.py
> Correct the exception to PipenvUsageError

- docs/_templates/sidebarlogo.html
Outdated link that leads to a placeholder site.
Remove the link to the project that apparently no longer exists.
> Remove outdated link that points to placeholder site

- news/4335.bugfix.rst
- news/4342.bugfix.rst
- news/4385.vendor.rst
- pipenv/vendor/requirementslib/__init__.py
- pipenv/vendor/requirementslib/models/requirements.py
- pipenv/vendor/requirementslib/models/setup_info.py
- pipenv/vendor/vendor.txt
- tasks/vendoring/__init__.py
- tasks/vendoring/patches/vendor/passa-close-session.patch
- tasks/vendoring/patches/vendor/update-attrs-import-path.patch
> Update requirementslib to 1.5.12

- news/4403.bugfix.rst
- news/4421.vendor.rst
- pipenv/core.py
- pipenv/vendor/pip_shims/__init__.py
- pipenv/vendor/pip_shims/compat.py
- pipenv/vendor/pip_shims/models.py
- pipenv/vendor/requirementslib/__init__.py
- pipenv/vendor/requirementslib/models/setup_info.py
- pipenv/vendor/requirementslib/models/vcs.py
- pipenv/vendor/requirementslib/utils.py
- pipenv/vendor/vendor.txt
- tasks/vendoring/patches/vendor/pip_shims_module_names.patch
- tests/integration/test_install_uri.py
> Do not copy project tree

- news/4386.bugfix.rst
- news/4441.feature.rst
- news/4443.feature.rst
- pipenv/cli/options.py
- pipenv/core.py
- pipenv/resolver.py
Change to a more robust constraint validation method to detect if there are any conflicts between constraints.
Fix #4386
> Fix a bug that non-wheel file requirements can be resolved successfully

- README.md
- docs/install.rst
- news/4013.doc.rst
> Discourage homebrew installation in doc

- news/4379.bugfix.rst
- pipenv/project.py
#4379 
Handle python major and minor version correctly in create_pipfile function.
The previous code only handles one digit of the minor version. This change handles the major minor version correctly.
> handle python major and minor version correctly in create_pipfile

- news/4225.bugfix.rst
- pipenv/project.py
Fixing #4225
If PIPENV_PYTHON is a path, only the last bit of the path gets included in the suffix, thus making sure that the environment name contains no incorrect characters. If it's a python version, the suffix is the version as previously intended. If PIPENV_PYTHON is not set, there is no suffix to the environment name.
I couldn't figure out an appropriate way to write tests for this since there don't seem to be tests created for the original function and new tests would depend on my pyenv setup, but if anyone knows how to test this effectively please let me know.
> Fix #4225 - virtualenv name when PIPENV_PYTHON set to filepath

- news/4480.bugfix.rst
- news/4480.vendor.rst
- pipenv/vendor/requirementslib/__init__.py
- pipenv/vendor/requirementslib/models/setup_info.py
- pipenv/vendor/vendor.txt
> Bugfix: editable packages matched the wrong metadata directory

- news/4089.bugfix.rst
- pipenv/vendor/requirementslib/models/requirements.py
- pipenv/vendor/requirementslib/models/setup_info.py
- pipenv/vendor/vendor.txt
> Bugfix: don't unquote file URL

- news/4387.bugfix.rst
- pipenv/environment.py
> Bugfix/4387 VCS dependencies always satisfy even if the ref has changed

- news/4523.bugfix.rst
- pipenv/cli/command.py
- pipenv/core.py
Fix #4523 
Improve the output of `pipenv scripts`
```bash
$ pipenv scripts
Command  Script
-------  ------
mode1    echo 1
mode2    echo 2
mode3    echo 3
```
> Fix the output of ``pipenv scripts`` under Windows platform

- news/4346.feature.rst
- pipenv/utils.py
- tests/integration/test_lock.py
> Show waring about what happened when a dep is skipped

- news/4527.bugfix.rst
- pipenv/resolver.py
- tests/integration/test_lock.py
The resolver misses the argument `dev`.
Fix #4527
> Bugfix: resolver takes the wrong section to validate constraints

- docs/diagnose.rst
- news/4534.doc.rst
Fixes #4534 
Fixes the issue by using the absolute path to the desired Python version, rather than relying on the shim.
> Update pyenv docs to avoid using shim

- docs/index.rst
Partially and temporarily addresses #1839 while we fix the underlying problem and investigate the search index. Users will temporarily only be able to use the search box in the sidebar.
Please revert this once the index is fixed.
Signed-off-by: Sumana Harihareswara <sh@changeset.nyc>
#1839
> Remove search link on main page of RTD documentation

- news/4549.bugfix.rst
- pipenv/environment.py
- pipenv/resolver.py
- tasks/vendoring/__init__.py
> Fix #4549: Ignore incompatibilities when resolve dist

- news/4538.bugfix.rst
- pipenv/project.py
- pipenv/shells.py
Fixes #4538. 
Followed the recommended solution which fixed the issue for when PIPENV_IN_VENV is False. Added further sanitation to pipenv/shells.py to fix the issue for when PIPENV_IN_VENV is True as well.
> Fix #4538 - Improve virtualenv path sanitazation to allow for activation

- news/4141.bugfix.rst
- pipenv/project.py
- tests/integration/test_project.py
Issue #4141 --skip-lock: tomlkit.exceptions.NonExistentKey: 'Key "source" does not exist.'
Following the tip from @uranusjr, I set the sources to [DEFAULT_SOURCE] if the section [Sources] does not exist in PIPFILE.
> Fix for: --skip-lock: tomlkit.exceptions.NonExistentKey: 'Key "source" does not exist

- news/4602.bugfix.rst
- pipenv/pep508checker.py
Fix https://github.com/pypa/pipenv/issues/4602
This includes all characters up to the second `"."` (instead of just the first 3 characters),
which should correct version-handling for Python 3.10.
> Correct python_version in pep508checker.py

- .github/workflows/ci.yaml
- azure-pipelines.yml
PIP dropped Python 2 support https://github.com/pypa/pip/issues/6148, therefore pipenv needs to drop Python 2 and make performance improvements.
I would like to volunteer sometime to drop Python 2.
Let's drop Python 2 from CI, then we can do other cleanups safely.
> drop python2 from CI

- news/4615.bugfix.rst
- pipenv/project.py
- pipenv/shells.py
Fixes #4615.
Related to #4538.
Added proper character escaping for `()` and `[]` characters in virtualenv paths, by modifying the regex in `_get_activate_script()` in `pipenv/shells.py`.
Also improved sanitization in `_sanitize()` of `Project` class in `pipenv/project.py` to turn `()` and `[]` characters into `_`.
These changes allows virtualenv paths with such characters to properly activate.
> Fix #4615 - Improve sanitization to allow virtualenv paths with () and [] characters to activate

- news/4642.bugfix.rst
- pipenv/utils.py
#4642 
pipenv lock --pre doesn't actually include prerelease dependencies
Used the already existing self.pre variable to append --pre to a built command that ultimately results in prerelease dependencies being included in the locking process. This seems to be consistent with conventions at least within that file, and doesn't require additional fields to be defined.
> 4642 fix pipenv lock --pre doesn't include prerelease dependencies

- docs/basics.rst
> What is the thing you want to fix? Is it associated with an issue on GitHub? Please mention it.
Documentation for VCS installation was missing `#egg=` for one URL.
> How does this pull request fix your problem? Did you consider any alternatives? Why is this the *best* solution, in your opinion?
Adds the missing `#egg=` for the git/ssh VCS URL.
> Docs: add missing #egg fragment to VCS URL

- README.md
The readme doesn't have the command to install on Windows. 
Added the command to install on Windows to the readme.
> Windows install command

- pipenv/vendor/pipreqs/pipreqs.py
The PR is only a tiny code refactoration which is intented to remove what I use to call 'avoidable indexer iterator'.
I just changed two lines of code, turning two operations on this model:
>[imports[i]["name"] for i in range(len(imports))]
To this model:
>[i["name"] for i in imports]
With that we are calling two less methods (range and len) and avoiding the use of the direct indexer imports[i] and made it easier to read.
Thanks.
> Small refactoration removing two avoidable indexer iterator

- pipenv/cli/command.py
- pipenv/cli/options.py
In the new version of click, if an option has no type and a default value is of type bool, the default type is bool and the required value for the option is also bool which is not correct for options like --code, --requirements, or --python.
Click 7:
```
-c, --code TEXT                 Install packages automatically discovered
-e, --editable TEXT             An editable Python package URL or path,
-r, --requirements TEXT         Import a requirements.txt file.
--extra-index-url TEXT          URLs to the extra PyPI compatible indexes to
-i, --index TEXT                Target PyPI-compatible package index url.
--python TEXT                   Specify which version of Python virtualenv
--pypi-mirror TEXT              Specify a PyPI mirror.
```
Click 8:
```
-c, --code BOOLEAN …
```
> Fix compatibility with click version 8

- .azure-pipelines/steps/run-tests-linux.yml
- .azure-pipelines/steps/run-tests-windows.yml
- .github/workflows/ci.yaml
- pipenv/cli/command.py
- pipenv/cli/options.py
- pipenv/core.py
- pipenv/environment.py
- pipenv/environments.py
- pipenv/exceptions.py
- pipenv/help.py
- pipenv/installers.py
- pipenv/project.py
- pipenv/resolver.py
- pipenv/shells.py
- pipenv/utils.py
- tests/conftest.py
- tests/integration/conftest.py
- tests/integration/test_cli.py
- tests/integration/test_install_markers.py
- tests/integration/test_lock.py
- tests/integration/test_project.py
- tests/integration/test_run.py
- tests/integration/test_uninstall.py
- tests/unit/test_core.py
- tests/unit/test_help.py
This is an attempt to solve #4746
> Refactor: replace shared states with create-on-demand

- news/4760.feature.rst
- pipenv/core.py
- pipenv/utils.py
See #4760.
In order to improve the logging, this commit shell-quotes each token before joining the results with spaces. This means that users should be able to copy and paste logged commands and run them using any common shell without issue, including when paths contain spaces or other special characters.
> Quote tokens when logging `pip` commands

- pipenv/core.py
Currently, `pipenv sync --system` would create a virtualenv, which should not be created by design.
Pass `system` to sub function.
> fix: do_sync should pass system/clear

- README.md
- news/4792.doc.rst
the install commands in the readme are made more difficult to copy because of the `$` and `#` prefixes
removed the prefixes so now you can easily copy and paste the command
> remove prefixes on install commands for easy copy/pasting

- docs/install.rst
> What is the thing you want to fix? Is it associated with an issue on GitHub? Please mention it.
In [Isolated Installation of Pipenv with Pipx](https://pipenv.pypa.io/en/latest/install/#isolated-installation-of-pipenv-with-pipx) section, link to Pipx's home page is missing. Since this is a minor changes in documentation, so there is no need for an issue on the Issue Tracker.
> How does this pull request fix your problem? Did you consider any alternatives? Why is this the *best* solution, in your opinion?
This merge request fix the problem, by adding the missing link.
> [docs] Add missing link of Pipx's home page

- pipenv/cli/command.py
- pipenv/core.py
As described in issue #4788 , `--py` option returns incorrect return code if no virtualenv is found. 
```
bash-3.2$ pipenv --version
pipenv, version 2021.5.29
bash-3.2$ cd / && pipenv --py
No virtualenv has been created for this project (/) yet!
bash-3.2$ echo $?
0
```
pass ctx to `do_py` and abort if virtualenv is not found.  The output is like this.
```
root@61d7aec9b3fc:/pipenv# python pipenv --py
No virtualenv has been created for this project (/pipenv) yet!
Aborted!
root@61d7aec9b3fc:/pipenv# echo $?
1
```
> Fixes #4788: incorrect returncode

- docs/basics.rst
The pre-existing basic usage documentation says that "pipenv lock -r" would include hashes in requirements.txt, this is not the behaviour i observe - i didn't find any issue around this - i guess it's either a bug or just the documentation is wrong.
Digging through the code it looks reasonably plain that it just does not include hashes in its output - there is no logic or option there:
https://github.com/pypa/pipenv/blob/master/pipenv/core.py#L849
> Fix basic usage docs to reflect lock -r behaviour

- docs/diagnose.rst
Suggested in https://github.com/pypa/pipenv/issues/2910#issuecomment-426484374.
I took the easy way out here by removing these docs altogether. If someone wants to go ahead and document the `--fancy` approach, it would be great. I don't know so much of how it works myself.
> diagnose.rst: Remove outdated -c docs

- news/4790.bugfix.rst
- pipenv/project.py
- tests/integration/test_dot_venv.py
fix issue #4790 
This is to prevent an user from choosing own workon home as the virtual environment or deleting all virtual environments accidentally under the workon dir. pipenv ignores the content with this change, so that it uses project name base virtual environment If an empty .venv is set in root.
> Fixes #4790: behaving as no .venv if .venv is in project root and empty

- pipenv/core.py
- introduced in #4779
- fixes #4835
> fix: set `PIPENV_USE_SYSTEM` when sync with `--system`

- CHANGELOG.rst
- Based on https://github.com/pypa/pipenv/issues/4261#issuecomment-962948608, 3.5 support is dropped, not 3.6.
- Fix typo
- Resolves #4844
> Fix 2021.11.5 support drop version notice from 3.6 to 3.5

- news/4852.bugfix.rst
- pipenv/environments.py
> Don't use sys.executable when inside a venv

- pipenv/core.py
**The issue**
- Duplicate parentheses show when virtualenv is activated. It is happening because of a recent update in the virtualenv package(v20.10.0). In this version, the activated virtualenv prompt is now always wrapped in parentheses. This affects venvs created with the --prompt attribute, and matches virtualenv’s behaviour on par with venv.
https://virtualenv.pypa.io/en/latest/changelog.html#v20-10-0-2021-11-01
**The fix**
- Removed parentheses when virtualenv is created.
Previous behaviour:
```
$ pwd
/code/myproject
$ pipenv shell
((myproject) )$ 
```
New behaviour:
```
$ pipenv shell
(myproject) $
```
> duplicate parentheses removed

- news/4899.bugfix.rst
- pipenv/core.py
- pipenv/patched/notpip/_internal/build_env.py
- pipenv/resolver.py
- pipenv/utils.py
- tasks/vendoring/patches/patched/_post_pip_import.patch
- tests/integration/test_install_basic.py
- tests/unit/test_utils.py
- Global options such as `--index-url`, `--extra-index-url` must be on their own lines
- Text following a `#` is ignored as comment string
> Fix the index parsing to reject illegal requirements

- pipenv/utils.py
Additional fix for #4899
Previously, due to default behavior of ArgumentParser, global --index-url,
--extra-index-url, and --trusted-host options in requirements files could be
abbreviated (e.g. "--index" == "--index-url"). As a result, unexpected
behavior could occur during processing of a requirements file with these
shortened option names when using Pipenv, which could be exploited by a
malicious actor to surreptitiously insert pip options using non-obvious
abbreviations.
For example, adding a line with "--t example.com" to the
requirements file would cause Pipenv to treat example.com as trusted, even
when example.com presents an invalid TLS certificate.
This commit disables support for abbreviated options in the ArgumentParser,
to align Pipenv's behavior when parsing global options in …
> disallow abbreviated forms of full option names

- news/4885.bugfix.rst
- pipenv/utils.py
- pipenv/vendor/pip_shims/compat.py
- tests/integration/test_lock.py
This fixes https://github.com/pypa/pipenv/issues/4885
> Use a PackageFinder with `ignore_compatibility` when collecting hashes

- MANIFEST.in
This was probably due to pipenv relying on Jinja2 in the
past.
However, Jinja2 was removed in 11229406ba8ac966bd4def4612847317c4d82455
> Remove leftover include of jinja2 files

- docs/basics.rst
This is now the correct path for running the application code.
> Fix typo in docker documnetation

- news/4944.bugfix.mdB
- pipenv/environments.py
`CI` can sometimes be set to `false` or a non-truthy value, in which case, `PIPENV_IS_CI` should not assume it is always true just because it exists.
check the actual values of the environment variable, instead of just the existence of the name in the environment
> improve detection of CI

- docs/advanced.rst
- news/4893.feature.rst
- pipenv/cli/command.py
- tests/integration/test_cli.py
This a proposal to have a new command added: `pipenv verify`
The aim is to be able to verify the hash in the Pipfile is up to date, or whether it needs updating.
The feature can be very useful within the CI/CD pipelines where the Pipfile.lock is a part of the repository and it needs to be up to date. The command can make it quick to run a check this is the case.
The PR is related to an open issue https://github.com/pypa/pipenv/issues/4893
> New command: verify Pipfile.lock hash is up to date

- news/4525.bugfix.rst
- pipenv/installers.py
This fixes https://github.com/pypa/pipenv/issues/4525
This issue has two parts: 
1. How `pipenv` calls `pipenv-win.bat` as mentioned by @uranusjr [here](https://github.com/pypa/pipenv/issues/4525#issuecomment-723733593).
2. `pyenv-win` not supporting the `-s/--skip-existing` flags while `pyenv` does, as mentioned by @i3v [here](https://github.com/pypa/pipenv/issues/4525#issuecomment-829641410). Luckily this is done automatically in `pyenv-win`, and it does not ask for user input which I guess it's why it was added in the first place. I initially opened a [PR](https://github.com/pyenv-win/pyenv-win/pull/350) in `pyenv-win` to add support for it but then realized more differences between the original vs the Windows versions which made me finally close it and go for this path.
3. (extra) …
> Fixes installing versions with pyenv-win

- pipenv/utils.py
- tests/unit/test_utils_windows_executable.py
In debugging other Windows related pipenv issues, I had to patch this locally to get windows to find pyenv which was already on the PATH.  This combined with the latest fix:  https://github.com/pypa/pipenv/pull/4929 allowed pipenv to finally use pyenv-win on windows successfully to install other versions of python beyond what I had installed at a system level or manually using pyenv-win.  
Pipenv should be able to use the pyenv already on the path in windows, instead of printing:
```
$ pipenv sync
Warning: Python 3.9 was not found on your system...
Neither 'pyenv' nor 'asdf' could be found to install Python.
You can specify specific versions of Python with:
$ pipenv --python path\to\python
``` …
> Windows: locate pyenv from PATH correctly

- news/4797.feature.rst
- pipenv/environments.py
The value of `PIPENV_SKIP_LOCK` is always False. This has been discussed in previous issues (#2200 and #3332) with no resolution. 
`PIPENV_SKIP_LOCK` to consider the value of the environment variable `PIPENV_SKIP_LOCK`. 
This is useful to large project as it enables the environment variable `PIPENV_SKIP_LOCK` to control the locking behavior. 
Default behavior is not changed, still False.
> Use PIPENV_SKIP_LOCK environment variable

- README.md
- docs/advanced.rst
- docs/basics.rst
- docs/index.rst
- news/4938.bugfix.rst
- pipenv/cli/command.py
- pipenv/cli/options.py
- pipenv/core.py
- pipenv/environments.py
Remove mention of the --two flag and python2
https://github.com/pypa/pipenv/issues/4938
Seems it was mostly removed already.  This tries to clean up remaining references.
> Remove mention of the --two flag and python2

- news/4975.bugfix.rst
- pipenv/core.py
- tests/integration/test_cli.py
- tests/integration/test_lock.py
- tests/integration/test_project.py
- tests/integration/test_run.py
Ensure that dot env variables are actually in the real environment so they can be exapnded by os.path.expandvars
https://github.com/pypa/pipenv/issues/4975
https://github.com/pypa/pipenv/issues/3901
The problem is that in the current code we are loading the .env variables into a copy of the environment which is not available to `os.path.expandvars` so they are always treated as a string.  This fixes that by applying it to the environment before copying it.  Also refactor away some of the complexity of `load_dot_env`.
> Fix for expanding dot env variables in scripts

- pipenv/core.py
**https://github.com/pypa/pipenv/issues/2222**
**https://github.com/pypa/pipenv/issues/2870**
How does this pull request fix your problem? Did you consider any alternatives? Why is this the *best* …
> display the directory path of the found requirements.txt file

- news/4637.bugfix.rst
- pipenv/core.py
- pipenv/patched/notpip/_internal/index/collector.py
- pipenv/patched/notpip/_internal/models/search_scope.py
- pipenv/utils.py
- tasks/vendoring/patches/patched/pip_index_safety.patch
Code changes that fix the indexes not being respected.   Acknowledged that this modifies code in pip, and so I will need extra considerations on how to proceed  I have opened a PR against Pip as well (https://github.com/pypa/pip/pull/10964) to propose my modifications of pip from here.   Yet without this logic, there is no way to enforce the index specifications are abided by during resolution and installation.   After several iterations of trying to understand this code and how to fix it, it feels like the `LinkCollector`''s `SearchScope` should have the knowledge it needs to return the right indexes at the right times.
Pipenv Lock (Or Install) Does Not Respect Index Specified For A Package  https://github.com/pypa/pipenv/issues/4637
Without this or similar logic, there is no way to …
> Fix for: Pipenv Does Not Respect Index Specified For A Package

- news/5002.bugfix.rst
- pipenv/core.py
- tests/integration/test_install_basic.py
https://github.com/pypa/pipenv/issues/5002
Check the indexes safely, the problem will still be that if you don't name an index, then it is just an extra source, but if you call out the name of an index it won't be able to resolve to an index that is unamed, and that should be fine.
> Fix the assumption that all sources are named.

- news/5008.vendor.rst
- pipenv/patched/notpip/COPYING
- pipenv/patched/notpip/LICENSE
- pipenv/patched/notpip/LICENSE.APACHE
- pipenv/patched/notpip/LICENSE.BSD
- pipenv/patched/notpip/LICENSE.md
- pipenv/patched/notpip/LICENSE.txt
- pipenv/patched/notpip/__init__.py
- pipenv/patched/notpip/_internal/locations/__init__.py
- pipenv/patched/notpip/_internal/locations/_distutils.py
- pipenv/patched/notpip/_internal/locations/_sysconfig.py
- pipenv/patched/notpip/_internal/models/link.py
- pipenv/patched/notpip/_internal/req/req_install.py
- pipenv/patched/notpip/appdirs.LICENSE.txt
- pipenv/patched/notpip/distro.LICENSE
- pipenv/patched/notpip/pyparsing.LICENSE
- pipenv/patched/notpip/six.LICENSE
- pipenv/patched/patched.txt
- pipenv/vendor/attr/LICENSE
- pipenv/vendor/dotenv/LICENSE
- pipenv/vendor/packaging/LICENSE.APACHE
- pipenv/vendor/packaging/LICENSE.BSD
- pipenv/vendor/pythonfinder/LICENSE
https://github.com/pypa/pipenv/issues/5008
This vendors in `pip==21.2.4` to fix a bug in one of the last releases that will support py 3.6
> Vendor in pip 21.2.4 release (from pip 21.2.2 prior).

- news/5010.bugfix.md
- pipenv/core.py
When the output is quieted, pipenv no longer loads the `.env` file
Load .env but only print the message if quiet is False
> Bugfix: Not loading .env when quiet

- .env
- .github/workflows/ci.yaml
- news/5010.bugfix.md
- news/5011.trivial.rst
- news/5019.bugfix.rst
- pipenv/core.py
- pipenv/vendor/requirementslib/models/setup_info.py
- setup.py
- tasks/vendoring/patches/vendor/requirementslib-subdir-fix.patch
- tests/integration/test_cli.py
- tests/integration/test_lock.py
- tests/integration/test_run.py
It would appear that potentially a recent change to setuptools revealed that we weren't actually passing in the subdirectory properly to generate the pep517 wheels, and that was revealed ~3 days ago when the CI started failing on a change that was merged in but had passed the CI the day before. 
Fixes #5019
Fixes #5014
> Subdirectory vcs installs are never passing the subdirectory in requirementslib which is now required by setuptools

- news/5023.bugfix.rst
- pipenv/utils/resolver.py
Fixes: #5023 
Re-organize the logic and fallback to generating the hash from the link, if pypi is not applicable, and there are no applicable candidates.  This also applies the index restrictions to the hash finder so it too can find the right hashes.
```
{
"_meta": {
"hash": {
"sha256": "dd84b90e2afa892488dc59130dc48898573afeee5ba3aa45d8c64c54be6be39c"
},
"pipfile-spec": 6,
"requires": {
"python_version": "3.10"
},
"sources": [
{
"name": "pypi",
"url": "https://pypi.org/simple",
"verify_ssl": true
},
{
"name": "downloadpytorch",
"url": "https://download.pytorch.org/whl/cu113/",
"verify_ssl": true
},
{
"name": "downloadpytorch-390",
"url": "https://download.pytorch.org/whl/",
"verify_ssl": true
}
]
},
"default": {
"torch": {
"index": "downloadpytorch-390",
"version": "==1.11.0+cu113"
}, …
```
> Issue 5023 Fix hash link generation

- docs/advanced.rst
- news/5022.doc.rst
- news/5022.removal.rst
- news/5022.trivial.rst
- pipenv/cli/command.py
- pipenv/cli/options.py
- pipenv/core.py
- pipenv/patched/notpip/_internal/cli/req_command.py
- pipenv/patched/notpip/_internal/req/req_file.py
- pipenv/utils/resolver.py
The primary goal of this PR is to improve the documentation around use of additional indexes and what it means to be the default index.
Additionally, since we would be declining#5028 due to the logical complexity of supporting that approach and the security concerns--I capture a trivial refactor change from that PR to re-use a util we already have for determining if an index is pypi.
Fixes #5028
Fixes #5022 
Fixes #5021 
- How do we deprecate something in the project?
- Are there additional options we want to support to make life nicer?
- Additional documentation that would be useful?
> Improve documentation around index restrictions

- news/2763.bugfix.rst
- news/4992.process.rst
- pipenv/environments.py
- pipenv/project.py
- tests/integration/test_dot_venv.py
- tests/integration/test_install_basic.py
- tests/integration/test_pipenv.py
Allow PIPENV_VENV_IN_PROJECT to be read in as None, and ensure if it is set to False that it does not use .venv directory.
Fixes  #2763 
The variable was being cast to a boolean so it would be False even if it was not set, this allows a user to explicitly set the variable to a non-truthy value and ensure that the .venv directory gets ignored.
> More granular control over PIPENV_VENV_IN_PROJECT variable.

- .github/workflows/ci.yaml
- docs/advanced.rst
- docs/conf.py
- docs/requirements.txt
- news/4778.doc.rst
Actually build sphinx docs locally and see if what I did for formatting here made the most sense: https://github.com/pypa/pipenv/pull/5029/files
I found a few warnings to clean up and wanted to improve the consistency and formatting of the note.
Also Fix for the CLI docs not generating.
Fixes #4778 
I figure this change is covered by the other news fragments added and issues we resolved.
> sphinx formatting change and fix CLI docs

- .github/workflows/ci.yaml
- Makefile
- Pipfile
- Pipfile.lock
- RELEASING.md
- news/4996.process.rst
- pipenv/patched/README.md
- pipenv/project.py
- pipenv/utils/dependencies.py
- pipenv/utils/resolver.py
- pipenv/vendor/requirementslib/models/cache.py
- run-tests.sh
- setup.cfg
- tasks/vendoring/__init__.py
#4996 
We don't actually vendor in pip-tools and we have a laundry list of TODOs in this method `_build_package_list` and I think this correctly addresses them.  We end up dropping `is_installable_file` but based on my grepping, that method exists in requirementslib as well so I think the code still accounts for `is_installable_file` and we have tests that install from files, so I think its a non-issue.
> Added pytest-cov and addressed outdated references to pip-tools

- .github/workflows/ci.yaml
- Makefile
- news/5061.process.rst
This PR suggests a couple of improvements for the build pipeline:
1) We only lint the code once (as compared to previous situation where linting was run on all architectures).
2) Linting is a prerequisite for all other jobs which run in parallel if it succeeds.
Also, this PR adds a Makefile target for running the vendoring stage locally.
This PR is cherry-picking of the CI parts from #5059.
> CI improvements

- news/5062.removal.rst
- pipenv/__init__.py
- pipenv/core.py
- pipenv/environment.py
- pipenv/environments.py
- pipenv/utils/dependencies.py
- pipenv/utils/resolver.py
- pipenv/utils/spinner.py
- tests/integration/conftest.py
This function was all about compatability of py2-py3.3 versions.
Later versions don't need it.
This PR replaces #5059 as I did too much havoc there with all the CI suggestions.
> Removed usage of fs_str from vistir

- docs/advanced.rst
- news/4706.bugfix.rst
- pipenv/utils/resolver.py
this is required if you want to e.g. use a keyring to authenticate
against Google Artifact Registry. fixes https://github.com/pypa/pipenv/issues/4706
How does this pull request fix your problem? Did you …
> [fix] allow the user to overwrite the `no_input` flag to pip

- news/5065.removal.rst
- setup.py
We missed python 3.6 support in the metadata.
Fixes: #5065
Drops the support fully.
> Issue 5056 setupy 36

- pipenv/core.py
- pipenv/environment.py
- pipenv/utils/resolver.py
- pipenv/utils/shell.py
* Removed usage of vistir.compat.JSONDecodeError
`json.JSONDecodeError` is Python 3.6+
* Removed vistir.path.rmtree in favour of shutil.rmtree
Should work, but we might have to revert this.
> Remove some more vistir usage

- .github/workflows/ci.yaml
- pipenv/exceptions.py
As discussed, we should remove crayons in favor of `click.echo` and `click.secho`.
`click` has a large user base and thus a better support across all major platform.
This PR is a test balloon. If it is merged, it allows us to carefully test that no drastic UI changes have
been introduced, without completely removing crayons.
Once we completely removed crayons, it's easy to fix #5057.
> Drop crayons in exceptions.py

- .github/workflows/ci.yaml
- news/5078.removal.rst
- pipenv/core.py
- pipenv/environment.py
- pipenv/resolver.py
- pipenv/shells.py
- pipenv/utils/dependencies.py
- pipenv/utils/resolver.py
Moving to Python version 3.7+ allows us to remove more usage of vistir.
Eventually we can completely drop it, but I prefer doing this gradually instead of a giant PR.
Also, I am not done yet. Will add 2-3 more commits, and we'll continue chopping this vistir with b[i,y]te size steps.
Pun intended :-)
> More vistir dropping

- news/5081.vendor.rst
- pipenv/vendor/requirementslib/__init__.py
- pipenv/vendor/requirementslib/models/setup_info.py
- pipenv/vendor/vendor.txt
Fixes deprecation warnings with new `setuptools` versions by vendoring in new `requirementslib` fix.
Fixes #5081 
> vendor in requirementslib==1.6.4

- news/5076.bugfix.rst
- pipenv/cli/command.py
- pipenv/utils/dependencies.py
- tests/integration/test_requirements.py
Solved by using existing convert_deps_to_pip function.
Fix #5076.
Original implementation by @fraser-langton. This also
solves the export of packages with editable mode, as suggested
by @hoyaaaa (#5071).
> Fixes of ``requirements`` with git requirements

- news/5075.bugfix.rst
- setup.py
Setuptools upgrade in setup.py causing issues for some users.
Fixes: https://github.com/pypa/pipenv/issues/5075
> revert setuptools required upgrade.

- docs/advanced.rst
- pipenv/cli/command.py
@matteius I gave `pipenv lock -r` some more thought and I think we should over time deprecate it in favor of `pipenv requirements`. This PR contains a deprecation warning and an update to the docs. Please let me know your thoughts
> Update docs and add deprecation warning for lock -r

- Makefile
- pipenv/core.py
- pipenv/environment.py
- pipenv/exceptions.py
- pipenv/resolver.py
- pipenv/shells.py
- pipenv/utils/indexes.py
- pipenv/utils/resolver.py
- pipenv/utils/shell.py
Found more stuff we can drop, so we are getting near the end of vistir dependency.
Also, gave a bit of dusting off the the makefile.
> More vistir drops makefile improvements

- .github/workflows/ci.yaml
- news/5096.bugfix.rst
- pipenv/environment.py
Python 3.10 introduced sysconfig._get_preferred_schemes[1], a mechanism to allow downstream distributors to overwrite the default install scheme.
This is done to support downstream modifications where distributors change the installation layout (eg. different site-packages directory). So, distributors will change the default scheme to one that correctly represents their layout.
This presents an issue for projects/people that need to bootstrap virtual environments, like virtualenv (see [2]) and pipenv too. As distributors might now be customizing the default install scheme, there is no guarantee that the information returned by sysconfig.get_default_scheme/get_paths is correct for the virtual environment, the only guarantee we have is that it is correct for the *current* environment. When …
> Make pipenv work with the `venv` install scheme if it is detected

- news/5134.bugfix.rst
- pipenv/cli/command.py
- tests/integration/test_requirements.py
Note: This is my first time ever contributing to an open source project. I'm super grateful for the work all of you are putting into the project. Keep it up!
According to issue #5134, environment variables are expanded when generating a `requirements.txt` file with `pipenv requirements`. This leads to credentials being leaked. 
The culprit can be found [here](https://github.com/pypa/pipenv/blob/b923d577a1e7dc5ee0b94a5b75e54bcac9dea106/pipenv/cli/command.py#L771).
How I understand the code, when calling `pipenv requirements` the lockfile is loaded using the `lockfile_content` property of the `project` object. This contains the lockfile as it used during runtime.
However, when generating a `requirements.txt` file this is not what we want, since environment variables are expanded.
Luckily, …
> Fix for #5134

- setup.cfg
Fix #5136.
This is an easy one. Found while installing pipenv newest ebuild on gentoo.
> Fix usage of deprecated `license_file`

- docs/conf.py
- docs/dev/contributing.rst
Fix #4778
Also, a tiny fix for the contributing.rst file.
> Fix Broken CLI docs

- news/5132.vendor.rst
- pipenv/vendor/requirementslib/__init__.py
- pipenv/vendor/requirementslib/models/markers.py
- pipenv/vendor/requirementslib/models/utils.py
- pipenv/vendor/vendor.txt
Vendor in the brand new `requirementslib` release I just published.
Fixes #5132 and perhaps some others (maybe the `setuptools` deprecation warning too 🤞 )
> 5132 Vendor in latest requirementslib.

- .github/workflows/ci.yaml
- news/5064.bugfix.rst
- tests/integration/test_install_uri.py
Fixes #5064
Compare the successful test run of https://github.com/pypa/pipenv/pull/5162
with this branch which does nothing except try to enable those failing tests again.
Outcome:  Would appear that we fixed something in the last several months that allow those skipped Windows tests to pass in the CI again.
> Reenable these tests again on the Windows CI.

- news/5158.bugfix.rst
- pipenv/cli/command.py
- pipenv/core.py
- pipenv/environment.py
- pipenv/environments.py
- pipenv/progress.py
- pipenv/project.py
- pipenv/utils/constants.py
- pipenv/utils/indexes.py
- pipenv/utils/processes.py
- pipenv/utils/resolver.py
- pipenv/utils/shell.py
- tests/integration/test_dot_venv.py
Follow-up to make NO_COLOR work and deprecated PIPENV_COLORBLIND.
There was some issues with the prior monkey patch suggested approach:  https://github.com/pypa/pipenv/pull/5184
So I opened this PR instead.
> Refactor to support the NO_COLOR argument and deprecate PIPENV_COLORBLIND

- pipenv/cli/command.py
https://github.com/pypa/pipenv/issues/5192
I added a space.  I also changed the order of words a bit to make it feel smoother.
> 5192 correct spacing for PIPENV_COLORBLIND warning

- news/5165.removal.rst
- tests/integration/test_install_basic.py
- tests/integration/test_install_twists.py
- tests/integration/test_lock.py
- tests/integration/test_pipenv.py
Remove tests that are old and permanently skipped, remove OS skips that seem to not make sense.
> Remove tests that are old and permanently skipped

- news/5204.bugfix.rst
- pipenv/core.py
- pipenv/environment.py
- pipenv/project.py
- pipenv/utils/resolver.py
`pip_shims` is slow and make the interface confusing for the internal `pip` usages.  Best part?  We no longer need to rely on pip_shims for pipenv usages, because we vendor in a specific version of pip and rely exclusively on it.
We will have to consider requirementslib separately, and then perhaps one day we can abandon pip_shims entirely.
* [?] Associated issue
> Unravel pip shims

- news/5200.removal.rst
- pipenv/cli/command.py
- pipenv/cli/options.py
- pipenv/core.py
- tests/integration/test_lock.py
Remove the deprecated `install -r` command and simplify the CLI interface + logic.
Fixes: #5198
We have the `pipenv requirements` command now.
> Remove old way of generting requirements.

- news/5214.bugfix.rst
- pipenv/cli/options.py
https://github.com/pypa/pipenv/issues/5214
This commit fixes the auto completing crash mentioned in the above command.
The bug is related to click and I have opened a corresponding issue in their github:
https://github.com/pallets/click/issues/2336
The main problem is that expose_value=False when used for arguments breaks the autocomplete.
The best solution is to fix click and then vendor the new version. However "expose_value=False" doesn't do anything for us as far as I can see. So removing it or setting it to true is a viable option.
> fix bug when auto completing install and uninstall

- news/5226.trivial.rst
- pipenv/utils/dependencies.py
- tests/unit/test_utils.py
This test sporadically fails on some of the CI runs -- looking more closely, we can convert off a vistir usage and update this test to not use pip-shims.  Hopefully this helps the CI not fail this test randomly.
> Convert this test off pip-shims, it became flakey recently.

- .github/workflows/ci.yaml
- Pipfile.lock
- news/5200.removal.rst
- news/5229.bugfix.rst
- pipenv/cli/command.py
- pipenv/core.py
- pipenv/project.py
- pipenv/utils/shell.py
- setup.py
- tests/unit/test_utils.py
Some of the other commands in core rely on the system installed pip, which has proven problematic for some issue reports in the past.   In PR we made great strides to using the internal vendored pip version and we dropped pip from being an installed requirement:  https://github.com/pypa/pipenv/pull/5199
This PR addresses other found spots in core.py that were using the user or system installed version of pip.   Fortunately in the latest pip we vendored in they revised the utility `_get_runnable_pip` such that it no longer generates a zip file, and it is the logical point for getting the module `pipenv.patched.pip` as a runnable python command.
It took me a few tries to arrive at this solution.
> Revise other spots that did not use the internal pip vendoring

- pipenv/core.py
After switching to use exclusively vendor'd pip for remaining commands, which includes install, two of the tests when run on python < 3.10 were failing in a weird loop where setuptools would get uninstalled and then be requested to install the newer version of setuptools and fail.   I am not sure why this passed on python 3.10 or why its so problematic for versions less than 3.10. 
The other thing this should fix is pipenv should no longer include BAD_PACKAGES in the Pipfile.lock -- these are packages that were already required be installed when installing `pipenv` so it should not be necessary to include them in the lock.  I had to manually delete setuptools from the pipenv Pipfile.lock to get the build to even run the tests for python versions < 3.10 in this PR: …
> Fix for inclusion of setuptools in the lock and install phase + other  BAD_PACKAGES.

- news/5235.doc.rst
- pipenv/core.py
- pipenv/environments.py
Removed the initialize method. This was masking sphinx autodoc.
Also, it was directly used inside the __init__ method.
Fix #5201
> Document all environment variables

- pipenv/project.py
new version of setuptools caused test failures with Mac OS https://pypi.org/project/setuptools/#history
I removed the offending code and all tests passed on windows, so I think this 2018/2019 logic may not be required.
> Remove code that is not required but may be causing the mac OS test failures.

- news/5234.bugfix.rst
- pipenv/core.py
- pipenv/resolver.py
- pipenv/utils/dependencies.py
- pipenv/utils/resolver.py
- tests/integration/test_install_basic.py
- tests/integration/test_lock.py
- tests/unit/test_utils.py
I'm trying to fix https://github.com/pypa/pipenv/issues/4371. I think it's better to consider 2 cases below:
- Installing from Pipfile.
- Installing from provided packages (the issue itself).
I read through the code, and here is what it does when installing packages from Pipfile:
1. Resolve `dev-packages` dependencies. Write to lockfile as default.
2. Resolve `packages` dependencies. Write to lockfile as develop.
3. Overwrite duplicated develop packages by default packages.
4. Install default and develop packages in the lockfile.
Because, `dev-packages` is resolved separately, there might be a chance where `dev-packages` is overwritten but its dependencies are not (they aren't duplicated with `packages`). So I think the result dependency graph would be more accurate if `packages` is …
> Issue 4371 incorrect dependencies when install dev packages

- news/5247.bugfix.rst
- pipenv/core.py
- tests/integration/test_install_basic.py
Fixes: #5247
When including the list of `BAD_PACKAGES` to be excluded from `batch_install` it caused problems for folks that depend on `packaging` to be installed by `pipenv`.  I don't see a reason to include `packaging` in the `BAD_PACKAGES` list.
> Don't count packaging as a bad package to omit.

- .pre-commit-config.yaml
- news/5254.bugfix.rst
- pipenv/core.py
Fixes #5254
Elsewhere we use `project_python(project)` but in my testing I was able to reproduce #5254 and discovered it was skipping `platformdirs` because it was already installed to my site-packages.
> Issue 5254

- pipenv/utils/shell.py
Remove `get_pipenv_dist` function that is no longer used.  We dropped using it in a prior PR.
> Remove `get_pipenv_dist` function that is no longer used.

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- news/5261.bugfix
- news/5261.bugfix.rst
- pipenv/utils/shell.py
This fixes https://github.com/pypa/pipenv/issues/5261.
Before this change, I would get a "The Python interpreter can't be
found" error when running `pipenv install --system` with a python3 but
no python.
Demo:
```
$ docker run $(docker build -q -f Dockerfile.pipenv-2022.8.15 https://github.com/jfly/2022-08-16-pipenv-system-which-issue.git#main)
Installing dependencies from Pipfile.lock (63bec0)...
The Python interpreter can't be found.▉ 0/4 — 00:00:00
🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/4 — 00:00:00
```
I'm confident this bug was introduced in
https://github.com/pypa/pipenv/commit/f276360dfcef3200908e2c6569567d617919c63d,
which removed a usage of `first()`, but broke the "filter None values"
behavior that `first()` gave us.
> Actually filter out missing interpreters

- news/5265.bugfix.rst
- pipenv/core.py
- pipenv/patched/pip/__main__.py
- tasks/vendoring/patches/patched/_post_pip_import.patch
Fixes #5265 
Fixes #5264
This is a much cleaner approach than to avoid having all the local site-packages in the path and require `--ignore-installed` as a workaround.   For reference this particular code works on Python 3.5+
Ref:  https://docs.python.org/3/library/importlib.html#importing-a-source-file-directly
> Revise how we do the import patch to include only module pipenv.

- news/5271.bugfix.rst
- pipenv/project.py
- pipenv/utils/resolver.py
Fixes #4323 
Constraints for editable packages were being added to the resolver when it encountered `install_requires` lines but not filtering them out when those requirements are included as editable packages.
> Exclude from resolver constraints the editable dependencies that will be installed.

- pipenv/utils/dependencies.py
- tests/unit/test_utils.py
This fixes https://github.com/pypa/pipenv/issues/5273
Convert ``Requirement`` into ``InstallRequirement`` before checking constraint.
> Issue 5273 constraints are not recognized

- .github/workflows/ci.yaml
- Pipfile.lock
- pipenv/core.py
- pipenv/patched/pip/_internal/locations/__init__.py
- tasks/vendoring/patches/patched/_post_pip_import.patch
Back when I was getting the rest of `pipenv` to use the vendor'd `pip`, I ran up against this issue that caused me to add `BAD_PACKAGES` to prevent setuptools from being installed.   The curious thing was the CI passed on python 3.10 -- through a recent interaction on issue #2364 and searching pip code for `3, 10` I found that the issue with installing setuptools after it had been uninstalled is diverted by patching to allow for usages of `sysconfig` on all supported python versions.   Based on this comment on the issue I opened in `pip` plus some additional CLI testing I did where I was able to install a specific version of `setuptools` using the `--system` flag, I think this change should be safe.  https://github.com/pypa/pip/issues/11389#issuecomment-1220185698
Fixes #2364
> Revert the exclusion of BAD_PACKAGES from batch_install

- docs/basics.rst
There is a typo in [Basic Usage of Pipenv](https://pipenv.pypa.io/en/latest/basics/) doc.
...
...
> Fix typo in Basic Usage of Pipenv doc

- news/5239.bugfix.rst
- pipenv/utils/resolver.py
this is a continuation of the following PR:
https://github.com/pypa/pipenv/pull/5279
> Fix nondeterminism with environment markers #5239

- news/5296.bugfix.rst
- pipenv/utils/shell.py
- tests/unit/test_utils.py
Fix a regression from commit dbea3f5 where `pip install --system` tries
to install using the `python` executable first which, on some systems
may point to Python 2.  Instead try `python3` first.
As explained in #5296 the is a regression whereby `pipenv install --system` will try `$(which python)` if it exists instead of `$(which python3)` and on some systems `python` points to Python 2, which will fail with `SyntaxError`.
The proposed fix is to try `python3` first, then `python` if `python3` fails.
> Fix: try python3 before python in `install --system` (#5296)

- README.md
- Fixed missing newlines.
- Updated indentation. within help-text.
I was reading the repository's README when I noticed some issues markdown-rendering issues.
These are caused due to missing newlines in the .md file and I thought of quickly fixing it up as it's a low-hanging fruit.
Plus, now it's much more readable . )
I also opened a issue for it at 
https://github.com/pypa/pipenv/issues/5280
Adding a newline where ever required + fixing indentations.
> Update README formatting at "Usage".

- pipenv/cli/command.py
- pipenv/core.py
- pipenv/utils/dependencies.py
- pipenv/utils/resolver.py
- tests/unit/test_utils.py
Its a good sign that they passed on this first run.
> Try to address these sporadic test failures without skipping the test.

- news/5239.bugfix.rst
- pipenv/utils/resolver.py
This reverts commit 4b9fc02a2561db47585e0fd822ada6dae6a49943.
@oz123 @bakhtiary -- this reverts: https://github.com/pypa/pipenv/pull/5286
because the change made here is actually fixing the issue and @dqkqd did some testing without this changeset and it was not required for fixing the issue:  https://github.com/pypa/pipenv/pull/5299#issuecomment-1228731246
I appreciate your effort to make pipenv better, please keep it up!   In this case, given some additional comments that came in on that PR and the added complexity that was not required, I think we should revert it.
> Revert "Fix nondeterminism with environment markers #5239 (#5286)"

- news/5309.bugfix.rst
- pipenv/utils/dependencies.py
Fix https://github.com/pypa/pipenv/issues/5273. 
This is a bug from commit https://github.com/pypa/pipenv/commit/640612d0d76a57e597517a1811c400e231f4cf1b. Because `check_invalid_constraint_type` from `pip` throws `PipDeprecationWarning`.
Create our own method for checking if package is constraint or not.
> Fixes checking constraint throws deprecation messages.

- Pipfile.lock
- news/4925.bugfix.rst
- pipenv/resolver.py
- pipenv/utils/resolver.py
> Issue 4925 resolver envvar limit

- pipenv/core.py
Fixes #5307
file installs can sometimes be caught into the standard requirements, which require hashes unless `--skip-lock` is passed.
> Fix issue where a file install is included with the hashed requirements.

- news/5316.trivial.rst
- pipenv/resolver.py
- pipenv/utils/resolver.py
Change #5313 to use a context manager as best practices suggest.
> Use a context manager to handle the temporary constraints file

- news/5273.bugfix.rst
- pipenv/utils/dependencies.py
Apply fix to constraints generation based on fact that pip resolver does not allowe unnamed constraints.
Fixes #5273
> Apply fix to constraints generation based on fact that pip resolver does not allowe unnamed constraints.

- pipenv/core.py
https://github.com/pypa/pipenv/pull/5301 broke keyring support again until https://github.com/pypa/pip/pull/11029 gets merged into Pip and then vendored into Pipenv.
This makes `get_pip_args()` respect `disable_pip_input` that was introduced in https://github.com/pypa/pipenv/pull/5036.
> Respect `disable_pip_input` setting from Pipfile

- Pipfile.lock
Was checking on if the markers bounced around, which they did not.   But I saw there were a few package updates we could commit.
> relock pipenv

- .pre-commit-config.yaml
- news/5306.bugfix.rst
- pipenv/core.py
- tests/integration/conftest.py
- tests/integration/test_install_basic.py
there are actually a couple of fixes here, one is that sometimes the file URL contains hashes so we should include that with the group with hashes like we did in `2022.8.31` by accident.  Also the filters after need to detect this additional part of the conditional and that change was missing in #5326.
#5306
> fix for issue where requirement is a file or URL but does conntain hashes.

- news/5329.bugfix.rst
- pipenv/utils/resolver.py
Thank you for contributing to Pipenv!  Replacement of: https://github.com/pypa/pipenv/pull/4982
Upstream setup.py can not define the setup.py markers properly, and pipenv will reveal a cryptic error.   This solves for that and allows the installation to move forward without the marker, while alerting the user of the potential problem.
> improve the case of upstream dependencies that mess up markers

- news/5328.removal.rst
- pipenv/cli/options.py
pipenv now uses python3 by default.
Following our discussion in #5304
> Deprecate the --three flag

- pipenv/core.py
- pipenv/utils/indexes.py
- tests/integration/test_install_uri.py
- tests/integration/test_lock.py
When installing a requirement that explicitly references an index all indexes are searched even though `install_search_all_sources = False`.
There were two different locations where the code appears to not have the expected behavior.
> Fix extra indexes

- tests/integration/conftest.py
- tests/integration/test_cli.py
- tests/integration/test_install_basic.py
- tests/integration/test_install_twists.py
- tests/integration/test_install_uri.py
- tests/integration/test_lock.py
- tests/integration/test_pipenv.py
- tests/integration/test_project.py
- tests/integration/test_requirements.py
- tests/integration/test_uninstall.py
On my fast laptop these were the 20 slowest tests:
```
259.54s call     tests/integration/test_lock.py::test_complex_lock_with_vcs_deps
254.14s call     tests/integration/test_install_uri.py::test_get_vcs_refs
253.65s call     tests/integration/test_install_twists.py::test_multiple_editable_packages_should_not_race
152.11s call     tests/integration/test_install_twists.py::test_local_zipfiles
137.95s call     tests/integration/test_lock.py::test_lock_editable_vcs_with_extras_without_install
133.73s call     tests/integration/test_lock.py::test_lock_nested_direct_url
133.52s call     tests/integration/test_lock.py::test_lock_editable_vcs_without_install
132.87s call     tests/integration/test_install_uri.py::test_install_editable_git_tag
130.86s call …
```
> Examine the 20 slowest tests and make improvements.

- pipenv/cli/command.py
- pipenv/core.py
- pipenv/utils/environment.py
- tests/unit/test_core.py
So this other PR actually didn't fix the issue:  https://github.com/pypa/pipenv/pull/5334
> Actually load the dot env file before virtualenv creation.

- pipenv/cli/command.py
- pipenv/core.py
Safety >= changed its JSON output leading to a strange output by the pipenv check command.
Safety >= 2.0 includes new options and improvements; this PR includes the new options and renders the improved Safety screen output, which offers more information to the users about the scan done. 
This pull request is related to #5218
> Improving pipenv check command with the new Safety options

- pyproject.toml
- setup.cfg
[PEP621](https://peps.python.org/pep-0621/) encourages the Python community to migrate away from complex `setup.cfg` + `setup.py` files by putting config data in `pyproject.toml`.  Let's keep moving in that direction.  https://github.com/abravalheri/ini2toml …
> Migrate isort, mypy, and pytest config into pyproject.toml

- .github/workflows/ci.yaml
- .github/workflows/pypi_upload.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- news/5352.trivial.rst
- pipenv/cli/options.py
pipenv can generate its own shell completions using the click framework. Prior to this PR, there are no file/path completions for the `-r` and `-e` options. See #3478 for a discussion.
This PR changes the option type to `click_types.Path` for `-r` and `-e`. This is enough for click to know that file/path completions are desired here.
And this isn't only beneficial for fish shell, it automatically applies to bash and zsh also.
This fixes partially issue #3478 but not the part concerning `pipenv run` completions.
I'm not sure whether the news fragment is mandatory and which type would be appropriate. If you tell me, I could add one.
> cli: set `click_types.Path` for `-r` and `-e` options

- .github/workflows/ci.yaml
- .github/workflows/pypi_upload.yml
- news/5368.bugfix.rst
- pipenv/core.py
- pipenv/patched/patched.txt
- pipenv/patched/pip/_vendor/platformdirs/LICENSE.txt
- pipenv/patched/pip/_vendor/rich/LICENSE
- pipenv/patched/pip/_vendor/tenacity/LICENSE
- pipenv/vendor/platformdirs/LICENSE.txt
- pipenv/vendor/plette/__init__.py
- pipenv/vendor/plette/lockfiles.py
- pipenv/vendor/vendor.txt
- tasks/vendoring/__init__.py
- tests/integration/test_install_twists.py
Fixes #5367 
Depends on:  https://github.com/sarugaku/plette/pull/26/files
> Fix for --skip-lock

- pipenv/vendor/requirementslib/__init__.py
- pipenv/vendor/requirementslib/models/markers.py
- pipenv/vendor/vendor.txt
> Always evaluate markers fresh, without lru_cache.

- pipenv/core.py
- pipenv/environment.py
I did not realize how broken pipenv is out of the box on the latest ubuntu until I upgraded.   It has to do with it defaulting to `posix_local` when creating a virtualenv, which has different paths for the python binaries.  I initially tried preferring `posix_local` for the paths but it had the side effect of trying to install everything to local site packages.
Risks:  The venv creator should be available on all systems, but the documentation points out:
> venv - this delegates the creation process towards the venv module, as described in [PEP 405](https://www.python.org/dev/peps/pep-0405). This is only available on Python interpreters having version 3.5 or later, and also has the downside that virtualenv must create a process to invoke that module (unless virtualenv is installed in the …
> Use creator venv when creating virtual environments

- news/5380.bugfix.rst
- pipenv/utils/indexes.py
Prefer to use the lockfile sources if available since this is used in install phase
Fixes #5353 whereby the user was only supplying the lockfile to the docker build for sync/deploy/install phase--we should prefer in install to use the sources from the lockfile.
> Prefer to use the lockfile sources if available since this is used in install phase

- news/5187.vendor.rst
I accidentally pushed the actual change directly to the master branch.
Hence, this PR only includes the news fragment.
> Add news fragment for dropping six

- news/5345.behavior.rst
- pipenv/project.py
- tests/integration/test_install_basic.py
https://github.com/pypa/pipenv/issues/5345
A user requested that when the full version is specified that it gets added to a new pipfile when it is created so that he/she wouldn't need to manually add it themselves.
Found the spot where the pipefile [requires] section gets created and modified it slightly to save based on if full version was specified or not.
> Python full version in pipfile

- news/5294.feature.rst
- pipenv/cmdparse.py
- tests/integration/test_run.py
- tests/unit/test_vendor.py
Requested new feature to add the ability to include something like:
```[scripts]
main = {call = "foo_package.bar_module:main('dev')"}
```
https://github.com/pypa/pipenv/issues/5294
This adds the ability to parse a callable with module.func in scripts
> Scripts run package functions

- pipenv/cli/options.py
- pipenv/core.py
- tests/integration/test_install_categories.py
Lack of build isolation means that build requirements no longer are implicitly installed and have to be installed ahead of time.  I am revisiting that decision to change the default isolation level because I feel it has already caused enough problems with existing workflows, and I realized an alternate solution is to recommend users that have issues requiring pre-requisites to pass ` --extra-pip-args="--no-build-isolation"` in their install or sync commands.
Fixes #5391 
Fixes #5398
> Revert back to build isolation by default; support extra-pip-args on sync command.

- docs/advanced.rst
- news/5396.doc.rst
- pipenv/cmdparse.py
Missed the docs on this one: https://github.com/pypa/pipenv/pull/5390
So updated it. Also noticed could improve the error message if command parsed wrongly so updated that too.
Updated docs
> Update documentation for callable scripts

- docs/_templates/sidebarlogo.html
The documentation sidebar contains a "Recommended Packages " that points to a page in Request's documentation, not in Pipenv's
Remove the bad link
> Remove recommended packages link in doc sidebar

- .github/workflows/ci.yaml
Hi
- Fixes for deprecated workflow syntax: #5404
> Replace deprecated workflow command

- README.md
The VCS Support Link was outdated, so I have tried to update it with the current lastest link.
> Update Link For VCS Support

- docs/dev/contributing.rst
I've noticed a missing backtick in the documentation that made some part of the documentation to look like code, when it shouldn't.
This PR fixes it.
> Add missing backtick in the contributing documentation.

- pipenv/project.py
- pipenv/utils/shell.py
- tests/integration/conftest.py
- tests/integration/test_install_twists.py
- tests/integration/test_run.py
As the last commit says, this function is obsolete.
> Remove usage of mkdir_p in favour of os.makedirs

- docs/advanced.rst
- news/5431.feature.rst
- pipenv/cli/command.py
- tests/integration/test_requirements.py
Closes: https://github.com/pypa/pipenv/issues/5397
This adds a `category` option to the `requirements` command. If specified a category, it will only generate the requirements of that category.
> Add support for multiple categories in exported requirements

- .github/workflows/ci.yaml
- .github/workflows/pypi_upload.yml
Hi `pipenv` community,
Currently, Foresight (https://www.runforesight.com/) is integrated into this repository to monitor CI pipelines and insights are publicly available here: pypa.app.runforesight.com
But for more detailed monitoring and richer insights, Foresight needs its Github actions to be added into the workflows.
This pull request adds Foresight `workflow-kit` and `test-kit` Github actions into **`CI `** (`ci.yml`) and **`Upload Python Package`** (`pypi_upload.yml`) workflows to collect workflow resource usage metrics, process traces and test results.
Note that in the PR, even though `FORESIGHT_API_KEY` is passed to the Foresight Github actions from secrets, it is OK to leave it undefined/empty. Because there is no need for an API key as we support "tokenless authentication" for …
> added foresight workflow and test kit actions

- pipenv/environment.py
- pipenv/resolver.py
- pipenv/utils/shell.py
Instead, we use `pipenv.utils.shell.load_path`.
> Rewrite Environment.sys_path without vistir.misc.run

- news/5419.removal.rst
- pipenv/environment.py
Following #5390 I realized this code is duplicated into pipenv, and we can use that instead of the one in vistir.
> Remove usage of vistir.cmdparse

- README.md
Hello, Pipenv community!
Since the **pipenv** project is now integrated with [Foresight](https://runforesight.com/) (#5433) and the project's workflow runs are listed publicly at [pypa.app.runforesight.com](https://pypa.app.runforesight.com/), displaying the test run results on the README would improve the accessibility throughtout the community. 
The badge looks as such;
[![image](https://api-public.service.runforesight.com/api/v1/badge/test?repoId=a9acfd31-fca9-4ebb-a449-c7bf0f85a481)](https://pypa.app.runforesight.com)
This change adds the said status badge for the pipenv workflow runs and links the project's public page on Foresight.
> Add Foresight status badge to README

- LICENSE
Updated the outdated copyright year to the present.
> chore: Update outdated LICENSE year

- docs/advanced.rst
- docs/dev/contributing.rst
- news/5451.feature.rst
- pipenv/environments.py
- pipenv/utils/shell.py
- tests/integration/test_cli.py
- tests/unit/test_environments.py
- tests/unit/test_utils.py
See #5407
* some pipenv settings are insufficiently documented, especially in terms of how to disable them
* implementation of pipenv settings detection is inconsistent, even though `pipenv.environments.get_from_env` exists as a pretty hardened utility
* refactor all relevant settings to use get_from_env, which more explicitly allows settings to be disabled
* add default kwarg to get_from_env
* update docs to indicate how to explicitly disable a setting
Other changes
- Fix rst in contributing guide
- Refactor out is_env_truthy
> Consolidate pipenv settings to use get_from_env

- news/5459.bugfix.rst
- pipenv/vendor/click/_compat.py
- pipenv/vendor/colorama/LICENSE.txt
- pipenv/vendor/colorama/__init__.py
- pipenv/vendor/colorama/ansi.py
- pipenv/vendor/colorama/ansitowin32.py
- pipenv/vendor/colorama/initialise.py
- pipenv/vendor/colorama/win32.py
- pipenv/vendor/colorama/winterm.py
- pipenv/vendor/vendor.txt
- pipenv/vendor/vistir/misc.py
- pipenv/vendor/vistir/spin.py
- pipenv/vendor/vistir/termcolors.py
- tasks/vendoring/__init__.py
Quick fix to roll back change of vendoring of colorama to solve issue report.
Fixes #5458 
Fixes #5459
> Roll back change vendoring of colorama.

- .github/workflows/ci.yaml
- Pipfile.lock
On **macOS**:
```
============================= test session starts ==============================
platform darwin -- Python 3.11.0rc1, pytest-7.1.2, pluggy-1.0.0
[ ... ]
FAILED tests/integration/test_cli.py::test_pipenv_graph - assert 1 == 0
FAILED tests/integration/test_cli.py::test_pipenv_graph_reverse - assert 1 == 0
FAILED tests/unit/test_utils.py::test_convert_deps_to_pip[deps0-requests] - A...
FAILED tests/unit/test_utils.py::test_convert_deps_to_pip[deps1-requests[socks]]
===== 4 failed, 278 passed, 18 skipped, 21 warnings in 1704.26s (0:28:24) ======
```
Always consider opening an issue first to describe your problem, so we can discuss what is the …
> Add Python 3.11 to the testing

- news/5456.bugfix.rst
- pipenv/core.py
- tests/integration/conftest.py
- tests/integration/test_uninstall.py
Fixes #5456
After named package categories was released, the lock file generation had the default behavior of `--keep-outdated` being passed true.
> Issue 5456

- pipenv/environments.py
I upgraded  from 2022.10.25 to 2022.11.5 and I figured out that my PIPENV_MAX_DEPTH env variable was not taken into account anymore. I had to use PIPENV_PIPENV_MAX_DEPTH. So here is a PR to fix the issue.
Bug introduces here: https://github.com/pypa/pipenv/pull/5451/files#diff-f74d4ef3c891c83b08a2b15b21602d0c31859892478cc4f56bf5be1a2c5092ecL185
> fix PIPENV_MAX_DEPTH environment variable

- news/5470.feature.rst
- pipenv/shells.py
```
pipenv shell
```
doesn't recognise nushell, follow up of https://github.com/pypa/pipenv/pull/5336
> feat(shells): support nushell

- pipenv/vendor/requirementslib/models/metadata.py
- tasks/vendoring/__init__.py
Compiling [vendor/requirementslib/models/metadata.py](https://github.com/pypa/pipenv/blob/30be4768010493cbcbef56752ae85f5c27b13b93/pipenv/vendor/requirementslib/models/metadata.py) raised a `SyntaxError`:
***   File "/gnu/store/62ms8p25ilrw7vrz5fn8fjf4pds10b02-pipenv-2022.11.11/lib/python3.9/site-packages/pipenv/vendor/requirementslib/models/metadata.py", line 17
from pipenv.patched.pip._vendor.distlib.metadata import import Metadata
^
SyntaxError: invalid syntax
Found through `python -m compileall /pipenv/source/` when trying to add pipenv to [Guix](https://guix.gnu.org/).
> Fix syntax error in requirementslib vendor

- news/5496.bugfix.rst
- setup.cfg
Resolve #5496 
https://packaging.python.org/en/latest/guides/dropping-older-python-versions/#dealing-with-the-universal-wheels
> Traditionally, projects providing Python code that is semantically compatible with both Python 2 and Python 3, produce [wheels](https://packaging.python.org/en/latest/glossary/#term-Wheel) that have a `py2.py3` tag in their names. When dropping support for Python 2, it is important not to forget to change this tag to just `py3`. It is often configured within setup.cfg under the `[bdist_wheel]` section by setting `universal = 1` if they use setuptools.
> Stop building universal wheels

- pipenv/core.py
- tests/integration/test_cli.py
#4819
#5488
Now, this command gets the packages to be analyzed from the target venv.
> Get packages for `pipenv check` from the target venv.

- docs/index.rst
- docs/install.rst
Fixes #5494 and also some other documentation review/updates.
> Documentation updates.

- pipenv/core.py
- tests/integration/test_cli.py
Migrating to rich console, caused a regression, where virtualenv creation reporting was to stdout. This reporting got included in requirements.txt.
This fixes #5503.
> requirements: fix generation of file

- news/5508.bugfix.rst
- pipenv/project.py
Need to let the test runner go and see if there is still a valid reason I added this conditional during named package categories feature work.   Fixes #5508
> Remove newer code branch that prevents new sources from being added to lockfile.

- news/5477.bugfix.rst
- pipenv/core.py
> Fix issue with venv module not being available on some systems.

- docs/quickstart.rst
Noticed a spelling error in the Quickstart docs when reading https://pipenv.pypa.io/en/latest/
Fixed spelling of word "regenerate" in `docs/quickstart.rst`
This seemed like such a simple fix, I did not bother with adding a news item, et al. Apologies if this means more work for the maintainers.
> Fix spelling error in docs/quickstart.rst

- news/5479.bugfix.rst
- pipenv/utils/dependencies.py
- pipenv/utils/locking.py
- tests/integration/test_install_uri.py
> Fix regression where wheel path is not included in the lockfile

- news/5486.bugfix.rst
- pipenv/utils/dependencies.py
- tests/integration/test_lock.py
Fixes #5486 
This checks if the marker has a value before adding it to the lock file.
> Issue 5486 null markers

- pipenv/__init__.py
Clean up the windows deprecation warnings for pipenv main branch.
> Remove CI from deprecation warning and only alert if env vars are set.

- news/5539.vendor.rst
- pipenv/vendor/plette/__init__.py
- pipenv/vendor/plette/__main__.py
- pipenv/vendor/plette/models/__init__.py
- pipenv/vendor/plette/models/packages.py
- pipenv/vendor/plette/models/sections.py
- pipenv/vendor/plette/pipfiles.py
- pipenv/vendor/vendor.txt
vendoring pipenv 0.4.4 to add more robust Pipfile validation and address #5440.
> vendor: bump plette to 0.4.4

- news/5540.bugfix.rst
- pipenv/core.py
- pyproject.toml
- tests/integration/test_update.py
closes https://github.com/pypa/pipenv/issues/5540
https://github.com/pypa/pipenv/issues/5540
Lookup the target package from the correct category instead of always using `[package]` category.
> [fix] `update --outdated` raises NonExistentKey with dev package

- news/5477.bugfix.rst
- pipenv/core.py
- pipenv/environments.py
Fixes #2538
The fix to import venv was ineffective, but this should retry without it if the first call resulted in error.
There is an existing news fragment about fixing this.
> Refactor virtualenv create logic and add retry if creator venv results in error

- README.md
> Fix Readme.md links.

- pipenv/cli/options.py
This flag, which was never fully explained in the documentation, leads to a source of a lot of confusion and issue because the underlying concept is flawed.   It cannot be used until a consistent lock file is generated with `pipenv lock` or `pipenv install` and then when applied it will bring in any new package from a new consistent lock phase which is not already defined in the `Pipfile.lock` thus often creating inconsistent and unexpected locks. 
This was always a workaround to avoid managing the Pipfile specifiers and packages listed/pinned in the Pipfile, which is the inputs into the resolver for the new lock phase whenever modifying package requirements.  Instead, users that do not want packages updated while upgrading other packages should be pinning those in the Pipfile so they can …
> Deprecate --keep-outdated flag.

- pipenv/core.py
Fixes #5462 
Sometimes users have index names defined in their Pipfile that do not correspond to actually defined sources.
Alert the user when this happens with a human friendly message and exit with failure code.
> Catch StopIteration error and alert user and exit failure.

- README.md
- docs/advanced.rst
- docs/basics.rst
- news/5576.removal.rst
- pipenv/cli/command.py
- pipenv/cli/options.py
- pipenv/core.py
- pipenv/environments.py
- tests/integration/test_cli.py
The flag was deprecated 4 months ago and it's time to let it go.
Doing so removes a lot of state and checks.
> Remove deprecated flag --three

- .pre-commit-config.yaml
- news/5530.bugfix.rst
- pipenv/core.py
- pipenv/utils/resolver.py
- tests/integration/test_update.py
> Fix verbose logging

- news/5554.bugfix.rst
- news/5586.vendor.rst
- pipenv/environments.py
Fixes #5554 
Use `pipenv` utility for reading and checking the env variable but doesn't require its truthyness.
> Fix regression with CI variable

- setup.py
Following the discussion in #5582, it seems it's about time to update these versions.
> Bump required setuptools and virtualenv

- news/5603.bugfix.rst
- pipenv/shells.py
This adds support for Nushell overlays. See #5583 for info.
Nushell support is broken due to a change in the `virtualenv` package which expects users to load the file using overlays instead of the `source` command. See #5583 for info.
Changing the command from `source` to `overlay use` resolves the issue.
> Switch to Nushell overlays

- docs/dev/contributing.rst
- news/5611.doc.rst
I made some minor improvements to the contributing guide. I also tried to merge the two paragraphs about testing into one. Maybe this could still be improved.
> Improved contributing guide

- docs/advanced.rst
- news/5600.feature.rst
- pipenv/cli/command.py
- pipenv/core.py
- tests/integration/test_cli.py
Fixes issue #5600 
Supply the options to pull the requirements from the lock file categories.
> Issue 5600 check command should be able to pull requirements from lock file

- news/5618.trivial.rst
- pipenv/cli/options.py
> Add missing spaces to `--keep-outdated` deprecation text

- .github/workflows/ci.yaml
- Pipfile.lock
- news/5620.trivial.rst
- setup.py
This shouldn't affect anything other than the shipped Pipfile.lock having one less package in it, and future-proofing in case the BeautifulSoup maintainer ever stops maintaining the redirect.
The `bs4` on PyPI is just a redirect to the latest release of `beautifulsoup4`.  Might as well point to the actual package.
Notably, in some cases, a scanner of a package  downstream of pipenv will note that their dependency chain is including a package (`bs4`) that is marked "inactive" on PyPI.
Swap `bs4` for `beautifulsoup4` in the two places where it's mentioned.
Surgically remove bs4 from the Pipfile.lock.
* [:x:] Associated issue
* [:heavy_check_mark:] A news fragment in the `news/` directory to describe this fix with the extension `.bugfix.rst`, `.feature.rst`, `.behavior.rst`, `.doc.rst`. …
> Require the actual 'beautifulsoup4' package, not the 'bs4' redirect.

- news/5628.trivial.rst
- pipenv/routines/check.py
pipenv check still prints "Checking installed packages for vulnerabilities...", regardless of it's using the installed environment with --use-installed or if it's using the dependencies from Pipfile.lock. If using default behavior, this should read something like "Checking Pipfile.lock packages for vulnerabilities..."
Fix #5600 
Show a different message if  `--use-installed` is specified in `pipenv check`
> Message for Pipfile.lock packages vulnerabilities check

- pipenv/cli/command.py
- pipenv/routines/update.py
Fixes #5624 
No news fragment requirement since the upgrade command hasn't been released yet.
> Fix dev flag support in update/upgrade.

- news/5636.bugfix.rst
- pipenv/utils/virtualenv.py
Ah crud -- totally missed this until I went to use the new pipenv today.
```
from .installers import Asdf, InstallerError, InstallerNotFound, Pyenv
ModuleNotFoundError: No module named 'pipenv.utils.installers'
```
> Fix import issue with pipenv 2023.3.18.

- docs/commands.md
- news/5644.docs.rst
Found a minor typo while reading docs.
This corrects the typo.
> Correct typo in docs

- .pre-commit-config.yaml
- Makefile
- docs/advanced.rst
- news/ruff.feature.rst
- pipenv/__init__.py
- pipenv/routines/update.py
- pipenv/utils/pip.py
- pipenv/utils/resolver.py
- pipenv/utils/shell.py
- pipenv/utils/virtualenv.py
- pyproject.toml
- setup.cfg
- tasks/vendoring/__init__.py
- tests/fixtures/fake-package/tasks/__init__.py
- tests/integration/test_install_basic.py
- tests/integration/test_install_misc.py
- tests/integration/test_install_uri.py
- tests/integration/test_uninstall.py
Continuation of #5361
[Ruff](https://beta.ruff.rs/) supports [over 500 lint rules](https://beta.ruff.rs/docs/rules) and can be used to replace [Flake8](https://pypi.org/project/flake8/) (plus dozens of plugins), [isort](https://pypi.org/project/isort/), [pydocstyle](https://pypi.org/project/pydocstyle/), [yesqa](https://github.com/asottile/yesqa), [eradicate](https://pypi.org/project/eradicate/), [pyupgrade](https://pypi.org/project/pyupgrade/), and [autoflake](https://pypi.org/project/autoflake/), all while executing (in Rust) tens or hundreds of times faster than any individual tool.
Added ruff in all the right places and removed flake8 and isort.
> feat: Replace flake8 and isort with ruff

- .pre-commit-config.yaml
- news/5653.bugfix.rst
- pipenv/routines/install.py
Fixes issue #5367  with --skip-lock reading from the lock file.
Fixes also issue #5654 
Going to want help testing this more thoroughly.
> Fix issue with skip-lock

- news/5659.vendor.rst
- pipenv/vendor/requirementslib/__init__.py
- pipenv/vendor/requirementslib/models/old_pip_utils.py
- pipenv/vendor/requirementslib/models/setup_info.py
- pipenv/vendor/vendor.txt
Vendor in latest requirementslib which includes the update for pip 23.1 so revendoring pipenv will be consistent.
> Vendor in latest requirementslib.

- docs/commands.md
There is a typo in the command part of the document. Since this is a very tiny change, I didn't file an issue or add news.
Fixed the typo.
> Fix a typo in the document

- .github/workflows/ci.yaml
- .github/workflows/pypi_upload.yml
- README.md
My understanding is Foresight is shutting down in May, and we will no longer be able to report telemetry, so we may as well remove it from our builds.
> Remove foresight

- pipenv/shells.py
xonsh supports virtualenv with a plugin. So if pipenv creates a virtualenv in xonsh, it would have a bin/activate.xsh. This change uses that script in 'pipenv shell'.
> pipenv shell: support xonsh

- pipenv/utils/shell.py
- pipenv/utils/virtualenv.py
- pipenv/vendor/click/core.py
- pipenv/vendor/click/globals.py
- pipenv/vendor/click/parser.py
- pipenv/vendor/click/types.py
- pipenv/vendor/click/utils.py
- pipenv/vendor/markupsafe/__init__.py
- pipenv/vendor/pythonfinder/__init__.py
- pipenv/vendor/pythonfinder/environment.py
- pipenv/vendor/pythonfinder/models/mixins.py
- pipenv/vendor/pythonfinder/models/path.py
- pipenv/vendor/pythonfinder/models/python.py
- pipenv/vendor/pythonfinder/pythonfinder.py
- pipenv/vendor/vendor.txt
Vendor in `pythonfinder==2.0.1`
Backstory:
I discovered that pyenv was broken with the new pythonfinder.   It was trying to install the system python and alerting that it was different than what was called out in the Pipfile.  Despite pyenv being installed, it did nothing to try and use those versions.
This also cleans up some other edge cases around pyenv:
* Ensures the shims directories will not be included (there was logic for this in there, but the paths weren't matching)
* Ensures the version directories are included on the PATH
> Fix pyenv as it is broken on new pythonfinder version.

- pipenv/utils/shell.py
- pipenv/vendor/pythonfinder/__init__.py
- pipenv/vendor/pythonfinder/environment.py
- pipenv/vendor/pythonfinder/models/path.py
- pipenv/vendor/pythonfinder/utils.py
- pipenv/vendor/vendor.txt
Windows was having issues creating new virtualenvs after this patch:  https://github.com/pypa/pipenv/pull/5686
There were two types of issues:
* sometimes the windows PATH may come from an env var in gitbash shell as \ instead of /
* It was sometimes double appending the drive and creating a new directory structure for the virtualenv home.
Fix PATH edge case in `pythonfinder==2.0.2`
Declining on a news fragment since the issue was never published in a pipenv release.
> Handle windows paths better and utilize this utility for creating the virtualenv path.

- pipenv/vendor/pythonfinder/__init__.py
- pipenv/vendor/pythonfinder/models/path.py
- pipenv/vendor/vendor.txt
Vendor in pythonfinder 2.0.3 to fix regression finding a specific python version should it not be installed.
> Fix pyenv version not installed edge case

- news/5681.trivial.rst
- pipenv/cli/command.py
#5680
`No action taken to avoid nested environments` can be read either way.
Describes what action was not taken.
> Reword active shell warning to reduce ambiguity

- news/5709.bugfix.rst
- pipenv/vendor/pythonfinder/__init__.py
- pipenv/vendor/pythonfinder/models/mixins.py
- pipenv/vendor/vendor.txt
Fixes #5709
Adds equality method to the base PathEntry
> Pythonfinder 2.0.4

- news/5701.feature.rst
- pipenv/project.py
- pipenv/utils/resolver.py
PEP 503 https://peps.python.org/pep-0503/
> The URL SHOULD include a hash in the form of a URL fragment with the following syntax: #<hashname>=<hashvalue>, where <hashname> is the lowercase name of the hash function (such as sha256) and <hashvalue> is the hex encoded digest.
This should enable non pypi.org sources that are following PEP 503 to be able to leverage those package hashes without downloading the package.   This may also lead to a wider inclusion of package hashes in the lock file.
Replacement PR for: https://github.com/pypa/pipenv/pull/5688
> Pep 503 hashed urls

- pipenv/project.py
- pipenv/routines/install.py
- pipenv/utils/resolver.py
- tests/integration/test_install_basic.py
Intended as a performance optimization and to reduce code complexity -- there should not be a reason to pre `pip install` the new packages before resolving and batch installing them.
> This pre pip install path should no longer be neccessary when adding packages.

- news/4588.bugfix.rst
- pipenv/installers.py
- pipenv/patched/pip/_vendor/typing_extensions.py
- pipenv/utils/shell.py
- pipenv/vendor/pydantic/env_settings.py
- pipenv/vendor/pydantic/fields.py
- pipenv/vendor/pydantic/mypy.py
- pipenv/vendor/pydantic/networks.py
- pipenv/vendor/pydantic/schema.py
- pipenv/vendor/pydantic/types.py
- pipenv/vendor/pydantic/typing.py
- pipenv/vendor/pydantic/version.py
- pipenv/vendor/vendor.txt
Fixes #4588 
Fixes #5714 
Improve the code paths for:
* Matching an existing path
* using the line as a version specifier (improved regex)
> Fix for Issue 4588 (path to python improvements)

- docs/docker.md
- docs/index.md
- docs/indexes.md
- docs/installation.md
- docs/specifiers.md
- docs/virtualenv.md
- docs/workflows.md
Fix formatting in docs, mainly links and codeblocks that were not adjusted in the rst->md transition, plus remove some duplication in the install section.
Feel free to change anything you don't like.
> Fix formatting in /docs

- pipenv/utils/internet.py
- pipenv/utils/resolver.py
Fixes #5724 
The improvement to the pep 508 URLs for determining appropriate hash did not consider the verify_ssl requirements.   Also, it seemed odd to me that even though pipenv is multi-processing we had a global variable for the requests session state.   This made it hard to have different requests (some that verify ssl and some that do not).  Since the primary point of re-use of the requests session is in the Resolver, I made a patch there to have a separate requests session per source.
> Safer usage requests sessions and account for the verify_ssl requirements of each source.

- news/5719.bugfix.rst
- pipenv/__init__.py
- pipenv/cli/command.py
- pipenv/routines/install.py
Fixes #5719 
Fixes #4706 
When we added back the hack to the sys.path it broke the google keyring support, I verified this -- because the appropriate requests package module cannot be found (strangely).   My goal has bene to eliminate these path patchces for a while and there were a couple reasons I had to add them back recent which I think have since been resolved:
1.) pydantic was getting an import error on typing_extensions, but the latest vendor'd pydantic seems to have cleaner imports which got re-written to use the right vendor path.
2.) pipdeptree prior version was getting an error on `pipenv graph` but it seems like the new version of `pipdeptrees` may be immune.
I verified that removing this path allows the google keyring stuff to work again.
It still requires that keyring and …
> Remove the sys path hacks (again) to fix edge cases with keyring

- docs/commands.md
- news/5737.bugfix.rst
- news/5737.removal.rst
- pipenv/cli/options.py
- pipenv/exceptions.py
- pipenv/patched/pip/_internal/models/search_scope.py
- pipenv/routines/outdated.py
- pipenv/utils/indexes.py
- tasks/vendoring/patches/patched/pip_index_safety.patch
- tests/integration/test_install_uri.py
- tests/integration/test_lock.py
At some point pip changed behaviors of how it searches among the indexes to not always prefer pypi -- this difference caused inconsistency with the index restricted packages expectations.
Fixes #5736
> Only search the Pipenv default index when an alternative index is not specified.

- docs/configuration.md
- news/missing_env_var_desc.doc.rst
https://github.com/pypa/pipenv/issues/5748
Adds missing tab due to a typo when docs were refactored
> Fix for issue #5748

- news/5755.bugfix.rst
- pipenv/cli/command.py
- pipenv/routines/requirements.py
- tests/integration/test_requirements.py
Fixes #5755 
The requirements command should have it all it needs from the lock file, but its re-using a requirementslib method that installs the requirements, which was a regression for the requirements command when we released requirementslib==3.0.0
Provide our own method and relocate the requirements command logic to the routines module.
> requirements command improvements, fixes issue 5755.

- news/5746.bugfix.rst
- pipenv/utils/internet.py
Fixes #5746 
When we introduced the pep508 package index url checks for determining package hashes, it broke users that rely on client side certificates when locking.
Consider how the users were supplying client side certs with `PIP_CLIENT_CERT` and pass it to the requests session as well.
> Consider the PIP_CLIENT_CERT value when creating the requests session.

- news/5766.bugfix.rst
- pipenv/utils/resolver.py
- pipenv/vendor/requirementslib/models/requirements.py
- pipenv/vendor/requirementslib/models/setup_info.py
- pipenv/vendor/requirementslib/models/utils.py
- tests/integration/test_lock.py
Fixes Issue #5766 
Ensure we consider the dependencies listed in the pyproject.toml
> Issue 5766

- news/5760.bugfix.rst
- pipenv/environment.py
- pipenv/project.py
- pipenv/resolver.py
- pipenv/utils/dependencies.py
- pipenv/utils/project.py
- pipenv/utils/resolver.py
- pipenv/utils/virtualenv.py
- pipenv/vendor/requirementslib/models/setup_info.py
It was discovered that requirementslib uses the sys.executable python rather than the pipenv environment python.  Which as @oz123 reminded me should be the same, but due to some weird code paths, it wasn't always the same in my testing when the resolver got invoked as subprocess.
Fixes #5753 
I don't love the use of the environment variable, but I figured out this was the original intention of how the pipenv <--> requirements lib interface and at some point it got hard-coded to sys.executable in the resolver code which was getting invoked with a different python version at points.
This fixes the problem by ensuring that the correct python of the pipenv environment is being used.
> Patch for setup.py egg_info issue

- docker/Dockerfile
- docker/Makefile
- docker/README.md
- docs/docker.md
Publish docker images for CICD.
Added a subtle note in the docs. The changelog should definitely explain more how to use these images.
See news snippet that will follow.
> Add docker build, update docs for using docker images

- pipenv/project.py
- pipenv/utils/project.py
- pipenv/utils/resolver.py
Fixes #5772 
Consider the system flag in the python which command.
> Pass system flag to python which

- pipenv/__init__.py
- pipenv/resolver.py
Ever since upgrading to pydantic in pipenv, I've had issues running it on windows when its an editable install.   I am not convinced its not an environment issue but I searched far and wide and continued to get:
```
[pipenv.exceptions.InstallError]: Traceback (most recent call last):
[pipenv.exceptions.InstallError]:   File "C:\Users\matte\Projects\pipenv\pipenv\patched\pip\__pip-runner__.py", line 50, in <module>
[pipenv.exceptions.InstallError]:     runpy.run_module("pip", run_name="__main__", alter_sys=True)
[pipenv.exceptions.InstallError]:   File "<frozen runpy>", line 226, in run_module
[pipenv.exceptions.InstallError]:   File "<frozen runpy>", line 98, in _run_module_code
[pipenv.exceptions.InstallError]:   File "<frozen runpy>", line 88, in _run_code …
```
> Fixes issue I've been having running pipenv as an editable install on windows.

- news/5777.bugfix.rst
- pipenv/routines/requirements.py
- tests/integration/test_requirements.py
Fixes #5777 
Restores `pipenv requirements --hash` output to `2023.6.26` behaviour. `2023.7.1` causes `pip` to fail to install with certain types of packages (at a guess, ones with a single hash).
> Keep hashes at the end of generated requirements.txt files

- news/5765.bugfix
- news/5765.bugfix.rst
- pipenv/vendor/requirementslib/models/requirements.py
- tests/integration/test_install_basic.py
Try to fix #5764 
Maybe not the best as it simply revert one line to avoid the crash. I've added a test to validate the fix
I believe there might be a better fix by concatenating a "default operator" to `_pipfile["version"]` before calling the specifier constructor. I am just not sure of the intent of the whole function and which function should add this default operator. 
`Requirement.parse`  function ? 
You have probably more knowledge on this to see if a default operator make sense. At least, we have a base to fix
@matteius Let me know
> Ensure version contains an operator when defined

- news/5784.bugfix.rst
- pipenv/routines/requirements.py
- tests/integration/test_requirements.py
Fixes #5783
Fixes #5780
* Consider extras for pypi or private index packages.
* Consider file and path requirements.
> Fix extras not being included for pypi packages in requirements command

- news/5788.bugfix.rst
- pipenv/routines/requirements.py
Fixes #5786 
use the empty string when the marker is None or null.
> Fix markers being included as None/null

- news/5794.bugfix.rst
- pipenv/utils/toml.py
- tests/integration/test_install_basic.py
We get this when we have subtables that do not
directly follow their parent table.
Fixes: #5794
I think this issue and the fix show that we're way too deep into the tomlkit internals. I think
in the long run it would be much better to try to use a higher level interface... But I really don't
have time to go that deep into the code to find out whether that is even feasible. So for now
the minimal fix.
> utils.toml: Handle tomlkit OutOfOrderTableProxy

- news/5807.bugfix.rst
- pipenv/exceptions.py
- pipenv/routines/check.py
- pipenv/routines/install.py
- pipenv/routines/outdated.py
- pipenv/shells.py
- pipenv/utils/resolver.py
- tasks/vendoring/__init__.py
- tests/integration/test_install_misc.py
- tests/integration/test_install_twists.py
- tests/integration/test_install_uri.py
- tests/integration/test_lock.py
- tests/integration/test_project.py
Fix all ruff warnings.
@matteius should be OK now.
> Fix ruff-complaints

- news/5809.bugfix.rst
- pipenv/environments.py
- pipenv/resolver.py
- pipenv/utils/resolver.py
- pipenv/vendor/requirementslib/models/setup_info.py
Fixes #5803 by restoring the default behavior to run the resolver in the project python sub-process.
Maintain the option to invoke resolver directly (useful for debugging).
> Restore prior resolver default behavior but maintain direct code path for testing resolver.

- news/5812.bugfix.rst
- pipenv/vendor/pythonfinder/__init__.py
- pipenv/vendor/pythonfinder/environment.py
- pipenv/vendor/vendor.txt
Vendor in pythonfinder==2.0.5
Fixes #
> Vendor in pythonfinder==2.0.5

- pipenv/cli/command.py
Continuing with secho removal in favour of rich APIs.
> Remove click.{s,}echo

- docs/advanced.rst
1. `pypi.python.org` now redirects to `pypi.org`, so let's point folks towards that to save them the redirect.
2. Travis CI has struggled mightily ever since they were acquired by a PE firm. Most open source projects have moved away from them.
3. Update the python version in the example so it doesn't look quite so dated.
4. Use the `name` key for `sources` as that's now [required](https://github.com/pypa/pipenv/discussions/5370#discussioncomment-3701061).
I didn't include a news fragment as I thought the changes were too trivial to list.
I also didn't take the time to regenerate the lockfiles after changing the `Pipfile`... that means the hashes are going to be wrong, but for the purposes of docs I think that's fine... no human will notice, and if they do run `pipenv` against the example …
> Some docs cleanups

- docs/installation.md
- docs/virtualenv.md
- news/5129.doc.rst
I was helped by the answer in issue #5123 and the further guidance in issue #5129 
- Added documentation in installation.md under 'Virtualenv' mapping caveat
- Added documentation to the virtualenv.md
This is my first pull request so feedback very welcome.
* [X ] Associated issue
* [ X] A news fragment in the `news/` directory to describe this fix with the extension `.bugfix.rst`, `.feature.rst`, `.behavior.rst`, `.doc.rst`. `.vendor.rst`. or `.trivial.rst` (this will appear in the release changelog). Use semantic line breaks and name the file after the issue number or the PR #.
> Address Issue #5129: Document how to rename (move) project directory 

- news/5722.feature.rst
- pipenv/routines/install.py
- pipenv/utils/pipfile.py
- pipenv/utils/project.py
- pipenv/utils/requirements.py
- tests/integration/test_install_categories.py
Fixes #5722 
changed the `import_requirements()` and related functions to have categories. `--categories` now works with requirements file. whether `-r <req_path>` is provided or not (when only requirements.txt is available)
> Add --categories option to work with requirements txt files

- news/5838.bugfix.rst
- pipenv/cli/command.py
Before:
```
matteius@matteius-VirtualBox:~/pipenv$ pipenv --version
pipenv
, version 2023.8.19
```
After:
```
matteius@matteius-VirtualBox:~/pipenv$ pipenv --version
pipenv, version 2023.8.19
```
We broke the benchmark run because unexpectedly the version output changed formats:. 
https://github.com/lincolnloop/python-package-manager-shootout/actions/runs/5914571940/job/16040022277
> Fix the version output

- news/5841.bugfix.rst
- pipenv/resolver.py
- pipenv/utils/resolver.py
The last release slowed down locking performance due to a major refactor -- this speeds it back up some.  Unfortunately adding cached_property where I want in some places causes failures with multiple index installs, so I deferred those changes for now.
> Some performance optimizations after analyzing benchmarks.

- news/5843.bugfix.rst
- pipenv/utils/dependencies.py
- pipenv/utils/requirements.py
Solves some edge cases:
* vcs sub-requirement has no ref
* old Pipfile or Pipfile.lock that contains a ref in the vcs url.
Fixes #5843 
Fixes #5846
> Do not include @ when no ref is specified

- news/5846.bugfix.rst
- pipenv/utils/dependencies.py
- pipenv/utils/requirements.py
Handle edge case where it is expected ssh:// urls to have at least one @ symbol
Fixes Issue #5849 
I think ssh:// urls require at least one @ and so checking for 2 or more in this case should be sufficient.
> Handle edge case where it is expected ssh:// urls to have at least one @ symbol

- news/5849.bugfix.rst
- pipenv/utils/dependencies.py
- pipenv/utils/requirements.py
Try fixing the other part of #5849 
Sometimes VCS urls have an @ symbol for netloc auth component, try to differentiate if its a valid ref.
> Try to match if the part after @ is a valid ref (reject treating URL parts as refs).

- news/5866.bugfix.rst
- pipenv/project.py
- pipenv/utils/fileutils.py
- pipenv/utils/internet.py
- tasks/vendoring/__init__.py
The else Fallback here is not working right, for example if my source url is: url = "https://download.pytorch.org/whl/cu117" and the page contains url's like: /whl/cu117/torch-2.0.1%2Bcu117-cp310-cp310-linux_x86_64.whl So the url that gets generated is: https://download.pytorch.org/whl/cu117/whl/cu117/torch-2.0.1%2Bcu117-cp310-cp310-linux_x86_64.whl which is wrong because it repeats /whl/cu117/
Fixes #5864
Fixes #5860
Maybe Fixes #5848
Use urllib.parse urljoin which will intelligently handle this case:
```
Downloading file torch-2.0.1+cu117-cp310-cp310-linux_x86_64.whl to obtain
hash...
Downloading file torch-2.0.1+cu117-cp310-cp310-win_amd64.whl to obtain hash...
Downloading file torch-2.0.1+cu117-cp311-cp311-linux_x86_64.whl to obtain
hash...
Downloading file …
```
> Adjust the Fallback logic for obtaining the hashes from private indexes

- .pre-commit-config.yaml
% `pre-commit autoupdate`
```
[https://github.com/pre-commit/pre-commit-hooks] already up to date!
[https://github.com/astral-sh/ruff-pre-commit] updating v0.0.275 -> v0.0.285
[https://github.com/psf/black] updating 23.3.0 -> 23.7.0
[https://github.com/pre-commit/pygrep-hooks] already up to date!
[https://github.com/mgedmin/check-manifest] already up to date!
[https://github.com/abravalheri/validate-pyproject] updating v0.13 -> v0.14
```
% `pre-commit run --all-files`
> pre-commit autoupdate 2023-08-25

- news/5872.bugfix.rst
- pipenv/cli/command.py
- pipenv/utils/funktools.py
Fix how format_help is used.
Because it uses `click.echo` color strings, one should not use `console.print`.
Fix #5869 
Fix #5850
> Fix usage of format_help

- pipenv/project.py
- pipenv/utils/dependencies.py
- pipenv/utils/funktools.py
- tests/integration/test_install_uri.py
Attempt to fix the local/editable file installs which broke when we refactored away from requirementslib.
Fixes (??) Issue #5858
> Attempt to fix the local/editable file installs

- pipenv/resolver.py
- pipenv/utils/resolver.py
Without caching, the Resolver duplicates the sources listed in the `Pipfile` multiple times (since the property re-adds them every time they're called) in the arguments sent to the `pip` parser.
Removing unused command-line option `--debug`
While diagnosing another issue, I found through `print` debugging that the multiple calls to these properties, `pip_args` and `pip_options`, ended up duplicating the sources listed in the `Pipfile` multiple times for the `pip` parser.
Related to the resolver, the `--debug` command-line option for `pipenv-resolver` is unused.
To fix this, I replaced `property` decorator with `cached_property`, which was already imported in the module. As best as I can tell, these properties (and a number of other ones) only need to …
> Caching properties to deduplicate sources

- news/5878.bugfix.rst
- pipenv/utils/resolver.py
Fixes #5878 
Fixes #5880 
Reverts the change that is believed to have caused this per https://github.com/pypa/pipenv/issues/5878#issuecomment-1695759815
> Revert change that caused the credentials in source url issue

- news/5885.bugfix.rst
- pipenv/project.py
- pipenv/utils/constants.py
- pipenv/utils/dependencies.py
- pipenv/utils/locking.py
In the refactor away from requirementslib, I incorrectly made an assumption that if the install line is found as a relative file path that its intended as an local file install, but this broke for cases where the file or directory name matched the named package to be pulled from a package index.
Editable installs will need to be specified by passing the editable: true or -e arg, and not inferred.
> Assorted local editable file file fixes

- .pre-commit-config.yaml
- pipenv/environment.py
- pipenv/environments.py
- pipenv/project.py
- pipenv/resolver.py
- pipenv/routines/graph.py
- pipenv/routines/install.py
- pipenv/routines/lock.py
- pipenv/utils/environment.py
- pipenv/utils/fileutils.py
- pipenv/utils/funktools.py
- pipenv/utils/locking.py
- pipenv/utils/markers.py
- pipenv/utils/pip.py
- pipenv/utils/pipfile.py
- pipenv/utils/requirementslib.py
- pipenv/utils/resolver.py
- pipenv/utils/shell.py
- pipenv/utils/toml.py
- pipenv/utils/virtualenv.py
- tasks/vendoring/__init__.py
- tests/integration/conftest.py
- tests/integration/test_dot_venv.py
- tests/integration/test_install_basic.py
- tests/integration/test_install_markers.py
- tests/integration/test_lock.py
- tests/integration/test_pipenv.py
- tests/integration/test_project.py
- tests/integration/test_uninstall.py
Some code simplifications made by `ruff --select=SIM --fix .`
* https://beta.ruff.rs/docs/rules/#flake8-simplify-sim
How does this pull request fix your problem? Did you consider any alternatives? Why is …
> ruff rules SIM

- news/5897.bugfix.rst
- pipenv/resolver.py
Fixes #5854
Set the resolver pipenv log level to WARN when verbose is not passed.
> Set log level in resolver to WARN when verbose is not passed

- news/5895.bugfix.rst
- pipenv/patched/pip/_internal/models/search_scope.py
- pipenv/utils/resolver.py
- tasks/vendoring/patches/patched/pip_index_safety.patch
- tests/integration/test_install_uri.py
- tests/integration/test_lock.py
A while back I broke install_search_all_sources = True and I've realized this patch.
Search scopes gets used for resolver and installer, but install we invoke pip interface.   This gives a way to ensure index restricted packages for the resolver, but bypass that during install.
Fixes #5743 
Fixes #5781
> Apply patch for install_search_all_sources = True

- Pipfile
- Pipfile.lock
Landing these two Python dependencies should make pull request #5836 easier to complete.
* https://pypi.org/project/build
* https://pypi.org/project/twine
@kalebmckale Your review, please.
> Pipfile: Add build and twine

- news/5898.bugfix.rst
- pipenv/project.py
Fixes #5894
I installed a local nexus server, uploaded packages and explored how the index is laid out, and then refactored the hash collector to work with both this and the pytorch style index.
Handles other edge cases around package names with dots.
> Handle more variations in private index html to improve hash collection

- Pipfile
- Pipfile.lock
- news/5892.feature.rst
- pipenv/utils/markers.py
- pipenv/utils/resolver.py
I want transitive platform locking to work better.
By following the resolution chain (where the package came from) we can get back to the Pipfile entry and apply the same sys_platform markers the user intended.
Additionally add a top level platform_machine specifier that works the same way.
Note:  Adding directly to the markers will behave different with the pip resolver than adding them as distinct specifier keys in the Pipfile.
> Top level Pipfile sys_platform markers should be transitive

- docs/configuration.md
- pipenv/environments.py
- pipenv/project.py
Please refer to [#5877](https://github.com/pypa/pipenv/pull/5877)
When I was using pipelinev in an environment with network issues, I needed to increase the timeout setting for the connection to complete properly, but I found that the default behavior was set to 10 seconds and could not be changed, so I increased it.
Add a new ENV config for timeout, so that user can change it.
> Add PIPENV_REQUESTS_TIMEOUT and use it for requests session (Re-send due to force push)

- .github/workflows/ci.yaml
- .github/workflows/ruff.yml
- .pre-commit-config.yaml
- pyproject.toml
Ensure that this repos `pyproject.toml` file is formatted like others.
Also:
* `pre-commit autoupdate`
* Upgrade to `actions/checkout@v4`
* Lint on the current version of Python
* Tests on Python 3.12 are failing on Linux, macOS, and Windows.
* https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#allow-pre-releases
Add `pyproject-fmt` to our pre-commit processing.
* https://pyproject-fmt.readthedocs.io
> pre-commit: Add pyproject-fmt

- news/5905.bugfix.rst
- pipenv/utils/dependencies.py
Fixes #5904 
Consider more edge cases in the setup.py ast parser and encourage more people to move away from complicated setup.py
> Handle case where setup name is referencing a variable that is a string

- news/5920.bugfix.rst
- pipenv/routines/install.py
Fixes #5912 
Include the Pipfile markers in the install phase when using `--skip-lock`
> include markers when skipping lock

- .github/workflows/ci.yaml
- tests/integration/test_install_categories.py
The 3.7 tests are failing because the recent lock adjustments and packages we depend on dropped 3.7, but it only affects the test runner for now -- we will pursue https://github.com/pypa/pipenv/pull/5879 soon since the latest rounds of bug fixes after the last major refactor are almost complete/stabilized.
Drop 3.7 from test CI
> Drop 3.7 test runner

- news/5919.bugfix.rst
- pipenv/utils/dependencies.py
We definitely don't want relative one directory to be treated as package name and pip documentation does not provide much guidance on this.
Fixes #5917 
If the path is not absolute, ensure it is prepended with ./ so it is treated as an installable path by pip (and not a named requirement) -- also handle the specification of extras with local file installs.
> Better handling of local file install edge cases; handle local file extras

- news/5921.bugfix.rst
- pipenv/project.py
- pipenv/routines/install.py
- pipenv/routines/outdated.py
- pipenv/routines/uninstall.py
- pipenv/routines/update.py
- pipenv/utils/dependencies.py
- pipenv/utils/locking.py
- pipenv/utils/resolver.py
* Fallback to default vcs ref when no ref is supplied
* More proactively determine package name from the pip line where possible, fallback to the existing file scanning logics when unable to determine name.
There are so many edge cases of trying to get the package name from setup.py and surprisingly many packages still rely on it.   A great example is requests:  https://github.com/psf/requests/blob/main/setup.py
In the requests setup.py example, the name comes from reading another file on the filesystem, and the ast parser will never be able to accomplish that.   Prior to this change, it was not possible to install the requests vcs into the Pipfile without manually creating the Pipfile entry with the correct package name and locking. 
Fixes issue #5857 
Allow not supplying a default ref …
> Fallback to default vcs ref and determine package name from the pip line where possible

- news/5926.bugfix.rst
- pipenv/utils/resolver.py
ignore_compatibility was supposed to default to False, collect hashes already passes True.
Fixes #5924 
* [] A news fragment in the `news/` directory to describe this fix with the extension `.bugfix.rst`, `.feature.rst`, `.behavior.rst`, `.doc.rst`. `.vendor.rst`. or `.trivial.rst` (this will appear in the release changelog). Use semantic line breaks and name the file after the issue number or the PR #.
> ignore_compatibility was supposed to default to False

- pipenv/resolver.py
- pipenv/utils/dependencies.py
- pipenv/utils/resolver.py
- tests/unit/test_utils.py
Specifying the package name with `name @ requirement` works for some things, but that information is lost the way the data is passed to the resolver currently.   This updates the constraints file to have req_name, pip_line format.
Improvements for the case of #5904
> Include the package name in the information to the resolver

- news/5934.bugfix.rst
- pipenv/utils/dependencies.py
- pipenv/utils/locking.py
- pipenv/utils/requirements.py
- tests/integration/test_lockfile.py
Fixes issue #5934
urllib urlparse has to be better at separating netlocs from the remaining path than I can do.
> Solving slashes or other less usual symbols in vcs refs were not being interpreted correctly.

- docs/advanced.md
- docs/pipfile.md
- docs/shell.md
- docs/workflows.md
I believe during the conversion from `.rst` to `.md` a minor typo was introduced on the link for `python-dotenv` repo on [pipenv docs](https://pipenv.pypa.io/en/latest/shell/#automatic-loading-of-env)
Remove the extra `>`
> **_ps._**: Since this typo was observed, I took the liberty to `grep` the repo and see if there were similar cases. I found three more that seemed relevant. Note that in the TOML case, the `Spec` header was moved from the `READ.md` into their docs
> Update some external links on the docs

- examples/Pipfile.lock
- news/5941.bugfix.rst
There is a security vulnerability for `certifi` versions <2023.7.22 (see details here: [CVE-2023-37920](https://nvd.nist.gov/vuln/detail/CVE-2023-37920)). Even though this version is only in /examples, it gets detected and flagged by static analysis tools when scanning docker images that have the latest version of pipenv installed.
Related issue: https://github.com/pypa/pipenv/issues/5940
Update `certifi` in `/examples` to address the issue
> Bump certifi from 2023.5.7 to 2023.7.22 in /examples

- pipenv/environment.py
req.link is of type InstallRequirements which can be None. Return False (requirement not met) if this is the case.
Fix issue #5950. 
`req` is of type `InstallRequirements`, which has an optional attribute `link` which can be `None`. However, attributes of `req.link` are accessed directly.
Catch if `req.link` is `None` and return `False` (requirement not met) before attributes of `req.link` are accessed.
> Catch req.link = None

- .github/workflows/ruff.yml
- news/5983.trivial.rst
Ruff linter had stopped working due to a deprecated argument being used in our CI.
This PR aims to fix #5983
In our GitHub actions for Ruff linter, we use the new option of `--output-format` instead of deprecated "--format"
> ci: fix ruff linter

- docs/advanced.md
The docs header "Automatic Python Installation" was inadvertently removed in https://github.com/pypa/pipenv/pull/5909. 
Added it back in, where it was before.
N/A, this just corrects a docs typo.
P.S.: I did notice the docs search still identified "Automatic Python Installation" as a heading when e.g. searching for "pyenv", even though it no longer appeared. Is there some search index that should be regenerated?
> Update advanced.md to restore Automatic Python Installation header

- Makefile
- news/5879.removal.rst
- pipenv/environment.py
- pipenv/utils/project.py
- pipenv/utils/resolver.py
- pipenv/utils/shell.py
- pyproject.toml
- run-tests.sh
- tests/integration/conftest.py
Drop support for Python 3.7
It's obvious
> Drop support for python3.7

- news/5969.behavior.rst
- pipenv/cli/command.py
#5969 
Similar to `do_where(bare=True)`, the PR adds the argument `bare=False` to `do_py` and calls it with `bare=True`.
Like `--venv`, it will use `print` instead of `console.print`. (`do_where` uses `click.echo`)
> Change `--py` to use `print` instead of `console.print`

- docs/pipfile.md
- pipenv/project.py
- tests/integration/test_install_basic.py
- tests/integration/test_uninstall.py
- tests/integration/test_upgrade.py
Add a new `[pipenv]` directive to sort package names alphabetically inside the category, for easier reading.
--
Unsure if this is the best place or way to implement. Small prototype to add to discussion in https://github.com/pypa/pipenv/issues/5964 .
Tests:
before patch:
```
AssertionError: assert ['atomicwrite...ama', 'build'] == ['atomicwrite...', 'colorama']
At index 1 diff: 'colorama' != 'build'
Full diff:
- ['atomicwrites', 'build', 'colorama']
?                  ---------
+ ['atomicwrites', 'colorama', 'build']
?                            +++++++++
```
after patch: pass.
------
> Sort packages alphabetically inside each category

- pipenv/project.py
For https://github.com/pypa/pipenv/issues/5964
As suggested in https://github.com/pypa/pipenv/pull/5965
We don't need to cast to `dict` first, we can just sort.
> Simplify sorting code

- news/5994.bugfix.rst
- pipenv/project.py
- pipenv/utils/internet.py
See https://github.com/pypa/pipenv/issues/5751#issuecomment-1773922272 and ramblings thereafter
Prior to this fix, `pipenv lock` would work, but with warnings because some calls within pipenv correctly used keyring, but others didn't:
> Locking [packages] dependencies...
> Building requirements...
> Resolving dependencies...
> Success!
> [====] Locking...Warning: WARNING:pipenv.patched.pip._internal.network.auth:Keyring is skipped due to an exception: expected str, bytes or os.PathLike object, not NoneType
> Locking [dev-packages] dependencies...
> Building requirements...
> Resolving dependencies...
> Success!
> [ =] Locking...Warning: WARNING:pipenv.patched.pip._internal.network.auth:Keyring is skipped due to an exception: expected str, bytes or os.PathLike object, not NoneType
With …
> Pass through pipfile index urls when creating https session so that keyring fully works

- news/6011.bugfix.rst
- pipenv/utils/dependencies.py
- tests/integration/conftest.py
- tests/integration/test_install_twists.py
- tests/integration/test_install_uri.py
Fixes #6011 and probably also another issue where local file installs on windows are on a different drive.
> Fix issue-6011 direct file url path

- pipenv/project.py
- tests/integration/test_dot_venv.py
Hi !
I have a project installed on my host (macOS) which use the `PIPENV_VENV_IN_PROJECT=1` env vars to install pipenv deps into `my_project/.venv` folder. Now I am working on a docker-compose setup, which has another Python version, with the local project bind mounted into the container.
In the Dockerfile, I am only copying Pipfiles and running `pipenv install` with `PIPENV_VENV_IN_PROJECT=0` so that the venv is built specifically for this container env and embedded in the docker image.
With my local code mounted inside the container, alongside the host `.venv`, I was expecting `pipenv` commands to follow `PIPENV_VENV_IN_PROJECT=0` set inside the container context and ignore the mounted `.venv`.
Turns out, it is not working even though the documentation clearly states:
``` …
```
> Ignore existing venv dir when PIPENV_VENV_IN_PROJECT is false

- news/6017.bugfix.rst
- pipenv/utils/dependencies.py
- tests/integration/test_install_twists.py
> Treat all return paths of this method as strings

- .github/workflows/pypi_upload.yml
Fixes #6015 
By changing the release creation action from the archived, no longer receiving updates version to a new, updated and working version.  The [releases look the same as here](https://github.com/stumpylog/pipenv/releases) with the new version.  All the actions run without warnings now:
- CI: https://github.com/stumpylog/pipenv/actions/runs/6960511112
- Upload: https://github.com/stumpylog/pipenv/actions/runs/6960554210
Obviously with failures as I can't push to PyPi, but it gets far enough to see no warnings
Not sure a simple update like this is worth of a news fragment?
> Chore: Resolve CI deprecation warnings

- README.md
Fit the issue #6022 
Add additional installation method in README.
> Fix the issue(#6022): Add additional installation method in README

- news/6021.bugfix.rst
- pipenv/project.py
Running pipenv with a `Pipfile` using a source without a name, like
```
[[source]]
[dev-packages]
"flake8" = "*"
mypy = "*"
pydocstyle = "*"
pylint = "*"
twine = "*"
[packages]
aiodns = "*"
aiohttp = "*"
async-timeout = "*"
```
results in a missing key error:
```
File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pipenv/resolver.py", line 675, in <module>
main()
File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pipenv/resolver.py", line 661, in main
_main(
File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pipenv/resolver.py", line 645, in _main
resolve_packages(
File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pipenv/resolve …
```
> Make `project.get_default_index()` populate a default name

- tests/integration/test_cli.py
Safety test for some reason is picking up an old pip version.
Ensure the test itself upgrades pip.
> Fix for the safety test failure in the CI

- news/6008.bugfix.rst
- pipenv/utils/requirements.py
If there are markers specified in requirements.txt they are not currently transferred to Pipfile while generating it. This commit adds markers to Pipfile as defined in requirements.txt
Using Pipenv with requirements.txt fails when generating Pipfile if there are markers defined in requirements.txt and those markers are for example specifying diffrent os.  For example this requirements.txt:
`windows-curses==2.3.1 ; sys_platform == 'win32' and python_version == '3.11'`
When run under Linux OS with:
`pipenv install -r requirements.txt`
Throws the following error:
```CRITICAL:pipenv.patched.pip._internal.resolution.resolvelib.factory:Could not find a version that satisfies the requirement windows-curses==2.3.1 (from versions: none)
[ResolutionFailure]:   File …
```
> Add markers to Pipfile when parsing requirements.txt

- news/6056.bugfix.rst
- pipenv/patched/pip/_internal/resolution/resolvelib/factory.py
- pipenv/utils/resolver.py
- tests/integration/test_lock.py
Fix a bug with locking projects that contains packages with non canonical names from private indexes
More details here:
https://github.com/pypa/pipenv/issues/6056
* [ X] Associated issue
* [X ] A news fragment in the `news/` directory to describe this fix with the extension `.bugfix.rst`, `.feature.rst`, `.behavior.rst`, `.doc.rst`. `.vendor.rst`. or `.trivial.rst` (this will appear in the release changelog). Use semantic line breaks and name the file after the issue number or the PR #.
* [] Send a fix to pip ?
> Fixed a bug with locking packages with non canonical names

- news/6069.bugfix.rst
- pipenv/utils/dependencies.py
> Only editable entry should trigger editable installs

- pipenv/project.py
> Check for name attribute in source parameter.

- pipenv/cli/command.py
Ran into this issue when attempting to activate pipenv environments using pwsh on mac. I'm not 100% sure this is the correct solution as the [documentation](https://docs.pipenv.org/basics/#about-shell-configuration) for fancy mode is sparse, but it seems the code enforces fancy mode if running on windows (because it's assumed it's pwsh?)
Definitely looking for some feedback. Thanks.
Issue is described in https://github.com/pypa/pipenv/issues/6107
Defaulting to fancy mode for pwsh on *nix
> Use fancy mode for pwsh on *nix (draft)

- news/6136.bugfix.rst
- pipenv/utils/locking.py
- tests/integration/test_lock.py
When installing a package that has a vcs dependency with a subdirectory, the subdirectory isn't added to the Pipfile.lock.
This is a tentative fix for #6120
When formatting the vcs requirement for lockfile in `format_requirement_for_lockfile`
- `normalize_vcs_url` to clean the vcs's url as is done in `install_req_from_pipfile` - this removes the fragments from the url
- Inspect and add the `req.link.subdirectory_fragment` to the lockfile if parsed by the `Link` object
As discussed in #6120, alternatives could have been to honor #4259 and work on the install portion to be able to resolve correctly the Pipfile entry with the `subdirectory` as a vcs url fragment.
> Add nested vcs dependency subdirectory when locking to Pipfile.lock (Fix #6120)

- Pipfile
- Pipfile.lock
Fixes #6137
No news fragment required as its our own internal pipfile.
> pipenv upgrade invoke -d

- news/6126.bugfix.rst
- pipenv/routines/check.py
This PR fixes issue #6126 
I have added additional check of presence of lockfile in pipenv check command so that it doesn't fails if Pipfile.lock is not present.
> Fix the issue(#6126): add lockfile_path presence in pipenv check command

- news/6156.feature.rst
- pipenv/cli/command.py
- pipenv/routines/requirements.py
- tests/integration/test_requirements.py
This is an enhancement of subcommand regards to https://github.com/pypa/pipenv/issues/6130
`pipenv requirements --from-pipfile` subcommand supports delimination of subpackages when command executed.
- Add `--from-pipfile` flag
- Load explicitly mentioned packages in Pipfile and initialize new set called `pipfile_root_package_names`
- If flag is True, add packages in deps only if the name is in `pipfile_root_package_names`
> Add --from-pipfile subcommand to `pipenv requirements`

- news/6139.bugfix.rst
- pipenv/environment.py
- pipenv/vendor/importlib_metadata/__init__.py
- pipenv/vendor/importlib_metadata/_adapters.py
- pipenv/vendor/importlib_metadata/_compat.py
- pipenv/vendor/importlib_metadata/_meta.py
- pipenv/vendor/importlib_metadata/compat/py39.py
- pipenv/vendor/importlib_metadata/diagnose.py
- pipenv/vendor/vendor.txt
Fix windows CI for 3.8 and the outdated command that was refactored to remove pkg_resources.
> Fix windows CI for 3.8 and the outdated command that was refactored to remove pkg_resources.

- news/6164.bugfix.rst
- pipenv/utils/virtualenv.py
- tests/integration/test_install_basic.py
This is a bug fix of Pipfile [requires] regards to https://github.com/pypa/pipenv/issues/6144
Pipenv only supports absolute python version. If the user specifies a Python version with inequality signs like >=3.12, <3.12 in the [requires] field, the code has been modified to explicitly express in an error log that absolute versioning must be used.
- Add protection logic to parse python verison on Pipfile.
- Enhance error log that absolute versioning must be used.
- Add test codes.
> Handle unsupported python versioning on Pipfile

- pipenv/vendor/plette/__init__.py
- pipenv/vendor/plette/models/scripts.py
- pipenv/vendor/vendor.txt
This fixes breakage on files which use scripts callable.
https://github.com/pypa/pipenv/issues/6173
> Update plette to version 2.1.0

- pipenv/routines/install.py
Given the correct CLI arguments and project, pipenv will show the following message:
```
Pipfile.lock (abcdef) out of date, but installation uses --system sore-building lockfile must happen in isolation. Please rebuild lockfile in a virtualenv.  Continuing anyway...
```
Add the missing space between "so" and "re-building".
_Since this is just a typo, I did not create an issue and I did not create a news, but let me know if you want me to do so._
> Fix typo missing space between "so" and "re-building"

- pipenv/project.py
Swap click for rich library
replace `click.echo` and `click.secho` calls in:
pipenv/project.py
continuation of click to rich migration.
@oz123
> remove all instances of click from project.py

- .github/workflows/pypi_upload.yml
- news/6177.bugfix.rst
- tasks/release.py
Automatic bump of the version in CI after release was broken mistakenly.
This should fix the issue.
> Fix bump version in CI

- .github/ISSUE_TEMPLATE/Bug_report.md
The URL to the diagnose page seems to have changed and is a broken link in the issue template.
> Update diagnose URL in issue template

- news/6178.vendor.rst
- pipenv/exceptions.py
- pipenv/utils/__init__.py
- pipenv/utils/shell.py
- pipenv/utils/virtualenv.py
- tests/integration/test_install_basic.py
Replace in shell.py and virtualenv.py.
Also, replace in some exceptions.
This is continuing my previous work in attempt to remove click in favor of rich.
@aidencullo
> refactor: click styling-> rich

- news/6202.bugfix.rst
- pipenv/cli/command.py
dot env is always globally loaded.
Fix #6198
> Fix: dont call load dot env in shell sub command

- news/6182.vendor.rst
- pipenv/cli/command.py
- pipenv/cli/options.py
- pipenv/utils/__init__.py
- pipenv/utils/display.py
We want to remove vendored click library as it is sizable and much of its functionality can be done with rich already.
replace `click.echo` calls in:
pipenv/cli/command.py
pipenv/cli/options.py
replace `click.style` calls in:
pipenv/utils/display.py
This will not remove all uses of click library in pipenv/cli, this is part of an incremental transition from click to rich.
@oz123
> Remove click.echo from pipenv/cli

- news/6197.bugfix.rst
- pipenv/shells.py
Add some cosmetic change to the comments.
Basically, all the work was done by @JoshStern.
See #6212 .
> Linuxbrew shell fix

- news/6216.vendor.rst
- pipenv/exceptions.py
Click library is large and rich does the same thing.
replace click.echo calls in:
pipenv/exceptions.py
@oz123
> remove all click.echo calls from exceptions.py

- news/6207.bugfix.rst
- pipenv/cli/command.py
- pipenv/routines/lock.py
More work needs to be done to respect the quiet state across utilities, which may mean studying up on how we track command state -- I don't want to just extend all the utilities to have a quiet parameter for example.   Anyway, this should fix the issue reported where quiet does not write the lock file changes.
Fixes #6207
> Solve issue with quiet lock not writing the lock file.

- news/6179.bugfix.rst
- pipenv/routines/outdated.py
The old and new versions of packages reported by `pipenv update --outdated` are swapped.
> Swap old_version and new_version in `pipenv update --outdated` output

- news/6209.bugfix.rst
- pipenv/routines/uninstall.py
- pipenv/utils/virtualenv.py
- tests/integration/test_uninstall.py
When I recently refactored the uninstall command behavior to be smarter, I broke the expected behavior of `--all` flag.
Specifically there should not be removal from the Pipfile and the do_purge logic should be invoked (it wasn't after my change).
Fixes #6200
> Corrected behavior of uninstall --all

- news/6222.bugfix.rst
- pipenv/utils/dependencies.py
- pipenv/utils/requirements.py
Fixes #6221 
Local file installs were not considering if user wanted it marked editable.   This was a regression, that seems like it has been long standing at this point.
> Correct for local package installs always being treated as editable.

- news/6225.bugfix.rst
- pipenv/routines/install.py
Fixes Issue #6189 
It would appear my refactor to the behavioral install changes in `2024.0.1` broke the `--skip-lock` flag.
```
$ pipenv install --skip-lock
The flag --skip-lock has been reintroduced (but is not recommended).  Without the lock resolver it is difficult to mana
provided.  However it can help manage installs with current deficiencies in locking across platforms.
Creating a virtualenv for this project
Pipfile: C:\Users\matte\Projects\pipenv-triage\issue-6189\Pipfile
Using default python from C:\Users\matte\AppData\Local\Programs\Python\Python311\python.exe3.11.2 to create virtualenv.
[   =] Creating virtual environment...created virtual environment CPython3.11.2.final.0-64 in 2742ms
creator CPython3Windows(dest=C:\c\users\matte\.virtualenvs\issue-6189-08vX2LT8, clear=False, …
```
> Corrected behavior of `pipenv install --skip-lock`

- pipenv/resolver.py
- pipenv/utils/resolver.py
And also remove hack to make it available for python3.7.
Pipenv does not support py37 for quite a while now.
> Remove import of cached_property from pip

- news/6235.vendor.rst
- pipenv/vendor/importlib_metadata/__init__.py
- pipenv/vendor/importlib_metadata/_adapters.py
- pipenv/vendor/importlib_metadata/_itertools.py
- pipenv/vendor/importlib_metadata/compat/py311.py
- pipenv/vendor/vendor.txt
Just another round of bumping vendored libs.
> vendor: bump importlib-metadata to 8.4.0

- pipenv/shells.py
I introduced a silly bug - with some major consequeces - in #6215.
First, I forgot to include brackets in `endswith`. Second, I added a "/" as if the command should be `/bin/bash` or `/usr/bin/bash`, which in Windows will be '/'. This is actually not needed and detecting the shell based on the last word (the command) without the path, should be fine on all OSs.
> Fix shell detection

- .github/workflows/ci.yaml
- .pre-commit-config.yaml
- Pipfile
- Pipfile.lock
- news/6240.bugfix.rst
- news/6240.feature.rst
- pipenv/utils/fileutils.py
- pipenv/utils/funktools.py
- pipenv/utils/indexes.py
- pipenv/utils/resolver.py
- pyproject.toml
- tests/integration/test_cli.py
* Initial support for python3.13
* Fixes #6232
> Add initial support for python 3.13

- pipenv/utils/resolver.py
Further removal for click.echo from pipenv modules.
> remove click echo from utils.resolver

- pipenv/utils/virtualenv.py
Fixes this issue which I've created: closes #6245.
Trying to install a library results in an error.
How does this pull request fix your problem? Did you consider any alternatives? Why is this the *best* …
> Fix logging error

- .pre-commit-config.yaml
- news/6243.bugfix.rst
- pyproject.toml
> potentially resolving issue 6205

- news/6151.bugfix.rst
- pipenv/routines/install.py
When running `pipenv install -r requirements.txt`, a warning (`ResourceWarning: unclosed file`) is shown to users. 
This warning comes from temporary directories that will be cleared on program exit, and is therefore not meaningful to the user.
Ignore the warning.
Fixes #6151
Fixes #6155
> Ignore resource warning

- news/6185.bugfix.rst
- pipenv/environment.py
- pipenv/routines/uninstall.py
- tests/integration/test_uninstall.py
This is a regression where `pipenv uninstall --all` fails when the venv does not exist.
Add a check to make sure the environment is valid (venv exists).
ref #6185
> Fix uninstall --all fails when venv is deleted

- news/6256.bugfix.rst
- pipenv/utils/dependencies.py
- tests/integration/test_install_vcs.py
- tests/unit/test_dependencies.py
I was overzealous with the cleaning the VCS URL in https://github.com/pypa/pipenv/pull/6242 -- this reverts the part of the change that cleans the lock file version, and just leaves the extraction for the Pipfile version (which I believe resolves both the prior and this issue).
Fixes #6256
> Preserve uncleaned VCS URL in the lock file.

- tests/integration/test_install_basic.py
- tests/integration/test_install_vcs.py
I wasn't expecting the windows CI to barf on my new test -- so now I made adjustments and it passes on windows locally but need to check if mac/ubuntu still passes.
> Fix new vcs test on Windows

- pipenv/utils/virtualenv.py
Missing spaces and broken f string in virtualenv.py
Adds the spaces and fixes the f
> Fix strings in virtualenv.py

- pipenv/environment.py
> Updated logic for determining available python version string.

- pipenv/utils/requirementslib.py
This PR addresses a couple of areas in the code where improvements in argument handling and path management were needed.
This PR does not fix a specific GitHub issue but addresses overall code quality.
Removed an extra space after -i, added some mini docstrings, improved the path handling logic.
> Some improvemets in requirementslib for clarity

- news/6295.bugfix.rst
- pipenv/routines/install.py
- tests/integration/test_install_basic.py
Fix the --system without --deploy flag bug
Fixes #6295 
Fixes #6296 
Recent refactor did not consider the `--system` flag without `--deploy`, in part because we were missing a test for it.
Adds test for it.
> Fix the --system without --deploy flag bug

- pipenv/project.py
- pipenv/utils/locking.py
- tests/integration/test_install_vcs.py
Take II on not ending up with dep_name @ vcs_url in the vcs key of the lockfile.
> Fix breakage that was almost released

- CHANGELOG.md
- news/6304.bugfix.rst
- pipenv/routines/install.py
- tests/integration/test_install_twists.py
correct regression in --skip-lock being passed the lockfile categories for the Pipfile categories and not finding anything.
Fixes #6301 
We were using the wrong pipfile categories with `--dev` flag (lockfile categories instead of pipfile) -- its a shame those two name groups differ.
> correct regression in --skip-lock

- news/6307.bugfix.rst
- pipenv/vendor/pipdeptree/__main__.py
Closes #6305
Making sure the new paths were added to the front of `PATH` resolved the error for me.
> Add new paths to front of PATH

- news/6306.bugfix.rst
- pipenv/project.py
- pipenv/routines/install.py
- pipenv/routines/update.py
- tests/integration/test_install_basic.py
- tests/integration/test_install_vcs.py
Prevent regression with install upgrading packages; duplicated sources in Pipfile prevention
Fixes #6306
> Prevent regression with install upgrading packages; duplicated sources in Pipfile prevention

- news/6327.bugfix.rst
- pipenv/shells.py
Running "pipenv shell" on MacOS in Powershell (pwsh) references incorrect Activate.ps1
issue link: https://github.com/pypa/pipenv/issues/6318 
Fix file path by removing the dot in `shells.py`
> Fix File path by removing the dot

- news/6329.bugfix.rst
- pyproject.toml
The license declaration is incompatible with PyPI (and some licence checkers like trivy). If the licence is not set correctly, it's not possible to check it. Secondly, it doesn't look so nice on PyPI.
fix the license declaration in pyproject.toml
> Fix license declaration

- news/6318.bugfix.rst
- pipenv/shells.py
Running "pipenv shell" on MacOS in Powershell (pwsh) references incorrect Activate.ps1
Adds a check for os.name and removes the extra '.' before the extension
> Fix activate path for pwsh on MacOS

- news/6321.bugfix.rst
- pipenv/shells.py
`repr(shell)` does not currently work properly - it is missing the `f` for a formatted string, and it's missing the `args` field.
It fixes that.
> Fix repr(Shell)

- pipenv/resolver.py
- pipenv/utils/resolver.py
> fix: correct printing of errors

- pipenv/exceptions.py
- pipenv/utils/resolver.py
Also, exist the program immediately.
For example:
```
$ pipenv install bottle==0.16.0
Installing bottle==0.16.0...
Installation Succeeded
Installing dependencies from Pipfile.lock (2110f5)...
All dependencies are now up-to-date!
Upgrading bottle==0.16.0 in  dependencies.
Building requirements...
Resolving dependencies...
✘ Locking Failed!
⠼ Locking
packages...CRITICAL:pipenv.patched.pip._internal.resolution.resolvelib.factory:Could
not find a version that satisfies the requirement bottle==0.16.0 (from
versions: 0.4.3, 0.4.4, 0.4.6, 0.4.7, 0.4.8, 0.4.9, 0.4.10, 0.4.11,
0.4.12, 0.4.13, 0.4.14,
0.5.3, 0.5.4, 0.5.6, 0.5.7, 0.5.8, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4,
0.6.5, 0.6.6, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.9.1, 0.9.2, 0.9.3,
0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.10.1, 0.10.2, 0.10.3, …
```
> fix: when a resolution is failed show a helpful error

- pipenv/environments.py
There is a small typo in the documentation where "it's" is incorrectly used instead of "its" in a comment. 
This is not associated with an open issue, but it's a minor fix to improve clarity and correctness in the documentation.
This pull request corrects the typo by replacing: 
```
#: Location for Pipenv to store it's package cache.
```
with
```
#: Location for Pipenv to store its package cache.
```
Since "it's" is a contraction of "it is," the correct possessive form "its" should be used. This fix ensures grammatical correctness in the comment.
> Fix typo in documentation for PIPENV_CACHE_DIR

- .github/workflows/ci.yaml
- .pre-commit-config.yaml
- pipenv/utils/resolver.py
- pyproject.toml
Fix https://github.com/pypa/pipenv/issues/6298
> Drop py3.8

- pipenv/routines/graph.py
If we can't use pipenv graph, we should not let RuntimeError slip away silently until it hits UnboundLocalError: cannot access local variable 'python_path'.
Fix #6340.
> fix: UnboundLocalError on pipenv graph

- .github/workflows/ci.yaml
- Pipfile
- Pipfile.lock
Use a fixed version of pypi-server instead of the one from git sources.
This version fixed the issues with modern Python versions.
> chore: bump pypi-server version to 2.3.2

- pipenv/utils/environment.py
- pipenv/utils/processes.py
- pipenv/utils/project.py
- tests/unit/test_core.py
Continuing the removal of `click.echo` from the code base in favor of `rich` API.
> Remove click echo from utils

- .pre-commit-config.yaml
- pipenv/environment.py
- pipenv/project.py
- pipenv/utils/dependencies.py
- pipenv/utils/virtualenv.py
- pyproject.toml
Disabling ruff rules  PLR0912 and PLR0913 has disabled the limits on code complexity `ruff.lint.pylint.max-args` (which has now doubled) and `ruff.lint.pylint.max-branches` (which has increased by 14).  Using numbers forces discussion in code reviews about why the increase in complexity is good for the project. Disabling the rules blinds maintainers to pull requests that increase code complexity.  Refactoring functions to make them less complex improves the project's maintainability.
Upgrade to ruff to the current v0.9.3 and also enforce [collapsible-else-if (PLR5501)](https://docs.astral.sh/ruff/rules/collapsible-else-if/#collapsible-else-if-plr5501) for fewer lines and less indentation.
How does this pull request fix your problem? Did you consider …
> Set upper limits on code complexity

- pipenv/environments.py
- pipenv/utils/pip.py
* #6339
#6339 failed to merge cleanly so this pull request fixes to violations of ruff rule PLW1508.
* https://docs.astral.sh/ruff/rules/invalid-envvar-default
> Fixes for ruff rule PLW1508

- README.md
Fix: Added missing punctuation in the README file
What was done:
In the README file, I corrected a minor punctuation issue by adding a period at the end of a sentence that was previously missing one. The sentence affected was:
"Or, some users prefer to use Python pip module".
Now it ends with a period: "Or, some users prefer to use Python pip module."
Why it's important:
This fix is part of maintaining proper grammar and readability in the documentation, ensuring it adheres to standard punctuation practices.
> docs: fix minor punctuation in README

- news/6737.bugfix.rst
- pipenv/environment.py
- pipenv/project.py
- pipenv/routines/shell.py
- pipenv/utils/virtualenv.py
- tests/unit/test_utils.py
This pull request refactors the logic for determining the venv's `scripts/`. or `bin/` directory location by leveraging `sysconfig`’s built-in mechanism for retrieving the complete global install directory path of scripts and retrieving its basename. This removes any platform-dependent logic and does not require an additional dependency.
Changes:
feat: Introduced a new approach for venv scripts path lookup, eliminating reliance on platform identifiers and improving compatibility with POSIX-like environments such as Cygwin and MinGW.
refactor: Updated both project-wide and routine-specific implementations to use the virtualenv mechanism for dynamic script location lookup, streamlining execution.
These changes mitigate execution inconsistencies in non-native Windows environments and improve …
> Refactor virtualenv `bin/` / `Scripts/` path resolution using `sysconfig` mechanism

- news/6322.bugfix.rst
- pipenv/shells.py
When using PowerShell in Windows, executing `pipenv shell` inside a UNC path (such as a SMB share) will cause a `CMD.EXE` error to be thrown, and a change to an incorrect CWD (normally, `C:\Windows`)
By disabling the shell functionality of `subprocess.call`, this is avoided.
On Windows, when this parameter is set to true, causes an intermediate `CMD.EXE` to be spawned between Python and PowerShell, which does not support the UNC path, causing the wrong CWD to be presented to the final PowerShell shell.
> Fix launching PowerShell on UNC paths

- news/6380.bugfix.rst
- pipenv/utils/markers.py
- tests/integration/test_install_markers.py
> Solve case when the the version is not in the MAX_VERSIONS

- news/6381.bugfix.rst
- pipenv/utils/dependencies.py
- tests/integration/test_install_paths.py
> Fix bug with paths with spaces

- news/6378.bugfix.rst
- pipenv/routines/update.py
- tests/integration/test_install_misc.py
I apparently broke the star specifier on CLI one of the last releases when I was working on making the upgrade logic better at figuring out which dependencies actually needed upgrading.
Also Fixes #6320
```
matteius@matteius-Ryzen9:~/pipenv-triage/star-specifier$ pipenv install requests==2.*
Creating a virtualenv for this project
Pipfile: /home/matteius/pipenv-triage/star-specifier/Pipfile
Using /home/matteius/.pyenv/versions/3.13.2/bin/python3.13.2 to create virtualenv...
⠋ Creating virtual environment...created virtual environment CPython3.13.2.final.0-64 in 54ms
creator CPython3Posix(dest=/home/matteius/Envs/star-specifier-z4Ot9-96, clear=False, no_vcs_ignore=False, global=False)
seeder FromAppData(download=False, pip=bundle, via=copy, …
```
> Fix for the install/upgrade star specifier

- news/6385.bugfix.rst
- pipenv/project.py
- pipenv/routines/install.py
- pipenv/utils/requirements.py
- pipenv/utils/resolver.py
- tests/integration/test_import_requirements.py
> HOTFIX import requirements

- news/6386.bugfix.rst
- pipenv/routines/update.py
- tests/integration/test_upgrade_cleanup.py
> Cleanup unused dependencies

- news/6389.bugfix.rst
- pipenv/utils/virtualenv.py
- tests/integration/test_python_version_mismatch.py
When using pyenv, and python version in Pipfile not available ...
Fixes #6387 
> Fix for UnboundLocalError in ensure_python SESSION_IS_INTERACTIVE=False

- CHANGELOG.md
- docs/cli.md
- docs/commands.md
- pipenv/cli/command.py
In commit 56d45354e12fd9a3b8cd13dc64ac8566225a29a8 the new `--scan` option for the `check` command was introduced, and a deprecation warning was added. The deprecation warning is misleading since it has the wrong date and references a `scan` command which does not exist. This will remove the `scan` command from the documentation and update the deprecation warning.
Reference-to: https://github.com/pypa/pipenv/issues/6396
> Correct check/scan command documentation

- run-tests.sh
Also, ensure the pypi-server process is killed when run-tests.sh exits.
`run-tests.sh` was not starting the pypi server causing a load of tests to fail.
This fixes the issue by adding the missing argument to start the server.
> Fix pypi-server startup (it now requires `--welcome`).

- news/6426.bugfix.rst
- pipenv/patched/pip/_internal/index/package_finder.py
- tasks/vendoring/patches/patched/pip_finder_ignore_compatability.patch
This patch was mistakenly dropped during the last pip vendoring update, which caused #6423 
This PR restores and formalizes the `ignore_compatibility` patch for pip's package finder, enabling Pipenv to include all relevant package hashes in lock files regardless of platform compatibility constraints.
Currently, pip's package finder filters out packages based on platform compatibility (wheel tags, Python version requirements, etc.), which prevents Pipenv from generating comprehensive lock files that include hashes for all platforms. This creates issues when:
- Lock files are generated on one platform but used on another
- Cross-platform deployments require packages for different architectures
- Complete hash verification is needed for security across all supported platforms
This patch adds …
> Add back ignore_compatibility option to pip package finder for comprehensive lock file generation
