pipenv/cli.py

Fix typo in lock file initialization

---

README.rst

Good job and thank you for great tool pipenv!

Fix command in README

---

pipenv/cli.py

Fixes https://github.com/kennethreitz/pipenv/issues/98

Prevent invalid shebangs with Homebrew Python

---

pipenv/cli.py

Fix pipenv for Python 3 versions.

Fix proper casing mechanism

---

LICENSE

Just wrapped the lines in the license file and added the note on the first line that it's the MIT license.

Wrap lines in license text

---

.gitignore
pipenv/cli.py
pipenv/project.py
pipenv/utils.py

* Fix Copy&Paste error in `mkdir_p` function
* Move `mkdir_p` function to utils
* Fix some PEP8 issues

Various fixes and cleanups

---

pipenv/cli.py

Fix bug introduced in 9e9ba529667fcb97e37e401527b0e9513dfa289a.
Failing build: https://travis-ci.org/kennethreitz/pipenv/builds/196416314

Fix no color mode env variable detection

---

pipenv/utils.py

Ran into needing SVN immediately upon trying this out, so I figured I'd finish that TODO for you. :)

Support all version control systems that pip does

---

pipenv/cli.py
pipenv/environments.py
pipenv/pep508checker.py
pipenv/project.py
pipenv/utils.py

Since `open` by default in read mode I removed `'r'` arguments, also made some minor cleanups.
Thanks.

Cleanup: IO and formatting

---

pipenv/cli.py
pipenv/project.py
tests/test_project.py

This PR closes #228. See https://github.com/kennethreitz/pipenv/issues/228 for the former discussion.
Use the command below to try patched version of pipenv.
```bash
pip install --upgrade git+https://github.com/simnalamburt/pipenv.git@issue-228
```
Please review and comment. Thanks!

Hash the project path and use it as a virtualenv's name

---

docs/advanced.rst

Fix typo in section header

---

docs/advanced.rst
pipenv/cli.py

Adds a flag for ignoring the Pipfile in favor of the Pipfile.lock

---

pipenv/cli.py

Fix 'update' command docstring.

---

Makefile
_appveyor/install.ps1
appveyor.yml

This should put what we need in place for appveyor to run pipenv's test suite.

setup appveyor for pipenv

---

HISTORY.txt
pipenv/cli.py
pipenv/project.py
pipenv/utils.py

pipfile importing (work in progress)

---

pipenv/cli.py

This PR is to address the issue pointed out in #342.
The install process is dependent upon the virtualenv existing which isn't always the case for fresh projects. This is the most common case this code will execute in, so we need to be able to create the Pipfile before the virtualenv is created. This will read the contents of the requirements.txt file and write them directly into a new Pipfile.
This approach required a little reworking of your initial implementation @kennethreitz, so I'd like you to sign off on this.
I removed the install portion completely because not only was it broken, but I don't know if it makes sense to install with *any* command passed to pipenv. Things like `pipenv shell` and `pipenv check` currently install the requirements.txt into the new environment which …

create Pipfile from requirements.txt without installing

---

docs/advanced.rst

Correction in the documentation

small sentence correction

---

README.rst

This reverts commit 7dce6d6d1f1293442c689ef198d868be24dfd010.
This commit seems to be a test. 🤔

Revert test commit ( Update README.rst )

---

tests/test_pipenv.py

Add small `pipenv run` test ( added in order to ensure no regression by #398 ) !

Add test for pipenv run

---

Pipfile
pipenv/vendor/delegator.py
requirements.txt

In the process of splitting up commits now that work is over.  This one updates the delegator.py to the latest version, v0.0.12, which will allow for custom timeouts to be implemented. I also realize I spelled delegator incorrectly in the branch name :(

Vendor delagator.py update

---

docs/advanced.rst

I updated the Advanced.rst Environment variables section to cover the new one

documented the new PIPENV_TIMEOUT variable

---

docs/advanced.rst

Document virtualenv name cleansing and slug

---

pipenv/cli.py
tests/test_pipenv.py

into it's proper Pipfile format

Added logic to parse VCS links from a requirements file

---

setup.py

`find_packages` more convenient way to set packages)

Simplify packages find

---

pipenv/utils.py

File path addition

---

pipenv/cli.py

See https://github.com/kennethreitz/pipenv/pull/506#issuecomment-328366839

Use os.path.isabs to detect absolute path commands

---

pipenv/utils.py
tests/test_utils.py

Add support for extras_require in Pipfile for vcs urls

---

README.rst

same typo as https://github.com/kennethreitz/pipenv/pull/526

fix README typo 'upate' -> 'update'

---

pipenv/cli.py
pipenv/utils.py
test_windows/test_pipenv.py
test_windows/test_utils.py
tests/test_utils.py

Signed-off-by: Kenneth Reitz <me@kennethreitz.org>

stole @jacebrowning's tests (modified)

---

pipenv/utils.py

We can do this ez-mode instead of being super complicated about it, maybe

Quick fix for dealing with relative paths!

---

pipenv/cli.py
pipenv/project.py

refactor: removed some elses and unused packages

---

pipenv/cli.py

See https://english.stackexchange.com/questions/22603/why-doesnt-its-have-an-apostrophe

remove stray apostrophe 🤓

---

pipenv/cli.py
tests/test_pipenv.py

Fix bug with misprint of "project" variable in update method of CLI

---

pipenv/cli.py

run ensure_project in cli do_shell method

---

pipenv/cli.py

Signed-off-by: Kenneth Reitz <me@kennethreitz.org>

see if this fixes things for windows

---

.gitignore
pipenv/cli.py
tests/test_pipenv.py

Bug #663 fix

---

pipenv/cli.py

add: --index in import_requirements

---

MANIFEST.in

This should fix https://github.com/kennethreitz/pipenv/issues/677

Fixed stdlib file not found error

---

docs/advanced.rst

Related to https://github.com/kennethreitz/pipenv/commit/621d89819a3501e5675afc9c6199d73c7f9e81ef

Add PIPENV_DOTENV_LOCATION to Docs

---

pipenv/utils.py

change 'factory-boy' to 'factory_boy' in packages

---

HISTORY.txt
pipenv/vendor/pexpect/popen_spawn.py
pipenv/vendor/pexpect/replwrap.py
pipenv/vendor/pexpect/utils.py

This will update pexcept and resolve the issue in #744.

update vendored pexcept to fix shellquote issues on Windows

---

pipenv/vendor/first.py

Adds the `first.py` requirement for our patched pip-tools.

vendor first to fix our patched pip-tools

---

pipenv/project.py

Fixed typo in virtualenv_name property docs

---

pipenv/environments.py

max-depth for pipfile searching

Fixed typo in environments.py docs

---

pipenv/environments.py

@kennethreitz I'm *fairly* certain I fixed this in https://github.com/pypa/pipfile/pull/83

remove PIPENV_MAX_DEPTH workaround

---

pipenv/cli.py
pipenv/project.py
pipenv/utils.py

See #806 - issue is easily reproducible

Non editable vcs fix

---

pipenv/cli.py
tests/test_pipenv.py

In reference to issue #791.
Added the --sequential flag to cli.update. I just aimed to emulate how it's implemented for cli.install.

Add update sequential

---

pipenv/cli.py
pipenv/project.py
tests/test_legacy.py
tests/test_pipenv.py
tests/test_project.py

Pep8 nicities

---

pipenv/project.py
pipenv/utils.py

* Fixes #817
* Packages werent being identified as local files
* Therefore they were not being given a path
* We were trying to resolve them with pypi

Fix install for local sdist packages

---

tests/test_pipenv.py

As promised in https://github.com/kennethreitz/pipenv/pull/821

Add check unused test for mapped package name

---

pipenv/patched/piptools/repositories/base.py
pipenv/patched/piptools/repositories/local.py
pipenv/patched/piptools/repositories/pypi.py
pipenv/patched/piptools/resolver.py

Aligned with pip-tools commit ef0aa2d62bd5499b328e5f3c9b26130d07be16dd
plus pipenv patching.
Fixes #832

Updating the patched pip-tools with the wheel dependency bugifx.

---

tests/test_utils.py

Add vcs tests to account for changes in #807

---

docs/install.rst

fixes spelling of "enviornment"

Spelling typo fix

---

pipenv/cli.py

Dep_d_endencies -> dependencies

Small typo fix

---

.github/ISSUE_TEMPLATE.md

That should give a helping hand to everyone.
I included some common information I feel would help, based on the bit of helping I've been doing.
Fell free to request (or make) any changes.

Add a Github issue template.

---

pipenv/utils.py
tests/test_utils.py

Add fix for windows paths

---

HISTORY.txt
pipenv/cli.py
pipenv/utils.py

This should fix #886, however i am not sure if this is the right way to do this! haha
if something needs to be changed or fixed please let me know! this is my first time contributing here so i am expecting that i did something wrong.
Thanks for this amazing project btw

fix for #886

---

CONTRIBUTING.rst

Refs #933 
Work in progress. I would like to get some input from people who are more familiar with the project.
This is just what I deduced from `.travis.yml` so far.
Curiously, if I follow these steps to run the tests on my local system, I get some test failures that I do not see on travis: https://gist.github.com/rfleschenberg/9b3eb58154cd8456a320b6b5cb694ce8

WIP: development docs

---

tests/test_utils.py

tests now are in separate PR 😄

added test for remote req file utils

---

pipenv/utils.py
tests/test_utils.py

new line is now being added to the end of the toml file

fix for #925

---

pipenv/cli.py
tests/test_pipenv.py

Outputs the reversed dependencies graph.
Ex:
```
requests==2.18.4
- lib_with_good_taste==1.0.0 [requires requests>=2.18]
- package_using_lib_with_good_taste==1.2.3 [requires lib_with_good_taste]
- another_package [requires requests<3.0,>=2.0]
```
Inspired by #881. Even if it's not exactly the same feature, this is a quick-win that covers essentially the same need: have a compact view of "who" required a given package. Plus, you get the full chain with this.

Add pipenv graph --reverse

---

pipenv/cli.py

Force vcs installs to block to avoid race condition

---

pipenv/vendor/pexpect/_async.py
pipenv/vendor/pexpect/expect.py
pipenv/vendor/pexpect/fdpexpect.py
pipenv/vendor/pexpect/pty_spawn.py
pipenv/vendor/pexpect/pxssh.py
pipenv/vendor/pexpect/screen.py
pipenv/vendor/pexpect/spawnbase.py

update the vendored pexpect for python 3.7 async support

---

docs/basics.rst

Hope this helps. This is what I needed to know...

Fixes #954. Example Pipfile.lock workflow.

---

pipenv/cli.py

Fix for respecting allow prerelease flag in pipfile

---

tests/test_pipenv.py

i am opening this pull request even though i didn't have a chance to run the test today (windows tests are broken i think #882) will take a look using my mac tomorrow
in the mean time please let me know if i used the correct decorators for the test function and if i am missing something from the test case
thank you for the amazing work
this is  a test for: `pipenv install -r http://something.com/req.txt`

test for installing from remote file

---

docs/basics.rst
pipenv/cli.py
tests/test_pipenv.py

Changed name of the --dev flag to --all-dev to be more specific about what it does.  --dev now does nothing

updated --dev flag to --all-dev

---

pipenv/cli.py

Ignore prerelease python installs from pyenv

---

README.rst

Related to https://github.com/kennethreitz/pipenv/issues/996.

Add instructions to install via homebrew in README

---

setup.py

Added a minimum version of flake8

---

.github/ISSUE_TEMPLATE.md

"describe you environment" -> "describe you**r** environment"

Fix typo in GitHub issue template

---

docs/index.rst
docs/install.rst

#999 added instructions for installing via homebrew to the README. This PR adds an expanded version of the same instructions to the docs

Add homebrew to the install instructions

---

pipenv/cli.py
pipenv/environments.py
pipenv/utils.py
pipenv/vendor/appdirs.py

- Store stamp file in app cache dir (os specific)
- Vendor appdirs (is this a good idea?)
- Fixes #1023 and some other issues I dont know about
- This works but is just a suggestion to get my thoughts on paper

Only check for updates once per 24 hours

---

pipenv/utils.py
tests/test_pipenv.py
tests/test_utils.py

Stop matching packages beginning with vcs names

---

pipenv/utils.py

- Follow pip methodology for boolean testing
- Be less confusing about what we're doing and why

Fix git url scheme parsing consistent with pip

---

pipenv/project.py

- Check if virtualenv_location exists as an os path as part of the virtualenv_exists check
- Fixes #969

Check if virtualenv location really exists

---

pipenv/utils.py

This reverts commit 73ba65fabbf5a6d094d95f3dea6e21aad9416c25.

Revert "In HackedPythonVersion, patch sys.version_info"

---

pipenv/utils.py

Fix "connection reset by peer" when grabbing hashes during lock

---

pipenv/cli.py

Fixes https://github.com/kennethreitz/pipenv/issues/997

Prompt for confirmation before replacing existing virtualenv

---

HISTORY.txt

does what it says on the tin :)

fix "isntalled" typo in HISTORY.txt

---

pipenv/cli.py

This addresses #1153, adding a quick message alerting the user they supplied a non-existent requirements.txt instead of dumping a stacktrace.

warn user if requirements.txt is missing

---

pipenv/utils.py

see https://github.com/pypa/pipenv/pull/1183/files#r155932921
also fixed comment typo

missing support for ~= in check? - see comment in #1183

---

pipenv/cli.py

Skip search for requirements.txt when provided

---

pipenv/cli.py
pipenv/utils.py
tests/test_legacy.py
tests/test_pipenv.py

Reverts pypa/pipenv#1233
- This breaks everything on windows

Revert "Clean up temporary files created during installation"

---

pipenv/cli.py
pipenv/utils.py
tests/test_pipenv.py

Reintegrate #1097 which is the last remaining commit missing from before the 9.0.1 release
- Fixes #1002 (again)

#1097 remerge

---

docs/advanced.rst

mention `PIPENV_PIPFILE` in advanced docs

---

docs/advanced.rst

Figured it'd be a good idea to have a standard answer for "How do I use this with conda?"
Left out any commentary about conflicts between conda and Pipenv about requirements... hoping that's obvious to folks who'd use both.

Add instructions for conda plus pipenv

---

tests/test_pipenv.py

based on https://github.com/pypa/pipenv/commit/e711fe313798434e4db8a19ac7052d8a99153dea

remove jumbotron unit test

---

pipenv/project.py
tests/test_project.py

This is just an idea but it would be useful if we automatically parsed pip config files and added the extra indexes as sources in the generated Pipfile.
Feedback is welcomed and greatly appreciated :)

add extra indexes from pip config files in Pipfile gen

---

docs/index.rst

En dashes are great, but these should be hyphens. :)
References:
* http://www.chicagomanualofstyle.org/qanda/data/faq/topics/HyphensEnDashesEmDashes/faq0002.html
* https://typographyforlawyers.com/hyphens-and-dashes.html

Use hyphens, not en dashes

---

pipenv/core.py

This would mimic the behavior of `pip freeze`

Output requirements in sorted order

---

HISTORY.txt
pipenv/core.py

- Fixes #1530 and builds on existing infrastructure
This seems like it will pass everything now, and no longer leaves / accumulates temporary artifacts

Clean up requirements files used during installs

---

docs/index.rst

Based on https://github.com/pypa/pipenv/issues/1332

Add editor integrations to documentation.

---

pipenv/core.py

- Since this is what shellquote is for I figured it's a good idea

Shellquote sys.executable when passing to shell

---

HISTORY.txt
pipenv/utils.py

Resolve multiple extras when provided

---

pipenv/core.py
pipenv/patched/pew/__init__.py
pipenv/patched/pew/__main__.py
pipenv/patched/pew/_print_utils.py
pipenv/patched/pew/_utils.py
pipenv/patched/pew/_win_utils.py
pipenv/patched/pew/pew.py
pipenv/patched/pew/shell_config/_pew
pipenv/patched/pew/shell_config/complete.bash
pipenv/patched/pew/shell_config/complete.fish
pipenv/patched/pew/shell_config/complete.zsh
pipenv/patched/pew/shell_config/complete_deploy
pipenv/patched/pew/shell_config/init.bash
pipenv/patched/pew/shell_config/init.fish
pipenv/patched/pew/shell_config/init.zsh
pipenv/patched/pew/template_django
pipenv/pew/__main__.py
pipenv/project.py
setup.py
tests/test_pipenv.py

- Breaks dependency on psutil
- Continued work on #1587 and #1600

Vendor pew under script name `pewtwo`

---

setup.py

- Possibly causing issues installing?

Add setuptools and drop psutil

---

pipenv/patched/piptools/resolver.py

Fix new resolver code to uniqueify markers

---

pipenv/core.py
pipenv/utils.py
setup.py
tests/test_utils.py

Shellquote all shell execs for path escaping

---

docs/advanced.rst

Tiny doc note to pair with explanation from #1469 cc @boeddeker.

Site packages with conda

---

docs/advanced.rst

Add a legal caveat on `pipenv check`

---

pipenv/pew/__main__.py

Add vendor and patch directories to pew path

---

pipenv/utils.py

- Dont import all of pip for smaller tasks

Update pip imports to always come from patched dir

---

pipenv/core.py
pipenv/environments.py
pipenv/project.py
run-tests.sh

Signed-off-by: Kenneth Reitz <me@kennethreitz.org>

parallelism

---

pipenv/__init__.py
pipenv/pew/__main__.py

- Small change for consistency

Better import paths

---

pipenv/patched/pew/pew.py

Fix #1692. Microsoft really has very different ideas about software than Unix people.

Suppress subshell errors for CMD and Powershell

---

pipenv/patched/pew/_win_utils.py

Fix ppid handling in patched pew._win_utils

---

pipenv/patched/pew/_win_utils.py

Fix syntax errors in pew windows c api calls

---

pipenv/cli.py

Show help for main pipenv command in same format for all three help invocations:
```
pipenv
pipenv --help
pipenv -h
```
Code extracted from recent update to `legit`.

Show formatted help with --help and -h options

---

pipenv/core.py
pipenv/utils.py

Fix clear for lock command. Clear flag was missed on resolver execution.

Pass clear flag to resolver

---

pipenv/patched/piptools/resolver.py

- Fix for when requirements are also present
- Fixes #1791

Fix resolving against multiple markers

---

Dockerfile

@kennethreitz - addresses comment in #1728 about git installs failing

Add git to Dockerfile for git installs

---

MANIFEST.in

Add requests's pem file to distribution

---

docs/advanced.rst
docs/basics.rst
run-tests.sh
tests/pytest-pypi/README.md

Misc. typos

---

pipenv/cli.py
pipenv/core.py
tests/test_pipenv.py

Fixes #1835 
I didn't find a prerelease package in mocked pypi so I uploaded one.

Pass allow_prereleases setting to lock

---

HISTORY.txt
pipenv/core.py
pipenv/resolver.py
pipenv/utils.py

Fix allow_global=system with new resolver

---

docs/basics.rst

- Add link to pip docs
- Unquote `-e .` example
- Add detail to examples
- Closes #1908

Update vcs documentation

---

pipenv/project.py
tests/test_pipenv.py

Normalize casing on windows virtualenv names
- Fixes #1925

Windows VEnv Case normalization

---

pipenv/vendor/requests/packages/chardet/LICENSE
pipenv/vendor/requests/packages/urllib3/LICENSE.txt
pipenv/vendor/requirements/LICENSE.rst

https://github.com/pypa/pipenv/issues/1961

More vendor licenses

---

pipenv/project.py
tests/integration/test_project.py

Add pipfile env var expansion and test

---

pipenv/core.py
pipenv/project.py

Fix #1993. I made it more general than the issue, so the .venv directory
is honoured in all situations.

Make sure to consider existing .venv directory

---

HISTORY.txt
pipenv/core.py

- Allows for windows paths with spaces in them
- Fixes #2054

Shellquote paths to requirements files

---

setup.py

Only depend on requests[security] and ordereddict for Python 2.6

---

pipenv/core.py
pipenv/project.py
pipenv/utils.py

Close #2031 (includes it), fix #1888.
Referenced atomic-write logic: https://github.com/lektor/lektor/blob/05a541120e6f6add0d5d9d30d0585166f838594c/lektor/utils.py#L451

Atomic lockfile overwrite

---

.gitignore
pipenv/core.py
pipenv/project.py
pipenv/utils.py
tests/integration/test_install_basic.py

Do not expand environ in cache on package install

---

pipenv/core.py
pipenv/utils.py
tests/integration/test_project.py

Allow the use of many sources instead of just 2

---

tasks/vendoring/__init__.py

Because I just can't remember the command.
Example usage:
```
$ pipenv run invoke vendoring.generate-patch patched/prettytoml table-iter
[vendoring.update] git diff HEAD -p pipenv/patched/prettytoml > pipenv/tasks/vendoring/patches/patched/prettytoml-table-iter.oatch
```

Add a task to generate patch file

---

pipenv/core.py

This should help the user know what's going on in situations like #2185.

Echo Pipfile location during init

---

pipenv/utils.py

I'm pretty sure `reps` is just a typo for `deps`.

Fix typo (actually_resolve_reps -> actually_resolve_deps)

---

docs/index.rst

punctuation: removed unnecessary comma

---

pipenv/core.py

Fix #2349. Commit introducing the error is 83e1ba9a2.

Ensure skip_requirements is set before use

---

pipenv/project.py

Use Path.touch to better ensure file existence

---

pipenv/utils.py
pipenv/vendor/requirementslib/utils.py
pipenv/vendor/vendor.txt
tests/integration/test_install_basic.py
tests/integration/test_install_twists.py
tests/unit/test_utils.py

Follow-up to #2401.
@techalchemy There’s an update to requirementslib. Maybe need to cut another release there?

Cleanup 16.0

---

news/2450.bugfix
pipenv/project.py

Ensure we use unicode for proper names db

---

Pipfile
Pipfile.lock
news/2453.bugfix
news/2453.vendor
pipenv/patched/piptools/utils.py
pipenv/vendor/requirementslib/__init__.py
pipenv/vendor/requirementslib/models/requirements.py
pipenv/vendor/requirementslib/models/utils.py
pipenv/vendor/shellingham/__init__.py
pipenv/vendor/shellingham/posix/__init__.py
pipenv/vendor/shellingham/posix/_default.py
pipenv/vendor/shellingham/posix/linux.py
pipenv/vendor/vendor.txt
setup.py
tasks/vendoring/__init__.py

- Updated requirementslib
- Fix local relative path bug whici caused paths to be output as
absolute (test added to requirementslib)
- Fix SSH normalization bug (test added to requirementslib)
- Fixes #2440, #2441

Update vendored dependencies

---

news/2484.bugfix
news/2484.vendor
pipenv/vendor/requirementslib/__init__.py
pipenv/vendor/requirementslib/_compat.py
pipenv/vendor/requirementslib/models/requirements.py
pipenv/vendor/requirementslib/models/utils.py
pipenv/vendor/requirementslib/utils.py
pipenv/vendor/vendor.txt

Fix parsing of usernames in private pypi URIs

---

docs/basics.rst

Some notes were preceded by a header while others were not. Added headers to all notes.

Revise note format for consistency in basics.rst

---

tasks/vendoring/patches/patched/crayons.patch

Update crayons and add patch

---

README.md
docs/conf.py
docs/dev/philosophy.rst
docs/diagnose.rst
docs/index.rst
docs/install.rst

Removed ppa mentions from documentation, and re-organised the page a bit to make it structurally easier to upderstand.
Both the documentation's front page and README.rst now actively refer to the page so user can be directed to better installation methods.
Also fixed many Sphinx warnings during documentation builds.

Documentation updates

---

pipenv/core.py

Full explanation: https://github.com/pypa/pipenv/issues/2575#issuecomment-405202712
I also sorted the package list alphabetically.

Add pkg-resources to the ignored packages list

---

README.md
pipenv/core.py

See https://github.com/pypa/pipenv/issues/2405

Add --rm option example to Usage Examples

---

pipenv/core.py

Pass PIPENV_DOTENV_LOCATION directly to load_dotenv if present

---

pipenv/core.py

fix grammar in error message

---

news/2527.feature
pipenv/core.py
pipenv/environments.py
tests/unit/test_core.py

PIPENV_VERBOSITY

---

news/2680.bugfix
pipenv/project.py
tests/integration/test_dot_venv.py

Fix virtualenv creation failure when a .venv file exists

---

docs/_templates/hacks.html
pipenv/cli.py

Just fixing a pet peeve of mine.

GitHub has a capital H

---

docs/basics.rst

Fix typo in basics.rst

---

docs/basics.rst
docs/index.rst

Issue #84 
r? @uranusjr 
In the thread, you mentioned that an edit to the documentation regarding this issue would be welcome. Can you review this?

Added shell deactivation instructions to documentation

---

news/2950.bugfix
news/2955.bugfix
news/2961.bugfix
pipenv/vendor/vistir/backports/tempfile.py
pipenv/vendor/vistir/compat.py
tasks/vendoring/patches/vendor/vistir-imports.patch

- Add tempfile patch and news
- Fixes #2950
- Fixes #2955
- Fixes #2961
- Closes #2967

Fix imports

---

news/2957.bugfix
pipenv/core.py

introduced in 999761130e910bb211c75467d66be7db7547e7fe.
issue #2957

fix virtualenv assertion bug

---

pipenv/core.py

- Additional logic required for #2953

Fix virtualenv installation

---

news/2952.bugfix
pipenv/core.py
pipenv/vendor/pipdeptree.py
tasks/vendoring/patches/vendor/pipdeptree-updated-pip18.patch

Fix graph import

---

news/2993.bugfix
news/2993.feature
pipenv/cli/command.py
pipenv/core.py

Add news entries and trusted host fix
- Additional fix for #2981

Cherrypick trusted host fix

---

news/3020.feature
pipenv/patched/crayons.py
tasks/vendoring/patches/patched/crayons.patch

- Swap native blue for magenta
- Fixes #3020

Enabled colors on native powershell

---

docs/index.rst
docs/install.rst

It is not immediately clear how pipenv knows the virtualenv for a project  (See #796)
Docs extension

Add brief description and caveats of project - virtualenv mapping

---

docs/install.rst

Fix typo in docs/install.rst

---

news/2983.bugfix.rst
pipenv/vendor/pythonfinder/__init__.py
pipenv/vendor/pythonfinder/cli.py
pipenv/vendor/pythonfinder/models/windows.py

Fixed a bug with encountering removed pythons

---

news/3154.trivial.rst
pipenv/project.py

Fix virtualenv path discovery

---

pipenv/core.py

Fix typo on spinner result text

---

pipenv/core.py

Fix typo in creating virtualenv

---

news/3230.bugfix.rst
pipenv/vendor/requirementslib/models/setup_info.py

Fix parsing of named `setup.py` extras
- Fixes #3230

Fix parsing of named `setup.py` extras

---

pipenv/environments.py

Fix the condition to reflect the real case.
The file is blackened.

Fix the is_in_virtualenv condition

---

news/3255.bugfix.rst
pipenv/core.py
pipenv/project.py
pipenv/utils.py
pipenv/vendor/plette/__init__.py
pipenv/vendor/plette/models/base.py
pipenv/vendor/requirementslib/__init__.py
pipenv/vendor/requirementslib/environment.py
pipenv/vendor/requirementslib/models/pipfile.py
pipenv/vendor/requirementslib/models/requirements.py
pipenv/vendor/requirementslib/models/setup_info.py
pipenv/vendor/vendor.txt

Ignore hashes when using `--skip-lock`
- Closes #3255 
- Fixes #3266

Ignore hashes when using `--skip-lock`

---

.gitmodules
pipenv/vendor/requirementslib/models/requirements.py
pipenv/vendor/requirementslib/models/setup_info.py
tests/integration/conftest.py
tests/integration/test_install_twists.py
tests/integration/test_install_uri.py
tests/pytest-pypi/pytest_pypi/app.py
tests/pytest-pypi/pytest_pypi/templates/artifact.html
tests/pytest-pypi/pytest_pypi/templates/artifacts.html

Add some test speedups, potentially decrease flakiness
- Decrease network calls
- include artifacts
- Fix requirementslib bug
- Silently handle empty or NoneType extras
- Fixes #3283

Speed up tests, silently handle empty and NoneType Extras

---

pipenv/core.py

As the title, fix a typo in comments

Fix typo in comments

---

news/3446.trivial.rst
pipenv/core.py

Fix order of hashes

---

.azure-pipelines/linux.yml
.azure-pipelines/windows.yml

Exclude peeps folder when trigger pipelines

---

news/3584.bugfix.rst
pipenv/project.py

Bugfix 3584

---

README.md

I just fixed a link to the documentation in the README file.

Fix documentation install page link

---

docs/advanced.rst

I noticed that my last change had some formatting issues so I fixed them.

Fixes formatting

---

news/3842.bugfix.rst
pipenv/project.py

Make sure symlinks are resolved.

---

docs/_templates/sidebarintro.html

- Make URLs HTTPS
- Modernize some links
- Remove a non-functioning iframe
- Make an image title more descriptive

Touch up sidebar

---

news/3912.doc.rst
pipenv/cli/command.py

Fixes https://github.com/pypa/pipenv/issues/3491.
Just added a tiny line exposing the potential issues.

Doc: pipenv shell --fancy

---

README.md

Not sure what went wrong in https://github.com/pypa/pipenv/pull/3536.

Removing myself again.

---

pipenv/utils.py

Fix setting os.environ of Python 3.7+

---

docs/_templates/hacks.html

Signed-off-by: Sumana Harihareswara <sh@changeset.nyc>
Followup to #4145.

Update GitHub logo link in docs

---

.github/workflows/ci.yaml
azure-pipelines.yml

Fix Azure Pipelines Windows issue + better names for CI checks

---

.github/workflows/pypi_upload.yml
Pipfile.lock
RELEASING.md
pipenv/core.py
tasks/release.py

- Automatically release when tags are pushed to master
- Release automation will build wheel and sdist + upload to pypi
- Added test pypi as initial target
- Updated version update scripts to help with automatic version
management

Automate release workflow

---

pipenv/project.py
tests/integration/test_install_basic.py

fix toml table construction

---

news/4232.bugfix.rst
pipenv/utils.py

Don't fallback to python unconstrained version

---

tests/unit/test_utils.py

- Fixes issue #4233 .
- I don't think this merits a news fragment in the `news/` directory

Mark unit tests requiring network connection

---

.github/workflows/pypi_upload.yml

Close #4328 
Switch to the current commit author to the official GitHub Actions bot on the PyPI upload workflow.

Switch commit author to GitHub Actions bot

---

news/4424.bugfix.rst
pipenv/utils.py
pipenv/vendor/delegator.py

Rewrite the imports of pexept to vendor.pexpect

---

news/4330.bugfix.rst
news/4436.bugfix.rst
pipenv/vendor/pythonfinder/__init__.py
pipenv/vendor/pythonfinder/models/path.py
pipenv/vendor/pythonfinder/models/windows.py
pipenv/vendor/vendor.txt

Fix path handling on Windows

---

news/4433.bugfix.rst
news/4433.vendor.rst
pipenv/vendor/tomlkit/__init__.py
pipenv/vendor/tomlkit/_compat.py
pipenv/vendor/tomlkit/_utils.py
pipenv/vendor/tomlkit/api.py
pipenv/vendor/tomlkit/container.py
pipenv/vendor/tomlkit/exceptions.py
pipenv/vendor/tomlkit/items.py
pipenv/vendor/tomlkit/parser.py
pipenv/vendor/tomlkit/source.py
pipenv/vendor/tomlkit/toml_char.py
pipenv/vendor/tomlkit/toml_file.py
pipenv/vendor/vendor.txt
tasks/vendoring/__init__.py
tasks/vendoring/patches/vendor/tomlkit-fix.patch
tests/integration/test_uninstall.py

Update dependency tomlkit

---

pipenv/cli/command.py
pipenv/core.py

Fixes #2227 
Just add the option, all needed function args already exist

Add --system option to sync command

---

.azure-pipelines/steps/install-dependencies.yml
.github/workflows/ci.yaml
Pipfile.lock
news/4379.bugfix.rst
pipenv/project.py
setup.py
tests/integration/test_install_basic.py

setuptools==50.0.0 is breaking the CI.

Fix CI failure

---

news/3630.trivial.rst
tests/integration/test_cli.py
tests/integration/test_install_markers.py
tests/integration/test_lock.py
tests/integration/test_project.py
tests/integration/test_windows.py

Fix #3630 Adapt test cases to prefer the mocked PyPI.

---

CONTRIBUTING.md

Fixes https://github.com/pypa/pipenv/issues/4468
https://github.com/pypa/pipenv/issues/4468
Link to details of how to run tests.

Clarify testing

---

docs/_templates/sidebarintro.html
docs/_templates/sidebarlogo.html

Several URLs in the sidebar lead to broken links or outdated project URLs. Other links are http:// and insecure. And as per the changes in #3868, the top project image has an title that's not very descriptive. 
* Make all URLs HTTPS where possible
* Update project URLs to current locations
* Make project image title consistent between sidebars

Update sidebar templates

---

news/4517.bugfix.rst
pipenv/patched/piptools/repositories/pypi.py
tasks/vendoring/patches/patched/piptools.patch

Fix regression issues:
Close #4517 
Close #4516

Restrict the acceptable hash type to SHA256 only

---

docs/basics.rst
news/4568.trivial.rst

I didn't create a GitHub issue, because the proposed change is trivial.

Fix description of the compatible-release operator

---

news/4591.vendor.rst
pipenv/vendor/packaging/__about__.py
pipenv/vendor/packaging/requirements.py
pipenv/vendor/packaging/specifiers.py
pipenv/vendor/packaging/tags.py
pipenv/vendor/packaging/utils.py
pipenv/vendor/packaging/version.py
pipenv/vendor/vendor.txt

Update packaging to 20.8

---

docs/index.rst

A broken link on the index page.
Replaced with the correct location in Kenneth's webiste.

re-fix broken link

---

.deepsource.toml
pipenv/_compat.py
pipenv/environments.py
pipenv/project.py
tasks/vendoring/__init__.py

Hey 👋 , I'm member of the Developer Outreach team at DeepSource and ran DeepSource analysis on my fork of the repo. It found some interesting [code quality improvements](https://deepsource.io/gh/ankitdobhal/pipenv/issues) to consider.
This PR fixes a few of the issues detected for you to assess if it is right for you.
Happy to provide the tweaks separately otherwise :)
This PR improve some code quality issues like anti-pattern and bug risks. 
- Remove `unused` imports
- Remove `duplicate` dictionary key(s)
- Refactor the comparison involving `not`
- Remove `length check` in favour of truthiness of the object
- Added `.deepsource.toml` file for continuous analysis on bug risks/performance/code-quality issues on new changes.

chore : refactor code quality issues

---

pipenv/environment.py

Fixed typo in comment.
```
enviornment -> environment
```

Fix typo in environment.py

---

tests/integration/test_cli.py

Fixed typo in comment.
```
begining -> beginning
```

Fix typo in test_cli.py

---

.github/workflows/ci.yaml
tasks/vendoring/__init__.py

Add CI jobs for packaging and vendoring

---

news/4831.bugfix.rst
pipenv/core.py
tests/integration/conftest.py
tests/integration/test_install_twists.py
tests/integration/test_install_uri.py
tests/integration/test_run.py

Set env vars in pipenv run

---

news/4837.vendor.rst
pipenv/vendor/pythonfinder/LICENSE.txt
pipenv/vendor/pythonfinder/__init__.py
pipenv/vendor/pythonfinder/models/python.py
pipenv/vendor/pythonfinder/models/windows.py
pipenv/vendor/pythonfinder/utils.py
pipenv/vendor/vendor.txt

update vendor pythonfinder

---

pipenv/__init__.py
pipenv/_compat.py
pipenv/core.py
pipenv/environment.py
pipenv/project.py
pipenv/shells.py
pipenv/utils.py
tasks/vendoring/__init__.py
tests/integration/conftest.py
tests/integration/test_dot_venv.py
tests/integration/test_install_basic.py
tests/integration/test_install_twists.py
tests/integration/test_install_uri.py
tests/integration/test_lock.py
tests/integration/test_windows.py
tests/unit/test_core.py

CI on Windows Python 3.6-3.9 timeout for unknown reason, create this to try to figure it out.

Windows CI debugging

---

news/4873.bugfix.rst
pipenv/core.py
pipenv/project.py
tests/integration/test_install_uri.py

[bug] Fix a bug of source saving in Pipfile

---

docs/index.rst

Add a link in docs. Text is not changed.

Add a clickable link to PEP 508 in index.rst

---

docs/basics.rst
docs/install.rst

Document running as root and usage in containers

---

docs/basics.rst

Following the discussion on #4917.
This PR add documentation which demonstrates how to use multistage build, and an explicit not on usage as root.
@jfly,  @matteius, your feed back is appreciated!

Document  usage of Pipenv in multistage docker build

---

pipenv/core.py

Remove dead code after exception

---

docs/basics.rst

Typo fix that may be confusing

doc fix docker container title

---

pipenv/vendor/README.md

Update vendoring docs.

---

.env
news/5010.bugfix.md
news/5011.trivial.rst
pipenv/core.py
setup.py
tests/integration/test_cli.py
tests/integration/test_lock.py
tests/integration/test_run.py

These additional tests and accepted bug fix, plus also revert the crud I had done to main the night I realize the regression with the CI.

5011 more tests3 final

---

Makefile
setup.cfg

Really run the tests in parallel

---

.github/workflows/ci.yaml

Limit resource usage in CI

---

pipenv/cli/command.py

A quick follow up on #5069.
Cosmetic change, saves 2 lines of code and one import.

Replace echo(style(...)) with secho(...)

---

news/5179.bugfix.rst
pipenv/vendor/requirementslib/__init__.py
pipenv/vendor/requirementslib/models/utils.py
pipenv/vendor/vendor.txt

vendor in minor update from requirementslib
Fixes:  https://github.com/pypa/pipenv/issues/5179

Issue 5179 requirementslib==1.6.8

---

pipenv/core.py
pipenv/help.py

There have been times I wanted to know what the setuptools version or the version of pip outside of pipenv that the user has installed.  Also telling the OS would be helpful.

Add extra details to the pipenv support command

---

news/5206.bugfix.rst
pipenv/utils/resolver.py

Issue 5206

---

tasks/vendoring/patches/vendor/pipdeptree-update-pip-import.patch

Regen patch hash

---

.github/workflows/ci.yaml
.github/workflows/pypi_upload.yml
news/5244.trivial.rst

Upgrade GitHub Actions

---

docs/basics.rst

Remvoe reference to -r from documentation.

---

news/5336.vendor.rst
pipenv/vendor/shellingham/__init__.py
pipenv/vendor/shellingham/_core.py
pipenv/vendor/shellingham/posix/__init__.py
pipenv/vendor/shellingham/posix/proc.py
pipenv/vendor/vendor.txt

Bump vendored version of shellingham

---

news/5337.vendor.rst

Bump plette version to v0.3.0

---

docs/advanced.rst

Update documentation around requirements command and provide current examples.

---

tests/integration/conftest.py

Remove small leftovers and unused import.

Clean conftest

---

Pipfile.lock
pipenv/core.py
pipenv/project.py
pipenv/vendor/plette/pipfiles.py
pipenv/vendor/vendor.txt

Fix for the meta data not getting updated in the lock phase.

---

pipenv/vendor/plette/__init__.py
pipenv/vendor/plette/models/sections.py
pipenv/vendor/vendor.txt

Bump plette to v0.4.2

---

pipenv/utils/resolver.py

One of the important tell-tell tests was failing for windows/python 3.7 and I finally tracked down the exact change that caused it.
I realized that pip encountered a similar issue with the default TemporaryDirectory class from tempfile and already had there only TempDirectory class that works nicely for this use case.

Remove QuasiPipTempDirectory and use pip's TempDirectory.

---

setup.py

#5491 
Include the missing package data for Safety.

Include missing package data for Safety

---

setup.py

Fix ruamel inclusion in wheel.

---

tasks/vendoring/patches/vendor/ruamel-import.patch

Fix ruamel vendoring

---

docs/dev/contributing.rst

fixed broken link to non-existing philosophy subpage

---

README.md

The README.md file is what drives the presentation of the pypi page.   This brings the Readme inline with what is published in our docs:  https://pipenv.pypa.io/en/latest/

Clean up intro section of our pypi page.

---

README.md
docs/index.md

Remove ubuntu apt install from list and some other small doc review.

---

docs/credentials.md

Improve the keyring docs based on what I learned today.

Improve keyring docs.

---

.github/workflows/ruff.yml
.pre-commit-config.yaml
pipenv/cmdparse.py
pipenv/environment.py
pipenv/exceptions.py
pipenv/installers.py
pipenv/project.py
pipenv/routines/lock.py
pipenv/utils/indexes.py
pipenv/utils/internet.py
pipenv/utils/pip.py
pipenv/utils/pipfile.py
pipenv/utils/processes.py
pipenv/utils/requirements.py
pipenv/utils/resolver.py
pipenv/utils/shell.py
pipenv/utils/virtualenv.py
pyproject.toml
tasks/vendoring/__init__.py
tests/integration/conftest.py
tests/integration/test_dot_venv.py
tests/integration/test_install_basic.py
tests/integration/test_install_markers.py
tests/integration/test_install_twists.py
tests/integration/test_install_uri.py
tests/integration/test_project.py
tests/integration/test_requirements.py
tests/integration/test_uninstall.py
tests/unit/test_cmdparse.py
tests/unit/test_utils_windows_executable.py

Upgrade pre-commit to run the current version of `ruff` and add pyupgrade …

ci: ruff --select=FLY,UP --target-version=py37 --fix .

---

docker/Makefile
docker/README.md

Makefile step to build and push all images

Witchcraft and sourcery - Makefile improvements

---

news/5804.vendor.rst
pipenv/environment.py
pipenv/routines/clean.py
pipenv/utils/__init__.py
pipenv/utils/pip.py
pipenv/utils/pipfile.py

Working on reusing rich from pipenv, so we can reuse vendored libs from it.

 Cleanup secho

---

README.md

I'm sure it could be further documented in the readme, but here's at least a basic start.

Document `upgrade` command in the `Readme`

---

pipenv/resolver.py
pipenv/routines/install.py
pipenv/utils/funktools.py
pipenv/utils/processes.py
pipenv/utils/resolver.py
pipenv/utils/toml.py
tests/integration/conftest.py
tests/integration/test_install_categories.py
tests/integration/test_install_twists.py

Get the CI green again -- also remove click.secho from one of the files I had to touch.

fix ruff complaints

---

pipenv/routines/update.py

Do not lock or sync when running in outdated mode

---

pipenv/utils/dependencies.py
pipenv/utils/requirements.py

Pass editable for vcs when specified

---

pipenv/routines/lock.py

Restore this code that should prevent the string has no attribute update bug.

---

news/6072.bugfix.rst
pipenv/routines/shell.py
tests/conftest.py
tests/integration/test_run.py

Fixes #4909 
Removes patch that affected code execution but was no longer required for the CI anyway.

Recheck if this logic is needed

---

news/6079.bugfix.rst
pipenv/utils/shell.py
pipenv/utils/virtualenv.py

Issue-6079 Remove debug print statements that mistakenly got released

---

tests/integration/test_cli.py

debugging weird CI failures

---

docs/diagnose.md

PiPenv -> Pipenv

---

pipenv/utils/virtualenv.py

We need to be more careful to merge contributor PRs when it involves conversions of a code path, at least expected the code path has been executed by the dev making the change.

Correction to the rich conversion

---

pipenv/exceptions.py

Make this code path more safe to prevent stack trace/regression.

---

pipenv/utils/resolver.py

Fix the assumption that all distributions are named

---

pipenv/routines/check.py

Fixes #6228
Leveraged Google Gemini-1.5 large context to give a concise summary of image and proposed fix, given context of the complete code base.   I think fed this into Claude manually and replaced the routine for do_check, and initiated test run.

Refactor do_check routine to be more modular and address concerns about quiet flag

---

docs/requirements.txt
news/6291.bugfix.rst

try rebuilding the docs

---

news/6299.bugfix.rst
pipenv/project.py
pipenv/routines/graph.py
pipenv/routines/update.py
tests/integration/conftest.py
tests/integration/test_install_twists.py
tests/integration/test_install_uri.py
tests/integration/test_update.py

... and don't require lockfile to exist
Fixes #6299 

refinements to update -- determine which packages may need upgrading

---

.pre-commit-config.yaml
pipenv/project.py
pipenv/routines/outdated.py
pyproject.toml

ci: bump ruff in pre-commit

---

tasks/release.py

When the Changelog generates today it uses the wrong version info.

Fix changelog generation during release.

---

pipenv/utils/dependencies.py
tests/integration/test_install_nested_setup.py

If your pull request makes a significant change to Pipenv, such as the user interface or intended functionality, please open a discussion or issue report first.

Apply variant of fix for wrong cononical name in Pipfile.
